import { Prisma, type PrismaClient } from "@prisma/client";
import { randomUUID } from "node:crypto";
import { db } from "@/lib/db/client";
import { requireCurrentCustomer } from "@/lib/auth/context";
import { requireAdmin } from "@/lib/auth/admin";
import { ReturnDomainError } from "@/lib/returns/errors";
import { cancellationEligibility, returnEligibility, assertCancellationTransition, assertReturnTransition, validateReturnQuantity, validateInspection, type ReturnReason, type CancellationLifecycle, type ReturnLifecycle } from "@/lib/returns/domain";
import { createReturnsRepository, type ReturnsOrder } from "@/lib/returns/repository";
import { toCancellationDto, toReturnDto } from "@/lib/returns/dto";
import type { CancellationDto, ReturnDto, ExceptionSummary } from "@/lib/returns/contracts";

const ACTIVE_RETURN_STATUSES: ReadonlySet<string> = new Set(["REQUESTED","UNDER_REVIEW","APPROVED","RETURN_IN_TRANSIT","RETURN_RECEIVED","INSPECTION_PENDING","INSPECTED","RESOLUTION_PENDING"]);
const REASON_VALUES = new Set<ReturnReason>(["WRONG_ITEM","DAMAGED","DEFECTIVE","SIZE_OR_FIT","NOT_AS_EXPECTED","CHANGED_MIND","OTHER"]);

function ref(prefix:string){ return prefix + randomUUID().replaceAll("-","").slice(0,32).toUpperCase(); }
function windowDays(){ const value=Number(process.env.RETURN_WINDOW_DAYS ?? "7"); return Number.isInteger(value)&&value>=0&&value<=365 ? value : 7; }
function requestText(value:unknown,max:number,required=false){ if(value===undefined||value===null){if(required) throw new ReturnDomainError("INVALID_REQUEST","Required text is missing."); return null;} if(typeof value!=="string"||value.trim().length===0||value.length>max) throw new ReturnDomainError("INVALID_REQUEST","Request text is invalid."); return value.trim(); }
function isRetryable(error:unknown){return error instanceof Prisma.PrismaClientKnownRequestError && error.code==="P2034";}
async function retry<T>(fn:()=>Promise<T>):Promise<T>{for(let i=0;i<3;i++){try{return await fn();}catch(e){if(!isRetryable(e)||i===2)throw e;}}throw new Error("unreachable");}
function mapError(error:unknown):never{if(error instanceof ReturnDomainError)throw error;throw new ReturnDomainError("DATABASE_ERROR","The request could not be completed safely.",undefined,{cause:error});}

export type ReturnsApplicationDependencies={database?:PrismaClient};
export type ReturnsApplication={
 getCustomerExceptionSummary(input:{orderNumber:string;request?:Request}):Promise<ExceptionSummary>;
 requestCancellation(input:{orderNumber:string;reason:string;description?:string;request?:Request}):Promise<CancellationDto>;
 reviewCancellation(input:{reference:string;decision:"APPROVE"|"REJECT";reason?:string;request?:Request}):Promise<CancellationDto>;
 requestReturn(input:{orderNumber:string;items:{orderItemReference:string;quantity:number}[];reasonCode:ReturnReason;description?:string;request?:Request}):Promise<ReturnDto>;
 reviewReturn(input:{reference:string;decision:"APPROVE"|"REJECT";reason?:string;request?:Request}):Promise<ReturnDto>;
 authorizeReturnShipment(input:{reference:string;carrier?:string;trackingNumber?:string;trackingUrl?:string;request?:Request}):Promise<ReturnDto>;
 markReturnReceived(input:{reference:string;request?:Request}):Promise<ReturnDto>;
 inspectReturn(input:{reference:string;receivedQuantity:number;acceptedQuantity:number;rejectedQuantity:number;outcome:"ACCEPTED"|"PARTIALLY_ACCEPTED"|"REJECTED";reason?:string;request?:Request}):Promise<ReturnDto>;
 resolveReturn(input:{reference:string;type:"REFUND"|"REPLACEMENT"|"STORE_CREDIT"|"REJECTED"|"PARTIAL_REFUND";refundAmount?:string;note?:string;request?:Request}):Promise<ReturnDto>;
 getCustomerReturn(input:{reference:string;request?:Request}):Promise<ReturnDto>;
 getCustomerCancellation(input:{reference:string;request?:Request}):Promise<CancellationDto>;
};

export function createReturnsApplication(dependencies:ReturnsApplicationDependencies={}):ReturnsApplication{
 const database=dependencies.database??db;
 async function customer(request?:Request){const current=await requireCurrentCustomer(request);return current.customer;}
 async function orderForCustomer(orderNumber:string,customerId:string,client=database){const order=await createReturnsRepository(client).getOrderByNumber(orderNumber,customerId);if(!order)throw new ReturnDomainError("ORDER_NOT_FOUND","Order could not be found.");return order;}
 function stateForOrder(order:ReturnsOrder){const shipment=order.shipments.slice().sort((a,b)=>b.updatedAt.getTime()-a.updatedAt.getTime())[0]??null;return {orderStatus:order.status,fulfillmentStatus:order.fulfillment?.status??null,hasShipment:order.shipments.length>0,shipmentStatus:shipment?.status??null,deliveredAt:shipment?.deliveredAt??null,paymentSucceeded:order.payment.status==="SUCCEEDED"&&!!order.payment.completedAt};}
 async function getCustomerExceptionSummary(input:{orderNumber:string;request?:Request}):Promise<ExceptionSummary>{
   const c=await customer(input.request); const order=await orderForCustomer(input.orderNumber,c.id); const state=stateForOrder(order);
   const cancellation=order.cancellationRequests[0] ? "already_requested" : cancellationEligibility(state);
   const existingActive=order.returnRequests.some((r)=>ACTIVE_RETURN_STATUSES.has(r.status));
   const ret=existingActive ? "already_requested" : returnEligibility({...state,now:new Date(),returnWindowDays:windowDays()});
   return {cancellation,return:ret};
 }
 async function requestCancellation(input:{orderNumber:string;reason:string;description?:string;request?:Request}){
   try{
    const c=await customer(input.request); const reason=requestText(input.reason,120,true)!; const description=requestText(input.description,2000);
    const result=await retry(()=>database.$transaction(async tx=>{
      const repo=createReturnsRepository(tx); const order=await repo.getOrderByNumber(input.orderNumber,c.id); if(!order)throw new ReturnDomainError("ORDER_NOT_FOUND","Order could not be found.");
      const existing=order.cancellationRequests[0]; if(existing)return existing;
      const eligibility=cancellationEligibility(stateForOrder(order)); if(eligibility==="no_longer_possible")throw new ReturnDomainError("CANCELLATION_NOT_ELIGIBLE","This order can no longer be cancelled.");
      const status:CancellationLifecycle=eligibility==="eligible" ? "APPROVED" : "REQUIRES_REVIEW";
      const created=await tx.cancellationRequest.create({data:{cancellationReference:ref("CAN-"),customerId:c.id,orderId:order.id,status:"REQUESTED",reason,customerDescription:description}});
      await repo.audit({actorType:"CUSTOMER",actorId:c.id,action:"CANCELLATION_REQUESTED",previousState:null,newState:"REQUESTED",reason,orderId:order.id,cancellationRequestId:created.id});
      await repo.notify({customerId:c.id,orderId:order.id,type:"CANCELLATION_REQUESTED"});
      {assertCancellationTransition("REQUESTED",status);await tx.cancellationRequest.update({where:{id:created.id},data:{status,reviewedAt:new Date()}});await repo.audit({actorType:"SYSTEM",action:"CANCELLATION_APPROVED",previousState:"REQUESTED",newState:status,reason:eligibility==="eligible"?"commercially_eligible":"operational_review_required",orderId:order.id,cancellationRequestId:created.id});}
      return tx.cancellationRequest.findUnique({where:{id:created.id},include:{order:true}});
    }));
    return toCancellationDto(result);
   }catch(e){return mapError(e);}
 }
 async function reviewCancellation(input:{reference:string;decision:"APPROVE"|"REJECT";reason?:string;request?:Request}){
  try{const admin=await requireAdmin(input.request);const reason=requestText(input.reason,500);
   const result=await database.$transaction(async tx=>{const row=await tx.cancellationRequest.findFirst({where:{cancellationReference:input.reference},include:{order:true}});if(!row)throw new ReturnDomainError("ORDER_NOT_FOUND","Cancellation could not be found.");
    const next=input.decision==="APPROVE"?"APPROVED":"REJECTED";if(row.status===next)return row;assertCancellationTransition(row.status as CancellationLifecycle,next);
    await tx.cancellationRequest.update({where:{id:row.id},data:{status:next,reviewedAt:new Date(),operationalReason:reason}});
    await tx.commerceExceptionAuditEvent.create({data:{actorType:"ADMIN",actorId:admin.customer.id,action:input.decision==="APPROVE"?"CANCELLATION_APPROVED":"CANCELLATION_REJECTED",previousState:row.status,newState:next,reason,orderId:row.orderId,cancellationRequestId:row.id}});
    await tx.notificationEvent.create({data:{customerId:row.customerId,orderId:row.orderId,type:input.decision==="APPROVE"?"CANCELLATION_APPROVED":"CANCELLATION_REJECTED"}});
    return tx.cancellationRequest.findUnique({where:{id:row.id},include:{order:true}});
   }); return toCancellationDto(result);
  }catch(e){return mapError(e);}
 }
 async function requestReturn(input:{orderNumber:string;items:{orderItemReference:string;quantity:number}[];reasonCode:ReturnReason;description?:string;request?:Request}){
  try{
   const c=await customer(input.request);if(!REASON_VALUES.has(input.reasonCode))throw new ReturnDomainError("INVALID_REQUEST","Return reason is invalid.");
   const description=requestText(input.description,2000);if(!Array.isArray(input.items)||input.items.length<1||input.items.length>50)throw new ReturnDomainError("RETURN_ITEM_INVALID","Return items are invalid.");
   return toReturnDto(await retry(()=>database.$transaction(async tx=>{
    const repo=createReturnsRepository(tx);const order=await repo.getOrderByNumber(input.orderNumber,c.id);if(!order)throw new ReturnDomainError("ORDER_NOT_FOUND","Order could not be found.");
    if(order.returnRequests.some((r)=>ACTIVE_RETURN_STATUSES.includes(r.status)))throw new ReturnDomainError("RETURN_ALREADY_REQUESTED","An active return request already exists.");
    const state=stateForOrder(order);const eligibility=returnEligibility({...state,now:new Date(),returnWindowDays:windowDays()});if(eligibility!=="eligible")throw new ReturnDomainError("RETURN_NOT_ELIGIBLE",`Return is not eligible: ${eligibility.replaceAll("_"," ")}.`);
    const seen=new Set<string>();const quantities=new Map<string,number>();
    for(const item of input.items){if(typeof item.orderItemReference!=="string"||seen.has(item.orderItemReference))throw new ReturnDomainError("RETURN_ITEM_INVALID","Return items are invalid.");seen.add(item.orderItemReference);validateReturnQuantity(item.quantity);quantities.set(item.orderItemReference,item.quantity);}
    const existing=await tx.returnItem.findMany({where:{orderItemId:{in:[...quantities.keys()]},returnRequest:{status:{notIn:["REJECTED"]}}},select:{orderItemId:true,quantity:true}});
    const existingMap=new Map<string,number>();for(const x of existing)existingMap.set(x.orderItemId,(existingMap.get(x.orderItemId)??0)+x.quantity);
    const orderItems=new Map(order.items.map((x)=>[x.id,x] as const));
    for(const [id,qty] of quantities){const oi=orderItems.get(id);if(!oi)throw new ReturnDomainError("RETURN_ITEM_INVALID","Return item is not part of this order.");const used=existingMap.get(id)??0;if(used+qty>oi.quantity)throw new ReturnDomainError("RETURN_QUANTITY_EXCEEDED","Requested return quantity exceeds the purchased quantity.");}
    const created=await tx.returnRequest.create({data:{returnReference:ref("RET-"),customerId:c.id,orderId:order.id,status:"REQUESTED",reasonCode:input.reasonCode,customerDescription:description,items:{create:[...quantities.entries()].map(([orderItemId,quantity])=>({orderItemId,quantity}))}}});
    await repo.audit({actorType:"CUSTOMER",actorId:c.id,action:"RETURN_REQUESTED",previousState:null,newState:"REQUESTED",orderId:order.id,returnRequestId:created.id});
    await repo.notify({customerId:c.id,orderId:order.id,returnRequestId:created.id,type:"RETURN_REQUESTED"});
    return tx.returnRequest.findUnique({where:{id:created.id},include:{items:{include:{orderItem:true}},order:true,shipment:true,inspection:true,resolution:true}});
   })));
  }catch(e){return mapError(e);}
 }
 async function getCustomerReturn(input:{reference:string;request?:Request}){try{const c=await customer(input.request);const row=await createReturnsRepository().getReturn(input.reference,c.id);if(!row)throw new ReturnDomainError("RETURN_NOT_FOUND","Return could not be found.");return toReturnDto(row);}catch(e){return mapError(e);}}
 async function getCustomerCancellation(input:{reference:string;request?:Request}){try{const c=await customer(input.request);const row=await createReturnsRepository().getCancellation(input.reference,c.id);if(!row)throw new ReturnDomainError("ORDER_NOT_FOUND","Cancellation could not be found.");return toCancellationDto(row);}catch(e){return mapError(e);}}
 async function reviewReturn(input:{reference:string;decision:"APPROVE"|"REJECT";reason?:string;request?:Request}){try{const admin=await requireAdmin(input.request);const reason=requestText(input.reason,500);return toReturnDto(await database.$transaction(async tx=>{const row=await tx.returnRequest.findUnique({where:{returnReference:input.reference},include:{items:{include:{orderItem:true}},order:true,shipment:true,inspection:true,resolution:true}});if(!row)throw new ReturnDomainError("RETURN_NOT_FOUND","Return could not be found.");const next=input.decision==="APPROVE"?"APPROVED":"REJECTED";if(row.status!==next)assertReturnTransition(row.status as ReturnLifecycle,next);await tx.returnRequest.update({where:{id:row.id},data:{status:next,reviewedAt:new Date(),operationalReason:reason}});await tx.commerceExceptionAuditEvent.create({data:{actorType:"ADMIN",actorId:admin.customer.id,action:input.decision==="APPROVE"?"RETURN_APPROVED":"RETURN_REJECTED",previousState:row.status,newState:next,reason,orderId:row.orderId,returnRequestId:row.id}});await tx.notificationEvent.create({data:{customerId:row.customerId,orderId:row.orderId,returnRequestId:row.id,type:input.decision==="APPROVE"?"RETURN_APPROVED":"RETURN_REJECTED"}});return tx.returnRequest.findUnique({where:{id:row.id},include:{items:{include:{orderItem:true}},order:true,shipment:true,inspection:true,resolution:true}});}));}catch(e){return mapError(e);}}
 async function adminReturn(reference:string,request?:Request){await requireAdmin(request);const row=await createReturnsRepository().getReturn(reference,"");if(!row)throw new ReturnDomainError("RETURN_NOT_FOUND","Return could not be found.");return row;}
 async function authorizeReturnShipment(input:{reference:string;carrier?:string;trackingNumber?:string;trackingUrl?:string;request?:Request}){try{const admin=await requireAdmin(input.request);const carrier=requestText(input.carrier,120);const trackingNumber=requestText(input.trackingNumber,160);const trackingUrl=requestText(input.trackingUrl,1000);if(trackingUrl){const url=new URL(trackingUrl);if(url.protocol!=="http:"&&url.protocol!=="https:")throw new ReturnDomainError("INVALID_REQUEST","Tracking URL must use HTTP(S).");}return toReturnDto(await database.$transaction(async tx=>{const row=await tx.returnRequest.findUnique({where:{returnReference:input.reference},include:{items:{include:{orderItem:true}},order:true,shipment:true,inspection:true,resolution:true}});if(!row)throw new ReturnDomainError("RETURN_NOT_FOUND","Return could not be found.");if(row.status!=="APPROVED")throw new ReturnDomainError("RETURN_INVALID_TRANSITION","Return must be approved before shipment authorization.");if(row.shipment)return tx.returnRequest.findUnique({where:{id:row.id},include:{items:{include:{orderItem:true}},order:true,shipment:true,inspection:true,resolution:true}});await tx.returnShipment.create({data:{returnRequestId:row.id,sourceShipmentId:null,reference:ref("RSH-"),status:"RETURN_AUTHORIZED",carrier,trackingNumber,trackingUrl,externallySupplied:true}});assertReturnTransition(row.status as ReturnLifecycle,"RETURN_IN_TRANSIT");await tx.returnRequest.update({where:{id:row.id},data:{status:"RETURN_IN_TRANSIT"}});await tx.commerceExceptionAuditEvent.create({data:{actorType:"ADMIN",actorId:admin.customer.id,action:"RETURN_APPROVED",previousState:"APPROVED",newState:"RETURN_IN_TRANSIT",reason:"return_shipment_authorized",orderId:row.orderId,returnRequestId:row.id}});return tx.returnRequest.findUnique({where:{id:row.id},include:{items:{include:{orderItem:true}},order:true,shipment:true,inspection:true,resolution:true}});}));}catch(e){return mapError(e);}}
 async function markReturnReceived(input:{reference:string;request?:Request}){try{const admin=await requireAdmin(input.request);return toReturnDto(await database.$transaction(async tx=>{const row=await tx.returnRequest.findUnique({where:{returnReference:input.reference},include:{items:{include:{orderItem:true}},order:true,shipment:true,inspection:true,resolution:true}});if(!row)throw new ReturnDomainError("RETURN_NOT_FOUND","Return could not be found.");if(row.status==="RETURN_RECEIVED")return row;if(row.status!=="RETURN_IN_TRANSIT")throw new ReturnDomainError("RETURN_INVALID_TRANSITION","Return must be in transit before receipt.");assertReturnTransition(row.status as ReturnLifecycle,"RETURN_RECEIVED");await tx.returnShipment.update({where:{returnRequestId:row.id},data:{status:"RETURN_RECEIVED"}});await tx.returnRequest.update({where:{id:row.id},data:{status:"RETURN_RECEIVED"}});await tx.commerceExceptionAuditEvent.create({data:{actorType:"ADMIN",actorId:admin.customer.id,action:"RETURN_RECEIVED",previousState:row.status,newState:"RETURN_RECEIVED",orderId:row.orderId,returnRequestId:row.id}});await tx.notificationEvent.create({data:{customerId:row.customerId,orderId:row.orderId,returnRequestId:row.id,type:"RETURN_RECEIVED"}});return tx.returnRequest.findUnique({where:{id:row.id},include:{items:{include:{orderItem:true}},order:true,shipment:true,inspection:true,resolution:true}});}));}catch(e){return mapError(e);}}
 async function inspectReturn(input:{reference:string;receivedQuantity:number;acceptedQuantity:number;rejectedQuantity:number;outcome:"ACCEPTED"|"PARTIALLY_ACCEPTED"|"REJECTED";reason?:string;request?:Request}){try{const admin=await requireAdmin(input.request);return toReturnDto(await database.$transaction(async tx=>{const row=await tx.returnRequest.findUnique({where:{returnReference:input.reference},include:{items:true,order:true,shipment:true,inspection:true,resolution:true}});if(!row)throw new ReturnDomainError("RETURN_NOT_FOUND","Return could not be found.");if(row.status!=="RETURN_RECEIVED")throw new ReturnDomainError("RETURN_INSPECTION_INVALID","Return must be received before inspection.");const returned=row.items.reduce((sum,i)=>sum+i.quantity,0);validateInspection(input.receivedQuantity,input.acceptedQuantity,input.rejectedQuantity,returned);if(row.inspection)return tx.returnRequest.findUnique({where:{id:row.id},include:{items:{include:{orderItem:true}},order:true,shipment:true,inspection:true,resolution:true}});await tx.returnInspection.create({data:{returnRequestId:row.id,receivedQuantity:input.receivedQuantity,acceptedQuantity:input.acceptedQuantity,rejectedQuantity:input.rejectedQuantity,outcome:input.outcome,internalReason:requestText(input.reason,500),operatorId:admin.customer.id}});assertReturnTransition(row.status as ReturnLifecycle,"INSPECTION_PENDING");await tx.returnRequest.update({where:{id:row.id},data:{status:"INSPECTION_PENDING"}});assertReturnTransition("INSPECTION_PENDING","INSPECTED");await tx.returnRequest.update({where:{id:row.id},data:{status:"INSPECTED"}});return tx.returnRequest.findUnique({where:{id:row.id},include:{items:{include:{orderItem:true}},order:true,shipment:true,inspection:true,resolution:true}});}));}catch(e){return mapError(e);}}
 async function resolveReturn(input:{reference:string;type:"REFUND"|"REPLACEMENT"|"STORE_CREDIT"|"REJECTED"|"PARTIAL_REFUND";refundAmount?:string;note?:string;request?:Request}){try{const admin=await requireAdmin(input.request);if(input.type!=="REJECTED")throw new ReturnDomainError("REFUND_UNAVAILABLE","Payment/refund, replacement, and store-credit execution are not implemented in the existing architecture; resolution is stopped at the explicit integration boundary.");return toReturnDto(await database.$transaction(async tx=>{const row=await tx.returnRequest.findUnique({where:{returnReference:input.reference},include:{items:{include:{orderItem:true}},order:true,shipment:true,inspection:true,resolution:true}});if(!row)throw new ReturnDomainError("RETURN_NOT_FOUND","Return could not be found.");if(row.status==="RESOLVED")return row;if(row.status!=="INSPECTED"&&row.status!=="RESOLUTION_PENDING")throw new ReturnDomainError("RETURN_RESOLUTION_INVALID","Return is not ready for resolution.");if(!row.inspection)throw new ReturnDomainError("RETURN_RESOLUTION_INVALID","Return inspection is required.");if(!row.resolution)await tx.returnResolution.create({data:{returnRequestId:row.id,type:"REJECTED",note:requestText(input.note,500),resolvedBy:admin.customer.id}});assertReturnTransition(row.status as ReturnLifecycle,"RESOLUTION_PENDING");await tx.returnRequest.update({where:{id:row.id},data:{status:"RESOLUTION_PENDING"}});assertReturnTransition("RESOLUTION_PENDING","RESOLVED");await tx.returnRequest.update({where:{id:row.id},data:{status:"RESOLVED",resolvedAt:new Date()}});await tx.commerceExceptionAuditEvent.create({data:{actorType:"ADMIN",actorId:admin.customer.id,action:"RETURN_RESOLVED",previousState:row.status,newState:"RESOLVED",reason:input.note??"rejected_resolution",orderId:row.orderId,returnRequestId:row.id}});await tx.notificationEvent.create({data:{customerId:row.customerId,orderId:row.orderId,returnRequestId:row.id,type:"RETURN_RESOLUTION_COMPLETED"}});return tx.returnRequest.findUnique({where:{id:row.id},include:{items:{include:{orderItem:true}},order:true,shipment:true,inspection:true,resolution:true}});}));}catch(e){return mapError(e);}}
 return {getCustomerExceptionSummary,requestCancellation,reviewCancellation,requestReturn,reviewReturn,authorizeReturnShipment,markReturnReceived,inspectReturn,resolveReturn,getCustomerReturn,getCustomerCancellation};
}
