import { db } from "@/lib/db/client";
import { requireAdmin } from "@/lib/auth/admin";
import { requireCurrentCustomer } from "@/lib/auth/context";
import { createReturnsApplication } from "@/lib/returns/application";
import { createShippingApplication } from "@/lib/shipping/application";
import { createFulfillmentApplication } from "@/lib/fulfillment/application";
import { Prisma } from "@prisma/client";
import { CaseDomainError } from "@/lib/cases/errors";
import { assertCaseTransition, CASE_CATEGORIES, CASE_PRIORITIES, CASE_RESOLUTIONS, type CaseCategory, type CasePriority, type CaseResolutionType, type CaseStatus } from "@/lib/cases/domain";
import type { CustomerCaseDto, InternalCaseDto } from "@/lib/cases/contracts";
import { getCaseByReference, caseInclude } from "@/lib/cases/repository";

const MAX_TITLE=200, MAX_DESCRIPTION=4000, MAX_NOTE=4000;
const statusLabels:Record<CaseStatus,string>={OPEN:"Open",TRIAGED:"Triaged",ASSIGNED:"Assigned",IN_PROGRESS:"In progress",WAITING:"Waiting",RESOLVED:"Resolved",CLOSED:"Closed"};

function text(value:unknown,max:number,required=false){if(value===undefined||value===null||value===""){if(required)throw new CaseDomainError("INVALID_REQUEST","Required text is missing.");return null;}if(typeof value!=="string"||value.trim().length>max)throw new CaseDomainError("INVALID_REQUEST","Text input is invalid.");return value.trim();}
export function parseCaseCategory(value:unknown):CaseCategory{if(typeof value==="string"&&(CASE_CATEGORIES as readonly string[]).includes(value))return value as CaseCategory;throw new CaseDomainError("INVALID_REQUEST","Case category is invalid.");}
export function parseCasePriority(value:unknown):CasePriority{if(typeof value==="string"&&(CASE_PRIORITIES as readonly string[]).includes(value))return value as CasePriority;throw new CaseDomainError("INVALID_REQUEST","Case priority is invalid.");}
export function parseCaseResolution(value:unknown):CaseResolutionType{if(typeof value==="string"&&(CASE_RESOLUTIONS as readonly string[]).includes(value))return value as CaseResolutionType;throw new CaseDomainError("INVALID_REQUEST","Case resolution is invalid.");}
export function parseCaseStatus(value:unknown):CaseStatus{const allowed=["OPEN","TRIAGED","ASSIGNED","IN_PROGRESS","WAITING","RESOLVED","CLOSED"];if(typeof value==="string"&&allowed.includes(value))return value as CaseStatus;throw new CaseDomainError("INVALID_REQUEST","Case status is invalid.");}
function reference(prefix:string){return prefix+crypto.randomUUID().replaceAll("-","").slice(0,32).toUpperCase();}

async function requireAuthorizedOperator(id:string){const operator=await db.adminUser.findFirst({where:{customerId:id,status:"ACTIVE"},select:{id:true,customerId:true}});if(!operator)throw new CaseDomainError("FORBIDDEN","The selected operator is not authorized.");return operator;}

async function createCase(input:{customerId?:string;orderId?:string;orderItemId?:string;shipmentId?:string;fulfillmentId?:string;returnRequestId?:string;cancellationRequestId?:string;paymentId?:string;category:CaseCategory;title:string;description?:string|null;source:"CUSTOMER"|"SYSTEM"|"OPERATOR";sourceReference?:string|null;deduplicationKey?:string|null;priority?:CasePriority;request?:Request}){
 if(input.source==="SYSTEM"&&!input.sourceReference)throw new CaseDomainError("INVALID_REQUEST","System cases require a source reference.");
 if(input.source==="SYSTEM"&&!input.deduplicationKey)throw new CaseDomainError("INVALID_REQUEST","System cases require a deduplication key.");
 if(input.source==="CUSTOMER"&&!input.customerId)throw new CaseDomainError("INVALID_REQUEST","Customer cases require an authenticated customer.");
  return db.$transaction(async tx=>{
   if(input.deduplicationKey){const existing=await tx.case.findUnique({where:{deduplicationKey:input.deduplicationKey},include:caseInclude});if(existing)return existing;}
   let customerId=input.customerId??null;
   if(input.orderId){const order=await tx.order.findUnique({where:{id:input.orderId},select:{customerId:true}});if(!order)throw new CaseDomainError("CASE_NOT_FOUND","Related order could not be found.");if(customerId&&order.customerId!==customerId)throw new CaseDomainError("FORBIDDEN","The order does not belong to the customer.");customerId=order.customerId;}
   const created=await tx.case.create({data:{caseReference:reference("CASE-"),customerId,orderId:input.orderId??null,orderItemId:input.orderItemId??null,shipmentId:input.shipmentId??null,fulfillmentId:input.fulfillmentId??null,returnRequestId:input.returnRequestId??null,cancellationRequestId:input.cancellationRequestId??null,paymentId:input.paymentId??null,category:input.category,title:input.title,customerDescription:input.description??null,source:input.source,sourceReference:input.sourceReference??null,deduplicationKey:input.deduplicationKey??null,priority:input.priority??"NORMAL"},include:caseInclude});
   await tx.caseAuditEvent.create({data:{caseId:created.id,actorId:input.source==="CUSTOMER"?customerId:null,action:"CREATED",previousState:null,newState:"OPEN",reason:input.source}});
   return created;
 },{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});
}

function customerDto(row:Awaited<ReturnType<typeof getCaseByReference>>):CustomerCaseDto{if(!row)throw new CaseDomainError("CASE_NOT_FOUND","Case could not be found.");return {caseReference:row.caseReference,category:row.category as CaseCategory,status:row.status as CaseStatus,statusLabel:statusLabels[row.status as CaseStatus],title:row.title,description:row.customerDescription,orderReference:row.order?.orderNumber??null,shipmentReference:row.shipment?.shipmentReference??null,returnReference:row.returnRequest?.returnReference??null,createdAt:row.createdAt.toISOString(),updatedAt:row.updatedAt.toISOString(),resolvedAt:row.resolvedAt?.toISOString()??null,closedAt:row.closedAt?.toISOString()??null};}
function internalDto(row:Awaited<ReturnType<typeof getCaseByReference>>):InternalCaseDto{if(!row)throw new CaseDomainError("CASE_NOT_FOUND","Case could not be found.");return {...customerDto(row),priority:row.priority as CasePriority,source:row.source,sourceReference:row.sourceReference,assignedOperatorId:row.assignedOperatorId,resolutionType:row.resolutionType as CaseResolutionType|null,resolutionSummary:row.resolutionSummary,correlationId:row.correlationId,version:row.version,notes:row.notes.map(n=>({id:n.id,body:n.body,authorId:n.authorId,createdAt:n.createdAt.toISOString()}))};}

async function getCustomerCases(request?:Request){const c=await requireCurrentCustomer(request);const rows=await db.case.findMany({where:{customerId:c.customer.id},orderBy:{createdAt:"desc"},take:50,include:caseInclude});return rows.map(customerDto);}
async function getCustomerCase(referenceValue:string,request?:Request){const c=await requireCurrentCustomer(request);return customerDto(await getCaseByReference(referenceValue,c.customer.id));}
async function createCustomerCase(input:{category:CaseCategory;title:string;description?:string;orderNumber?:string;request?:Request;idempotencyKey?:string}){const c=await requireCurrentCustomer(input.request);const title=text(input.title,MAX_TITLE,true)!;const description=text(input.description,MAX_DESCRIPTION);let orderId:string|undefined;if(input.orderNumber){const order=await db.order.findFirst({where:{orderNumber:input.orderNumber,customerId:c.customer.id},select:{id:true}});if(!order)throw new CaseDomainError("CASE_NOT_FOUND","Order could not be found.");orderId=order.id;}const key=input.idempotencyKey?"customer:"+c.customer.id+":"+input.idempotencyKey.slice(0,180):null;return customerDto(await createCase({customerId:c.customer.id,orderId,category:input.category,title,description,source:"CUSTOMER",deduplicationKey:key,request:input.request}));}
async function createOperatorCase(input:{idempotencyKey?:string;customerId?:string;orderId?:string;orderItemId?:string;shipmentId?:string;fulfillmentId?:string;returnRequestId?:string;cancellationRequestId?:string;paymentId?:string;category:CaseCategory;title:string;description?:string;priority?:CasePriority;request?:Request}){const admin=await requireAdmin(input.request,"case.create");const title=text(input.title,MAX_TITLE,true)!;const description=text(input.description,MAX_DESCRIPTION);const deduplicationKey=input.idempotencyKey?"admin:"+admin.customer.id+":"+input.idempotencyKey.slice(0,180):null;return internalDto(await createCase({...input,title,description,source:"OPERATOR",deduplicationKey,request:input.request}));}
async function createSystemCase(input:{category:CaseCategory;title:string;description?:string|null;source:"SYSTEM";sourceReference:string;deduplicationKey:string;orderId?:string;orderItemId?:string;shipmentId?:string;fulfillmentId?:string;returnRequestId?:string;cancellationRequestId?:string;paymentId?:string;priority?:CasePriority;request?:Request}){return internalDto(await createCase(input));}

async function listInternalCases(query:{status?:CaseStatus;category?:CaseCategory;priority?:CasePriority;assignedOperatorId?:string;orderReference?:string;limit?:number;cursor?:string;request?:Request}){await requireAdmin(query.request,"case.read");const take=Math.min(Math.max(query.limit??50,1),100);const rows=await db.case.findMany({where:{status:query.status,category:query.category,priority:query.priority,assignedOperatorId:query.assignedOperatorId,order:query.orderReference?{orderNumber:query.orderReference}:undefined},orderBy:[{updatedAt:"desc"},{id:"desc"}],take:take+1,...(query.cursor?{cursor:{id:query.cursor},skip:1}:{}),include:caseInclude});const more=rows.length>take;return {items:(more?rows.slice(0,take):rows).map(internalDto),nextCursor:more?rows[take-1]?.id??null:null};}
async function getInternalCase(referenceValue:string,request?:Request){await requireAdmin(request,"case.read");return internalDto(await getCaseByReference(referenceValue));}
async function assignCase(input:{reference:string;operatorId:string;idempotencyKey?:string;request?:Request}){const admin=await requireAdmin(input.request,"case.assign");await requireAuthorizedOperator(input.operatorId);return internalDto(await db.$transaction(async tx=>{const row=await tx.case.findUnique({where:{caseReference:input.reference}});if(!row)throw new CaseDomainError("CASE_NOT_FOUND","Case could not be found.");if(input.idempotencyKey){const prior=await tx.caseAuditEvent.findFirst({where:{caseId:row.id,correlationId:input.idempotencyKey,action:"ASSIGNED"}});if(prior)return tx.case.findUnique({where:{id:row.id},include:caseInclude});}if(row.status==="CLOSED")throw new CaseDomainError("CASE_CONFLICT","Closed cases cannot be assigned.");const next=row.status==="OPEN"||row.status==="TRIAGED"?"ASSIGNED":row.status;const updated=await tx.case.updateMany({where:{id:row.id,version:row.version},data:{assignedOperatorId:input.operatorId,status:next,version:{increment:1}}});if(updated.count!==1)throw new CaseDomainError("CASE_CONFLICT","Case changed concurrently.");const result=await tx.case.findUnique({where:{id:row.id},include:caseInclude});if(!result)throw new CaseDomainError("CASE_NOT_FOUND","Case could not be found.");await tx.caseAssignment.create({data:{caseId:row.id,operatorId:input.operatorId}});await tx.caseAuditEvent.create({data:{caseId:row.id,actorId:admin.customer.id,action:"ASSIGNED",previousState:row.status,newState:next,reason:"assignment",correlationId:input.idempotencyKey}});return result;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable}));}
async function addNote(input:{reference:string;body:string;idempotencyKey?:string;request?:Request}){const admin=await requireAdmin(input.request,"case.update");const body=text(input.body,MAX_NOTE,true)!;return internalDto(await db.$transaction(async tx=>{const row=await tx.case.findUnique({where:{caseReference:input.reference}});if(!row)throw new CaseDomainError("CASE_NOT_FOUND","Case could not be found.");if(input.idempotencyKey){const prior=await tx.caseAuditEvent.findFirst({where:{caseId:row.id,correlationId:input.idempotencyKey,action:"NOTE_ADDED"}});if(prior)return tx.case.findUnique({where:{id:row.id},include:caseInclude});}await tx.caseNote.create({data:{caseId:row.id,authorId:admin.customer.id,body}});await tx.caseAuditEvent.create({data:{caseId:row.id,actorId:admin.customer.id,action:"NOTE_ADDED",reason:"internal_note",correlationId:input.idempotencyKey}});return tx.case.findUnique({where:{id:row.id},include:caseInclude});},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable}));}
async function transitionCase(input:{reference:string;to:CaseStatus;reason?:string;idempotencyKey?:string;request?:Request}){const admin=await requireAdmin(input.request,"case.update");const reason=text(input.reason,1000);return internalDto(await db.$transaction(async tx=>{const row=await tx.case.findUnique({where:{caseReference:input.reference}});if(!row)throw new CaseDomainError("CASE_NOT_FOUND","Case could not be found.");if(input.idempotencyKey){const prior=await tx.caseAuditEvent.findFirst({where:{caseId:row.id,correlationId:input.idempotencyKey,action:"TRANSITIONED"}});if(prior)return tx.case.findUnique({where:{id:row.id},include:caseInclude});}assertCaseTransition(row.status as CaseStatus,input.to);const updated=await tx.case.updateMany({where:{id:row.id,version:row.version},data:{status:input.to,version:{increment:1}}});if(updated.count!==1)throw new CaseDomainError("CASE_CONFLICT","Case changed concurrently.");const result=await tx.case.findUnique({where:{id:row.id},include:caseInclude});if(!result)throw new CaseDomainError("CASE_NOT_FOUND","Case could not be found.");await tx.caseAuditEvent.create({data:{caseId:row.id,actorId:admin.customer.id,action:"TRANSITIONED",previousState:row.status,newState:input.to,reason,correlationId:input.idempotencyKey}});return result;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable}));}
async function updatePriority(input:{reference:string;priority:CasePriority;idempotencyKey?:string;request?:Request}){const admin=await requireAdmin(input.request,"case.update");return internalDto(await db.$transaction(async tx=>{const row=await tx.case.findUnique({where:{caseReference:input.reference}});if(!row)throw new CaseDomainError("CASE_NOT_FOUND","Case could not be found.");if(input.idempotencyKey){const prior=await tx.caseAuditEvent.findFirst({where:{caseId:row.id,correlationId:input.idempotencyKey,action:"PRIORITY_CHANGED"}});if(prior)return tx.case.findUnique({where:{id:row.id},include:caseInclude});}if(row.status==="CLOSED")throw new CaseDomainError("CASE_CONFLICT","Closed cases cannot change priority.");const updated=await tx.case.updateMany({where:{id:row.id,version:row.version},data:{priority:input.priority,version:{increment:1}}});if(updated.count!==1)throw new CaseDomainError("CASE_CONFLICT","Case changed concurrently.");const result=await tx.case.findUnique({where:{id:row.id},include:caseInclude});if(!result)throw new CaseDomainError("CASE_NOT_FOUND","Case could not be found.");await tx.caseAuditEvent.create({data:{caseId:row.id,actorId:admin.customer.id,action:"PRIORITY_CHANGED",previousState:row.priority,newState:input.priority,correlationId:input.idempotencyKey}});return result;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable}));}
async function resolveCase(input:{reference:string;resolutionType:CaseResolutionType;summary:string;idempotencyKey?:string;request?:Request}){const admin=await requireAdmin(input.request,"case.resolve");const summary=text(input.summary,1000,true)!;const row=await getCaseByReference(input.reference);if(!row)throw new CaseDomainError("CASE_NOT_FOUND","Case could not be found.");if(row.status==="CLOSED")throw new CaseDomainError("CASE_CONFLICT","Case is already closed.");if(["REFUND_REQUESTED","REFUND_COMPLETED"].includes(input.resolutionType))throw new CaseDomainError("REFUND_UNAVAILABLE","Refund resolution must use the Payment application service; no direct case refund execution is available.");
 if(input.resolutionType==="RETURN_APPROVED"||input.resolutionType==="RETURN_REJECTED"){if(!row.returnRequest?.returnReference)throw new CaseDomainError("CASE_CONFLICT","Case has no return reference.");await createReturnsApplication().reviewReturn({reference:row.returnRequest.returnReference,decision:input.resolutionType==="RETURN_APPROVED"?"APPROVE":"REJECT",reason:summary,idempotencyKey:input.idempotencyKey,request:input.request});}
 else if(input.resolutionType==="ORDER_CANCELLED"){if(!row.cancellationRequest?.cancellationReference)throw new CaseDomainError("CASE_CONFLICT","Case has no cancellation reference.");await createReturnsApplication().reviewCancellation({reference:row.cancellationRequest.cancellationReference,decision:"APPROVE",reason:summary,idempotencyKey:input.idempotencyKey,request:input.request});}
 else if(input.resolutionType==="SHIPMENT_RECONCILED"){if(!row.shipmentId)throw new CaseDomainError("CASE_CONFLICT","Case has no shipment reference.");await createShippingApplication().reconcileShipment({shipmentId:row.shipmentId});}
 else if(input.resolutionType==="FULFILLMENT_RESOLVED"){if(!row.fulfillmentId)throw new CaseDomainError("CASE_CONFLICT","Case has no fulfillment reference.");await createFulfillmentApplication().reconcileFulfillment({fulfillmentId:row.fulfillmentId});}
 return internalDto(await db.$transaction(async tx=>{const current=await tx.case.findUnique({where:{id:row.id}});if(!current)throw new CaseDomainError("CASE_NOT_FOUND","Case could not be found.");if(current.status==="CLOSED")throw new CaseDomainError("CASE_CONFLICT","Case is already closed.");if(input.idempotencyKey){const prior=await tx.caseAuditEvent.findFirst({where:{caseId:current.id,correlationId:input.idempotencyKey,action:"RESOLVED"}});if(prior)return tx.case.findUnique({where:{id:current.id},include:caseInclude});}if(current.status!=="RESOLVED")assertCaseTransition(current.status as CaseStatus,"RESOLVED");const updated=await tx.case.updateMany({where:{id:current.id,version:current.version},data:{status:"RESOLVED",resolutionType:input.resolutionType,resolutionSummary:summary,resolvedAt:new Date(),version:{increment:1}}});if(updated.count!==1)throw new CaseDomainError("CASE_CONFLICT","Case changed concurrently.");const result=await tx.case.findUnique({where:{id:current.id},include:caseInclude});if(!result)throw new CaseDomainError("CASE_NOT_FOUND","Case could not be found.");await tx.caseAuditEvent.create({data:{caseId:current.id,actorId:admin.customer.id,action:"RESOLVED",previousState:current.status,newState:"RESOLVED",reason:summary,correlationId:input.idempotencyKey}});return result;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable}));}
async function closeCase(input:{reference:string;reason:string;idempotencyKey?:string;request?:Request}){const admin=await requireAdmin(input.request,"case.resolve");const reason=text(input.reason,1000,true)!;return internalDto(await db.$transaction(async tx=>{const row=await tx.case.findUnique({where:{caseReference:input.reference}});if(!row)throw new CaseDomainError("CASE_NOT_FOUND","Case could not be found.");if(input.idempotencyKey){const prior=await tx.caseAuditEvent.findFirst({where:{caseId:row.id,correlationId:input.idempotencyKey,action:"CLOSED"}});if(prior)return tx.case.findUnique({where:{id:row.id},include:caseInclude});}if(row.status!=="RESOLVED")throw new CaseDomainError("CASE_CONFLICT","Case must be resolved before closure.");const updated=await tx.case.updateMany({where:{id:row.id,version:row.version},data:{status:"CLOSED",closedAt:new Date(),version:{increment:1}}});if(updated.count!==1)throw new CaseDomainError("CASE_CONFLICT","Case changed concurrently.");const result=await tx.case.findUnique({where:{id:row.id},include:caseInclude});if(!result)throw new CaseDomainError("CASE_NOT_FOUND","Case could not be found.");await tx.caseAuditEvent.create({data:{caseId:row.id,actorId:admin.customer.id,action:"CLOSED",previousState:"RESOLVED",newState:"CLOSED",reason,correlationId:input.idempotencyKey}});return result;},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable}));}
export function createCaseApplication(){return {createCustomerCase,getCustomerCases,getCustomerCase,createOperatorCase,createSystemCase,listInternalCases,getInternalCase,assignCase,addNote,transitionCase,updatePriority,resolveCase,closeCase};}
