export const CASE_TRANSITIONS: Record<CaseStatus, readonly CaseStatus[]> = {
  OPEN:["TRIAGED"], TRIAGED:["ASSIGNED","IN_PROGRESS","WAITING"], ASSIGNED:["IN_PROGRESS","WAITING"], IN_PROGRESS:["WAITING","RESOLVED"], WAITING:["IN_PROGRESS","RESOLVED"], RESOLVED:["CLOSED"], CLOSED:[]
} as const;
export type CaseStatus="OPEN"|"TRIAGED"|"ASSIGNED"|"IN_PROGRESS"|"WAITING"|"RESOLVED"|"CLOSED";
export const CASE_CATEGORIES=["ORDER_ISSUE","PAYMENT_ISSUE","FULFILLMENT_ISSUE","SHIPPING_ISSUE","DELIVERY_ISSUE","TRACKING_ISSUE","CANCELLATION_REVIEW","RETURN_REVIEW","RETURN_INSPECTION","REFUND_ISSUE","PROVIDER_EXCEPTION","RECONCILIATION_EXCEPTION","CUSTOMER_SUPPORT"] as const;
export type CaseCategory=typeof CASE_CATEGORIES[number];
export const CASE_PRIORITIES=["LOW","NORMAL","HIGH","URGENT"] as const;
export type CasePriority=typeof CASE_PRIORITIES[number];
export const CASE_RESOLUTIONS=["INFORMATION_PROVIDED","CUSTOMER_ACTION_REQUIRED","PROVIDER_RECONCILED","ORDER_CANCELLED","RETURN_APPROVED","RETURN_REJECTED","REFUND_REQUESTED","REFUND_COMPLETED","SHIPMENT_RECONCILED","FULFILLMENT_RESOLVED","NO_ACTION_REQUIRED","DUPLICATE","ESCALATED"] as const;
export type CaseResolutionType=typeof CASE_RESOLUTIONS[number];
export function assertCaseTransition(from:CaseStatus,to:CaseStatus){if(!CASE_TRANSITIONS[from].includes(to))throw new Error(`Invalid case transition: ${from} -> ${to}`);}
export function isTerminalCaseStatus(status:CaseStatus){return status==="CLOSED";}
