[build]
command = "npx prisma migrate deploy && npm run build"
functions = "netlify/functions"

[build.environment]
NODE_VERSION = "24.21.0"
NPM_VERSION = "11.6.0"

[functions]
node_bundler = "esbuild"

[dev]
framework = "nextjs"
