import {createHash,randomUUID} from "node:crypto";
import {db} from "@/lib/db/client";
export const RELEASE_LIMITS={maxStages:12,maxExposure:100,maxObservationSeconds:86400,maxEvidence:1000} as const;
const strategies=["CANARY","COHORT","PERCENTAGE","FEATURE_FLAG","REGION","CUSTOMER_SEGMENT","FULL_RELEASE"] as const;
const next:Record<string,readonly string[]>={DRAFT:["READY_CHECK","BLOCKED"],READY_CHECK:["READY","BLOCKED"],READY:["SCHEDULED","CANARY_PENDING"],SCHEDULED:["CANARY_PENDING","BLOCKED"],CANARY_PENDING:["CANARY_RUNNING"],CANARY_RUNNING:["CANARY_VALIDATING","PAUSED","ABORTED"],CANARY_VALIDATING:["CANARY_APPROVED","PAUSED","ROLLED_BACK"],CANARY_APPROVED:["PROGRESSIVE_ROLLOUT","FULL_RELEASE_PENDING"],PROGRESSIVE_ROLLOUT:["ROLLOUT_VALIDATING","PAUSED","ABORTED","ROLLED_BACK"],ROLLOUT_VALIDATING:["FULL_RELEASE_PENDING","PAUSED","ROLLED_BACK"],FULL_RELEASE_PENDING:["FULL_RELEASE","PAUSED"],FULL_RELEASE:["POST_RELEASE_MONITORING","PAUSED","ROLLED_BACK"],POST_RELEASE_MONITORING:["VERIFIED","PAUSED","ROLLED_BACK"],VERIFIED:["CERTIFIED","INVALIDATED"],CERTIFIED:["INVALIDATED"],PAUSED:["CANARY_RUNNING","PROGRESSIVE_ROLLOUT","FULL_RELEASE","ABORTED","ROLLED_BACK"],BLOCKED:[],ABORTED:[],ROLLED_BACK:[],FAILED:[],INVALIDATED:[]};
const safe=(v:unknown):unknown=>{if(v===null||["string","number","boolean"].includes(typeof v))return v;if(Array.isArray(v))return v.slice(0,100).map(safe);if(typeof v==="object"){const o:Record<string,unknown>={};for(const[k,x]of Object.entries(v as Record<string,unknown>))o[k]=/password|secret|token|authorization|cookie|apiKey|privateKey|cardNumber|cvv/i.test(k)?"[REDACTED]":safe(x);return o}return "[UNSUPPORTED]"};
const hash=(v:unknown)=>createHash("sha256").update(JSON.stringify(safe(v))).digest("hex");
const transition=(from:string,to:string)=>{if(!next[from]?.includes(to))throw new Error(`Illegal release transition: ${from} -> ${to}`)};
export async function readiness(id:string,actor:string){const r=await db.release.findUnique({where:{id}});if(!r||!["DRAFT","READY_CHECK"].includes(r.status))throw new Error("Release is not in readiness state");const c=await db.changeRequest.findUnique({where:{id:r.changeRequestId}}),a=await db.releaseArtifact.findUnique({where:{id:r.artifactId}});const checks:Array<[string,boolean]>=[["CHANGE_APPROVAL",!!c&&c.revision===r.changeRevision&&["APPROVED","REHEARSAL_CERTIFIED","READY_FOR_RELEASE","RELEASE_WINDOW_OPEN"].includes(c.status)],["ARTIFACT_INTEGRITY",!!a&&a.approved&&!a.superseded],["POLICY",!!r.policyVersion],["ROLLBACK_DECLARED",!!r.rollbackStrategy],["BOUNDED_TARGET",r.target!==null&&typeof r.target==="object"]];await db.releaseGate.deleteMany({where:{releaseId:id}});for(const [g,ok] of checks)await db.releaseGate.create({data:{releaseId:id,key:g,category:g,metric:g,baseline:{},threshold:{required:true},evaluationWindowSeconds:60,minimumSampleSize:1,failureTolerance:{maxFailures:0},action:ok?"CONTINUE":"BLOCK",required:true,result:ok?"PASS":"BLOCKED"}});const ok=checks.every(x=>x[1]);const to=ok?"READY":"BLOCKED";await db.release.update({where:{id},data:{status:to}});await audit(id,"READY",r.status,to,actor,r.policyVersion,ok?"Readiness passed":"Critical prerequisite failed");await evidence(id,"READINESS",{checks,passed:ok},actor);return {passed:ok,checks};}
async function evidence(id:string,type:string,payload:unknown,actor:string){return db.releaseEvidence.create({data:{releaseId:id,evidenceType:type as never,source:"phase-15.35",reference:randomUUID(),integrityHash:hash(payload),payload:safe(payload) as never,capturedBy:actor}})}
export async function createRelease(i:{stableId:string;changeRequestId:string;changeRevision:number;artifactId:string;environment:string;target:unknown;ownerId:string;strategy:string;policyVersion:string;validationStrategy:unknown;rollbackStrategy:unknown;releaseWindowId?:string}){if(!(strategies as readonly string[]).includes(i.strategy))throw new Error("Unsupported rollout strategy");const c=await db.changeRequest.findUnique({where:{id:i.changeRequestId}});if(!c||c.revision!==i.changeRevision||!["APPROVED","REHEARSAL_CERTIFIED","READY_FOR_RELEASE","RELEASE_WINDOW_OPEN"].includes(c.status))throw new Error("Current approved ChangeRequest required");const a=await db.releaseArtifact.findUnique({where:{id:i.artifactId}});if(!a||!a.approved||a.superseded)throw new Error("Approved non-superseded artifact required");const old=await db.release.findUnique({where:{stableId:i.stableId}});if(old)return old;return db.release.create({data:{stableId:i.stableId,changeRequestId:i.changeRequestId,changeRevision:i.changeRevision,artifactId:i.artifactId,environment:i.environment.slice(0,80),target:safe(i.target) as never,ownerId:i.ownerId,strategy:i.strategy as never,status:"DRAFT",risk:String(c.risk),policyVersion:i.policyVersion,validationStrategy:safe(i.validationStrategy) as never,rollbackStrategy:safe(i.rollbackStrategy) as never,releaseWindowId:i.releaseWindowId,correlationId:randomUUID()}})}
export async function readiness(id:string,actor:string){const r=await db.release.findUnique({where:{id}});if(!r||!["DRAFT","READY_CHECK"].includes(r.status))throw new Error("Release is not in readiness state");const c=await db.changeRequest.findUnique({where:{id:r.changeRequestId}}),a=await db.releaseArtifact.findUnique({where:{id:r.artifactId}});const checks=[["CHANGE_APPROVAL",!!c&&c.revision===r.changeRevision&&["APPROVED","REHEARSAL_CERTIFIED","READY_FOR_RELEASE","RELEASE_WINDOW_OPEN"].includes(c.status)],["ARTIFACT_INTEGRITY",!!a&&a.approved&&!a.superseded],["POLICY",!!r.policyVersion],["ROLLBACK_DECLARED",!!r.rollbackStrategy],["BOUNDED_TARGET",r.target!==null&&typeof r.target==="object"]];await db.releaseGate.deleteMany({where:{releaseId:id}});for(const[g,ok]of checks)await db.releaseGate.create({data:{releaseId:id,key:g,category:g,metric:g,baseline:{},threshold:{required:true},evaluationWindowSeconds:60,minimumSampleSize:1,failureTolerance:{maxFailures:0},action:ok?"CONTINUE":"BLOCK",required:true,result:ok?"PASS":"BLOCKED"}});const ok=checks.every(x=>x[1]);const to=ok?"READY":"BLOCKED";await db.release.update({where:{id},data:{status:to}});await audit(id,"READY",r.status,to,actor,r.policyVersion,ok?"Readiness passed":"Critical prerequisite failed");await evidence(id,"READINESS",{checks,passed:ok},actor);return {passed:ok,checks};}
export async function configureStages(id:string,stages:{name:string;exposure:number;minObservationSeconds:number}[]){if(!stages.length||stages.length>RELEASE_LIMITS.maxStages)throw new Error("Invalid stage count");let previous=0;for(const s of stages){if(!Number.isInteger(s.exposure)||s.exposure<0||s.exposure>100||s.exposure<previous)throw new Error("Exposure must be bounded and monotonic");if(!Number.isInteger(s.minObservationSeconds)||s.minObservationSeconds<0||s.minObservationSeconds>86400)throw new Error("Invalid observation window");previous=s.exposure}await db.releaseStage.deleteMany({where:{releaseId:id}});return Promise.all(stages.map((s,n)=>db.releaseStage.create({data:{releaseId:id,ordinal:n+1,name:s.name.slice(0,80),exposure:{percentage:s.exposure},minObservationSeconds:s.minObservationSeconds,maxExposure:s.exposure,progressionPolicy:{requiredHealthGates:true},rollbackPolicy:{validatedOnly:true}}})));}
export async function schedule(id:string,actor:string){const r=await db.release.findUnique({where:{id}});if(!r||r.status!=="READY")throw new Error("Release must be READY");if(!r.releaseWindowId)throw new Error("Release window required");const w=await db.releaseWindow.findUnique({where:{id:r.releaseWindowId}});if(!w||w.frozen)throw new Error("Release window unavailable");await db.release.update({where:{id},data:{status:"SCHEDULED"}});await audit(id,"SCHEDULE","READY","SCHEDULED",actor,r.policyVersion,"Scheduled in governed window");return db.release.findUnique({where:{id}});}
export async function startCanary(id:string,actor:string){const r=await db.release.findUnique({where:{id},include:{stages:true}});if(!r||!["SCHEDULED","CANARY_PENDING"].includes(r.status)||!r.stages.length)throw new Error("Canary prerequisites not met");await db.release.update({where:{id},data:{status:"CANARY_RUNNING"}});await audit(id,"START",r.status,"CANARY_RUNNING",actor,r.policyVersion,"Canary started without deployment side effects");return db.release.findUnique({where:{id},include:{stages:true}});}
export async function evaluateStage(id:string,ordinal:number,actor:string){
 const r=await db.release.findUnique({where:{id},include:{stages:true,gates:true}});
 if(!r)throw new Error("Release not found");
 const stage=r.stages.find(x=>x.ordinal===ordinal); if(!stage)throw new Error("Stage not found");
 const failedGate=r.gates.some(g=>g.required&&g.result!=="PASS");
 const evidenceCount=await db.releaseEvidence.count({where:{releaseId:id,evidenceType:"HEALTH"}});
 const passed=!failedGate&&evidenceCount>0;
 let to=r.status;
 if(r.status==="CANARY_RUNNING")to="CANARY_VALIDATING";
 else if(r.status==="CANARY_VALIDATING")to=passed?"CANARY_APPROVED":"PAUSED";
 else if(r.status==="PROGRESSIVE_ROLLOUT")to="ROLLOUT_VALIDATING";
 else if(r.status==="ROLLOUT_VALIDATING")to=passed?"FULL_RELEASE_PENDING":"PAUSED";
 else if(r.status==="FULL_RELEASE")to="POST_RELEASE_MONITORING";
 else if(r.status==="POST_RELEASE_MONITORING")to=passed?"VERIFIED":"PAUSED";
 transition(r.status,to);
const executionData={stageId:stage.id,idempotencyKey:hash({id,ordinal,version:r.version}),actorId:actor,result:(passed?"PASSED":"FAILED") as never,healthSnapshot:{evidenceCount,failedGate},decision:{passed:passed,next:to},correlationId:randomUUID()};await db.releaseStageExecution.create({data:executionData});
 await db.releaseStage.update({where:{id:stage.id},data:{status:passed?"PASSED":"FAILED",completedAt:new Date()}});
 await db.release.update({where:{id},data:{status:to as never}});
 await audit(id,"VALIDATE",r.status,to,actor,r.policyVersion,passed?"Stage passed":"Stage paused: missing health evidence or failed gate");
 await evidence(id,"PROGRESSION",{ordinal,passed,to},actor);
 return {passed,to};
}
export async function pause(id:string,actor:string){const r=await db.release.findUnique({where:{id}});if(!r||["CERTIFIED","INVALIDATED","ABORTED","ROLLED_BACK"].includes(r.status))throw new Error("Release cannot be paused");await db.release.update({where:{id},data:{status:"PAUSED"}});await db.releasePause.create({data:{releaseId:id,reason:"MANUAL",details:{},stageOrdinal:0,healthSnapshot:{},actorId:actor}});await audit(id,"PAUSE",r.status,"PAUSED",actor,r.policyVersion,"Governed pause");return db.release.findUnique({where:{id}});}
export async function resume(id:string,actor:string){const r=await db.release.findUnique({where:{id},include:{stages:true}});if(!r||r.status!=="PAUSED")throw new Error("Release is not paused");const to=r.stages.some(x=>x.status==="PASSED")?"PROGRESSIVE_ROLLOUT":"CANARY_RUNNING";transition("PAUSED",to);await db.release.update({where:{id},data:{status:to}});await audit(id,"RESUME","PAUSED",to,actor,r.policyVersion,"Governed resume");return db.release.findUnique({where:{id}});}
export async function abort(id:string,actor:string){const r=await db.release.findUnique({where:{id}});if(!r||["CERTIFIED","INVALIDATED","ROLLED_BACK"].includes(r.status))throw new Error("Release cannot be aborted");await db.release.update({where:{id},data:{status:"ABORTED"}});await audit(id,"ABORT",r.status,"ABORTED",actor,r.policyVersion,"Abort performs no business mutation");return db.release.findUnique({where:{id}});}
export async function rollback(id:string,actor:string){const r=await db.release.findUnique({where:{id}});if(!r)throw new Error("Release not found");const rs=r.rollbackStrategy as Record<string,unknown>;if(rs?.validated!==true)throw new Error("Rollback is not proven safe");await db.release.update({where:{id},data:{status:"ROLLED_BACK"}});await db.releaseRollback.create({data:{releaseId:id,stageOrdinal:0,trigger:"GOVERNED",policy:rs as never,strategy:rs as never,result:"SAFE_ELIGIBILITY_RECORDED",remainingImpact:{},actorId:actor,validated:true}});await audit(id,"ROLLBACK",r.status,"ROLLED_BACK",actor,r.policyVersion,"Eligibility proven; provider execution remains disabled");return db.release.findUnique({where:{id}});}
export async function validate(id:string,actor:string){const r=await db.release.findUnique({where:{id},include:{gates:true}});if(!r)throw new Error("Release not found");const passed=["POST_RELEASE_MONITORING","VERIFIED"].includes(r.status)&&r.gates.every(g=>!g.required||g.result==="PASS");const to=passed?"VERIFIED":"PAUSED";transition(r.status,to);await db.release.update({where:{id},data:{status:to}});await audit(id,"VALIDATE",r.status,to,actor,r.policyVersion,passed?"Post-release validation passed":"Post-release validation blocked");return {passed,status:to};}
export async function certify(id:string,actor:string){const r=await db.release.findUnique({where:{id},include:{gates:true}});if(!r||r.status!=="VERIFIED")throw new Error("Release must be VERIFIED");const c=await db.releaseCertification.create({data:{releaseId:id,status:"CERTIFIED",artifactHash:hash(r.artifactId),policyVersion:r.policyVersion,dependencySnapshot:{phase:"15.32",freshness:"required"},healthEvidence:{gates:r.gates},validationEvidence:{verified:true},validUntil:new Date(Date.now()+86400000),certifiedBy:actor}});await db.release.update({where:{id},data:{status:"CERTIFIED"}});await audit(id,"CERTIFY","VERIFIED","CERTIFIED",actor,r.policyVersion,"Release certified");return c;}
export async function invalidate(id:string,reason:string,actor:string){const r=await db.release.findUnique({where:{id}});if(!r)throw new Error("Release not found");await db.release.update({where:{id},data:{status:"INVALIDATED",version:{increment:1}}});await db.releaseInvalidation.create({data:{releaseId:id,reason:reason.slice(0,500),changedDomain:"governance",previousVersion:r.version,actorId:actor}});return db.release.findUnique({where:{id}});}
export async function listReleases(limit=50){return db.release.findMany({take:Math.min(Math.max(limit,1),100),orderBy:{updatedAt:"desc"},include:{stages:true,gates:true,certifications:{orderBy:{certifiedAt:"desc"},take:1}}});}
export async function detail(id:string){return db.release.findUnique({where:{id},include:{stages:{orderBy:{ordinal:"asc"}},gates:true,decisions:{orderBy:{createdAt:"desc"},take:50},evidence:{orderBy:{createdAt:"desc"},take:100},certifications:{orderBy:{certifiedAt:"desc"},take:5},pauses:{orderBy:{createdAt:"desc"},take:20},rollbacks:{orderBy:{createdAt:"desc"},take:20}}});}
