import Link from "next/link";
import { notFound } from "next/navigation";
import { requireAdmin } from "@/lib/admin/authorization";
import { AdminError } from "@/lib/admin/errors";
import { getAdminFulfillment } from "@/lib/admin/fulfillment";
import { AdminFulfillmentAction } from "@/components/admin/fulfillment-action";

export default async function AdminFulfillmentDetailPage({params}:{params:Promise<{fulfillmentId:string}>}){
 const context=await requireAdmin(undefined,"fulfillment.read");let fulfillment;
 try{fulfillment=await getAdminFulfillment((await params).fulfillmentId,context);}catch(error){if(error instanceof AdminError&&error.code==="NOT_FOUND")notFound();throw error;}
 const endpoint="/api/admin/fulfillments/"+fulfillment.id;
 const canSubmit=context.permissions.has("fulfillment.submit")&&fulfillment.status==="PENDING";
 const canRetry=context.permissions.has("fulfillment.retry")&&fulfillment.status==="FAILED"&&!fulfillment.failure.reconciliationRequired;
 const canReconcile=context.permissions.has("fulfillment.reconcile")&&fulfillment.failure.reconciliationRequired;
 return <section className="space-y-6">
  <header className="border-4 border-black bg-[#f7d51d] p-6 shadow-[8px_8px_0_0_#000]"><Link href="/admin/fulfillments" className="font-black underline">← Fulfillment</Link><p className="mt-4 text-xs font-black uppercase tracking-[0.2em]">{fulfillment.status}</p><h2 className="mt-1 break-all text-4xl font-black uppercase">{fulfillment.id}</h2><p className="mt-2 text-sm">Order {fulfillment.orderNumber} · Provider {fulfillment.provider}</p><div className="mt-4 flex flex-wrap gap-2">{canSubmit&&<AdminFulfillmentAction endpoint={endpoint} action="submit"/>}{canRetry&&<AdminFulfillmentAction endpoint={endpoint} action="retry"/>}{canReconcile&&<AdminFulfillmentAction endpoint={endpoint} action="reconcile"/>}</div></header>
  <div className="grid gap-6 xl:grid-cols-2">
   <section className="border-4 border-black bg-white p-5 shadow-[6px_6px_0_0_#000]"><h3 className="text-xl font-black uppercase">Fulfillment state</h3><dl className="mt-4 grid gap-3 sm:grid-cols-2"><div><dt className="text-xs font-black uppercase">Status</dt><dd className="font-black">{fulfillment.status}</dd></div><div><dt className="text-xs font-black uppercase">Provider</dt><dd>{fulfillment.provider}</dd></div><div><dt className="text-xs font-black uppercase">Provider reference</dt><dd className="break-all">{fulfillment.providerReference||"Restricted / unavailable"}</dd></div><div><dt className="text-xs font-black uppercase">Requested</dt><dd>{new Date(fulfillment.requestedAt).toLocaleString("en-IN")}</dd></div><div><dt className="text-xs font-black uppercase">Submitted</dt><dd>{fulfillment.submittedAt?new Date(fulfillment.submittedAt).toLocaleString("en-IN"):"—"}</dd></div><div><dt className="text-xs font-black uppercase">Completed</dt><dd>{fulfillment.completedAt?new Date(fulfillment.completedAt).toLocaleString("en-IN"):"—"}</dd></div></dl>{fulfillment.failure.code&&<div role="alert" className="mt-5 border-2 border-black bg-[#ff5c35] p-3"><p className="font-black uppercase">{fulfillment.failure.code}</p><p className="mt-1 text-sm">{fulfillment.failure.message}</p>{fulfillment.failure.reconciliationRequired&&<p className="mt-2 font-black uppercase">Provider reconciliation required before retry.</p>}</div>}</section>
   <section className="border-4 border-black bg-white p-5 shadow-[6px_6px_0_0_#000]"><h3 className="text-xl font-black uppercase">Order & customer</h3><p className="mt-3 font-black"><Link className="underline" href={"/admin/orders/"+fulfillment.orderNumber}>{fulfillment.orderNumber}</Link></p><div className="mt-4 border-2 border-black p-3"><p className="font-black">{fulfillment.customer.displayName||"Unnamed customer"}</p><p>{fulfillment.customer.email}</p><p className="mt-1 break-all text-xs">Customer ID: {fulfillment.customer.id}</p></div></section>
  </div>
  <section className="border-4 border-black bg-white p-5 shadow-[6px_6px_0_0_#000]"><h3 className="text-xl font-black uppercase">Fulfillment items</h3><div className="mt-4 grid gap-3">{fulfillment.items.map(item=><article key={item.id} className="border-2 border-black p-3"><div className="flex flex-wrap justify-between gap-2"><p className="font-black">{item.productTitle}{item.variantTitle?" · "+item.variantTitle:""}</p><p className="font-black">Qty {item.quantity}</p></div><div className="mt-2 grid gap-1 text-sm sm:grid-cols-2"><p>Store SKU: {item.storeSku||"—"}</p><p>Provider SKU: {item.providerSku||"Restricted"}</p><p>Provider variant: {item.providerVariantReference||"Restricted"}</p><p>Item state: {item.status||"—"}</p></div></article>)}</div></section>
  <div className="grid gap-6 xl:grid-cols-2">
   <section className="border-4 border-black bg-white p-5 shadow-[6px_6px_0_0_#000]"><h3 className="text-xl font-black uppercase">Shipment handoff</h3><div className="mt-4 grid gap-3">{fulfillment.shipments.map(s=><article key={s.id} className="border-2 border-black p-3"><p className="font-black">{s.reference} · {s.status}</p><p className="text-sm">{s.carrier||"Carrier unavailable"} · {s.trackingNumber||"No tracking number"}</p><p className="text-sm">Provider: {s.providerId}{s.providerReference?" · Reference "+s.providerReference:""}</p>{s.reconciliationRequired&&<p className="mt-1 font-black">Shipment reconciliation required.</p>}</article>)}{!fulfillment.shipments.length&&<p>No Shipment is currently associated.</p>}</div></section>
   <section className="border-4 border-black bg-white p-5 shadow-[6px_6px_0_0_#000]"><h3 className="text-xl font-black uppercase">Cancellation / return</h3><div className="mt-4 grid gap-2">{fulfillment.cancellations.map(c=><p key={c.reference} className="border-2 border-black p-2 text-sm"><strong>{c.reference}</strong> · {c.status} · {c.reason}</p>)}{fulfillment.returns.map(r=><p key={r.reference} className="border-2 border-black p-2 text-sm"><strong>{r.reference}</strong> · {r.status} · {r.reasonCode}</p>)}{!fulfillment.cancellations.length&&!fulfillment.returns.length&&<p>No cancellation or return relationship recorded.</p>}</div></section>
  </div>
  {context.permissions.has("fulfillment.audit.read")&&<section className="border-4 border-black bg-white p-5 shadow-[6px_6px_0_0_#000]"><h3 className="text-xl font-black uppercase">Admin audit</h3><div className="mt-4 grid gap-2">{fulfillment.audit.map((a,i)=><p key={a.createdAt+"-"+i} className="border-2 border-black p-2 text-sm">{new Date(a.createdAt).toLocaleString("en-IN")} · <strong>{a.action}</strong> · {a.success?"success":"failure"}{a.reason?" · "+a.reason:""}</p>)}</div></section>}
 </section>;
}
