import test from "node:test";
import assert from "node:assert/strict";
import { confidenceFromEvidence, autonomousMutationAllowed, deterministicAnomaly, validReliabilityTransition, SAFE_STRATEGIES } from "@/lib/reliability/autonomous-model";

test("unknown and low confidence never authorize mutation",()=>{ assert.equal(autonomousMutationAllowed("UNKNOWN","SAFE_AUTOMATION"),false); assert.equal(autonomousMutationAllowed("LOW","SAFE_AUTOMATION"),false); assert.equal(autonomousMutationAllowed("HIGH","APPROVAL_REQUIRED"),false); });
test("confidence is deterministic and bounded",()=>{ assert.equal(confidenceFromEvidence({signalCount:0,contradictions:0,validated:false,stableBaseline:false}),"UNKNOWN"); assert.equal(confidenceFromEvidence({signalCount:1,contradictions:0,validated:false,stableBaseline:false}),"MEDIUM"); assert.equal(confidenceFromEvidence({signalCount:3,contradictions:0,validated:false,stableBaseline:false}),"HIGH"); assert.equal(confidenceFromEvidence({signalCount:3,contradictions:0,validated:true,stableBaseline:true}),"VERIFIED"); assert.equal(confidenceFromEvidence({signalCount:3,contradictions:1,validated:true,stableBaseline:true}),"LOW"); });
test("anomaly detection uses an explainable threshold",()=>{ const normal=deterministicAnomaly({value:101,center:100,spread:2,minimumDeviation:0}); const anomaly=deterministicAnomaly({value:110,center:100,spread:2,minimumDeviation:0}); assert.equal(normal.anomalous,false); assert.equal(anomaly.anomalous,true); assert.match(anomaly.explanation,/exceeds/); });
test("assessment transitions reject unsafe skips",()=>{ assert.equal(validReliabilityTransition("CREATED","CORRELATING"),true); assert.equal(validReliabilityTransition("CREATED","REMEDIATING"),false); assert.equal(validReliabilityTransition("VERIFYING","REGRESSED"),true); assert.equal(validReliabilityTransition("CLOSED","REMEDIATING"),false); });
test("safe strategy is bounded and provider-neutral",()=>{ assert.equal(SAFE_STRATEGIES.SYNTHETIC_RETRY.action,"RERUN_SYNTHETIC_CHECK"); assert.equal(SAFE_STRATEGIES.SYNTHETIC_RETRY.maxSteps,1); assert.equal(SAFE_STRATEGIES.SYNTHETIC_RETRY.maxMutations,1); });
