import test from "node:test";
import assert from "node:assert/strict";
import { assessPolicy,validateSignal,classifyOptimization,comparePolicies,evaluateShadow,evaluateRegression,confidenceFromEvidence,GOVERNANCE_STATES,GOVERNANCE_DECISIONS } from "@/lib/delivery-governance-intelligence/service";

test("policy assessment decomposes safety and efficiency",()=>{const r=assessPolicy({policyId:"p",policyVersion:"1",metrics:{falsePositiveRate:.4,falseNegativeRate:.02,securityFindings:0,operationalToil:.1},evidence:Array.from({length:20},()=>({ok:true}))});assert.equal(r.driftDetected,true);assert.equal(r.dimensions.safety,1);assert.equal(r.dimensions.precision,.6);});
test("signal validation excludes unsafe evidence",()=>{const r=validateSignal({state:"ACTIVE",freshnessSeconds:900,maxAgeSeconds:60,confidence:"HIGH",provenanceValid:true,versionCompatible:true,sourceAvailable:true});assert.equal(r.excluded,true);assert.match(r.exclusionReasons.join(","),/STALE/);});
test("optimization risk blocks prohibited policy weakening",()=>{assert.equal(classifyOptimization({proposedPolicy:{payment:"bypass verification"},affectedSystems:["payments"],paymentChange:true,rollbackCapability:true}),"PROHIBITED");});
test("policy comparison and shadow evaluation are deterministic",()=>{assert.deepEqual(comparePolicies({a:1,b:2},{a:1,b:3,c:4}),[{key:"b",current:2,proposed:3},{key:"c",current:null,proposed:4}]);assert.equal(evaluateShadow({currentResult:{a:1},proposedResult:{a:2},releaseIds:["r"],policyId:"p",policyVersion:"1"}).observationalOnly,true);});
test("regression pauses and confidence is evidence based",()=>{assert.equal(evaluateRegression({baseline:{rollbackRate:.02},candidate:{rollbackRate:.1},thresholds:{rollbackRate:.05}}).regressed,true);assert.equal(confidenceFromEvidence({sampleSize:50,evidenceQuality:1,simulationCoverage:1,environmentConsistency:1,signalFreshness:1,architectureStability:1,outcomeCertainty:1}),"VERIFIED");});
test("lifecycle and decision vocabularies are explicit",()=>{assert.ok(GOVERNANCE_STATES.includes("CERTIFIED"));assert.ok(GOVERNANCE_STATES.includes("INVALIDATED"));assert.ok(GOVERNANCE_DECISIONS.includes("COLLECT_MORE_EVIDENCE"));});
