import { createHash } from "node:crypto";
import { db } from "@/lib/db/client";
import { GRAPH_CONFIDENCE,GRAPH_DRIFT_SEVERITIES,GRAPH_NODE_TYPES,GRAPH_PROVENANCE,GRAPH_RELATION_TYPES,freshnessFrom,isClosed,type GraphNodeType,type GraphProvenance,type GraphConfidence,type GraphRelationType } from "@/lib/platform-graph/model";
const MAX_DEPTH=5,MAX_NODES=250,MAX_PAGE=50;
type Safe=Record<string,unknown>;
const redact=(v:unknown):unknown=>{const walk=(x:unknown,d=0):unknown=>{if(d>6)return "[TRUNCATED]";if(x===null||typeof x==="string"||typeof x==="number"||typeof x==="boolean")return x;if(Array.isArray(x))return x.slice(0,100).map(y=>walk(y,d+1));if(typeof x==="object"){const o:Safe={};for(const[k,y]of Object.entries(x)){o[k]=/password|secret|token|authorization|cookie|apiKey|privateKey|cardNumber|cvv/i.test(k)?"[REDACTED]":walk(y,d+1)}return o}return String(x)};return walk(v)};
const hash=(v:unknown)=>createHash("sha256").update(JSON.stringify(v)).digest("hex");
export function validateGraphNodeType(v:string):GraphNodeType{if(!isClosed(GRAPH_NODE_TYPES,v))throw new Error("Unknown graph node type.");return v}
export function validateGraphRelationType(v:string):GraphRelationType{if(!isClosed(GRAPH_RELATION_TYPES,v))throw new Error("Unknown graph relationship type.");return v}
export function validateGraphProvenance(v:string):GraphProvenance{if(!isClosed(GRAPH_PROVENANCE,v))throw new Error("Unknown graph provenance.");return v}
export function validateGraphConfidence(v:string):GraphConfidence{if(!isClosed(GRAPH_CONFIDENCE,v))throw new Error("Unknown graph confidence.");return v}
export function normalizeTraversalDepth(v:number){return Number.isInteger(v)&&v>=0?Math.min(v,MAX_DEPTH):2}
export function normalizePageSize(v:number){return Number.isInteger(v)&&v>0?Math.min(v,MAX_PAGE):MAX_PAGE}
export async function upsertNode(i:{stableId:string;type:string;name:string;sourceOfTruth?:string;owner?:string;environment?:string;status?:string;confidence?:string;metadata?:unknown}){const type=validateGraphNodeType(i.type),confidence=validateGraphConfidence(i.confidence??"UNKNOWN");if(!i.stableId.trim()||!i.name.trim())throw new Error("Graph node stableId and name are required.");return db.platformGraphNode.upsert({where:{stableId:i.stableId},create:{stableId:i.stableId,type,name:i.name,sourceOfTruth:i.sourceOfTruth??null,owner:i.owner??null,environment:i.environment??null,status:i.status??null,confidence,metadata:redact(i.metadata??{}) as never},update:{type,name:i.name,sourceOfTruth:i.sourceOfTruth??null,owner:i.owner??null,environment:i.environment??null,status:i.status??null,confidence,metadata:redact(i.metadata??{}) as never}})}
export async function upsertRelationship(i:{stableId:string;fromStableId:string;toStableId:string;relationType:string;provenance:string;sourceIdentifier:string;confidence:string;verifier?:string;staleThresholdSeconds?:number;metadata?:unknown}){const relationType=validateGraphRelationType(i.relationType),provenance=validateGraphProvenance(i.provenance),confidence=validateGraphConfidence(i.confidence);if(!i.sourceIdentifier.trim())throw new Error("Relationship provenance source identifier is required.");const[from,to]=await Promise.all([db.platformGraphNode.findUnique({where:{stableId:i.fromStableId}}),db.platformGraphNode.findUnique({where:{stableId:i.toStableId}})]);if(!from||!to)throw new Error("Graph relationship endpoints must already exist.");if(from.id===to.id&&relationType==="DEPENDS_ON")throw new Error("Self dependency is not allowed.");const now=new Date(),threshold=Math.max(60,Math.min(i.staleThresholdSeconds??86400,31536000)),metadata=redact(i.metadata??{});const old=await db.platformGraphRelationship.findUnique({where:{stableId:i.stableId}});const version=old?old.version+1:1;const row=await db.platformGraphRelationship.upsert({where:{stableId:i.stableId},create:{stableId:i.stableId,fromNodeId:from.id,toNodeId:to.id,relationType,provenance,sourceIdentifier:i.sourceIdentifier,confidence,verifier:i.verifier??null,discoveredAt:now,lastVerifiedAt:now,lastObservedAt:now,staleThresholdSeconds:threshold,freshness:"CURRENT",metadata:metadata as never,version,active:true},update:{fromNodeId:from.id,toNodeId:to.id,relationType,provenance,sourceIdentifier:i.sourceIdentifier,confidence,verifier:i.verifier??null,lastVerifiedAt:now,lastObservedAt:now,staleThresholdSeconds:threshold,freshness:"CURRENT",metadata:metadata as never,version,active:true}});await db.platformGraphEvidence.create({data:{relationshipId:row.id,provenance,sourceIdentifier:i.sourceIdentifier,observedAt:now,summary:"Relationship synchronized.",integrityHash:hash({stableId:i.stableId,from:i.fromStableId,to:i.toStableId,relationType,provenance,sourceIdentifier:i.sourceIdentifier}),payload:metadata as never}});return row}
export async function traverse(id:string,direction:"UPSTREAM"|"DOWNSTREAM"|"BOTH",depthInput:number){const depth=normalizeTraversalDepth(depthInput),start=await db.platformGraphNode.findUnique({where:{stableId:id}});if(!start)throw new Error("Graph node not found.");const visited=new Set([start.id]);let frontier=[start.id];const layers=[{depth:0,nodes:[{id:start.id,stableId:start.stableId,type:start.type as GraphNodeType,name:start.name}]}];for(let level=1;level<=depth&&frontier.length&&visited.size<MAX_NODES;level++){const edges=await db.platformGraphRelationship.findMany({where:{active:true,...direction==="DOWNSTREAM"?{fromNodeId:{in:frontier}}:direction==="UPSTREAM"?{toNodeId:{in:frontier}}:{OR:[{fromNodeId:{in:frontier}},{toNodeId:{in:frontier}}]}},include:{fromNode:true,toNode:true},take:MAX_NODES});const next:string[]=[];const nodes:Array<{id:string;stableId:string;type:GraphNodeType;name:string}>=[];for(const e of edges){const n=frontier.includes(e.fromNodeId)?e.toNode:e.fromNode;if(!visited.has(n.id)&&visited.size<MAX_NODES){visited.add(n.id);next.push(n.id);nodes.push({id:n.id,stableId:n.stableId,type:n.type as GraphNodeType,name:n.name})}}if(nodes.length)layers.push({depth:level,nodes});frontier=next}return{start:id,direction,depth,nodeCount:visited.size,layers,truncated:visited.size>=MAX_NODES}}
export async function impactAnalysis(id:string,depth:number){const t=await traverse(id,"BOTH",depth),ids=t.layers.flatMap(x=>x.nodes.map(n=>n.id)),nodes=await db.platformGraphNode.findMany({where:{id:{in:ids}}});const counts:Record<string,number>={};for(const n of nodes)counts[n.type]=(counts[n.type]??0)+1;return{...t,affectedTypes:counts,affectedNodeIds:nodes.map(n=>n.stableId)}}
export async function listNodes(i:{query?:string;type?:string;cursor?:string;limit?:number}){const limit=normalizePageSize(i.limit??MAX_PAGE),type=i.type?validateGraphNodeType(i.type):undefined;const rows=await db.platformGraphNode.findMany({where:{...(type?{type}:{}),...(i.query?{OR:[{stableId:{contains:i.query,mode:"insensitive"}},{name:{contains:i.query,mode:"insensitive"}}]}:{})},orderBy:{stableId:"asc"},take:limit+1,...(i.cursor?{skip:1,cursor:{id:i.cursor}}:{})});return{items:rows.slice(0,limit),nextCursor:rows.length>limit?rows[limit-1]?.id:undefined}}
export async function nodeDetail(id:string){const node=await db.platformGraphNode.findUnique({where:{stableId:id}});if(!node)throw new Error("Graph node not found.");const[dependencies,dependents]=await Promise.all([db.platformGraphRelationship.findMany({where:{fromNodeId:node.id,active:true},include:{toNode:true},take:MAX_PAGE}),db.platformGraphRelationship.findMany({where:{toNodeId:node.id,active:true},include:{fromNode:true},take:MAX_PAGE})]);return{node,dependencies,dependents}}
export async function refreshFreshness(){const edges=await db.platformGraphRelationship.findMany({where:{active:true},take:5000});let updated=0;for(const e of edges){const f=freshnessFrom(e.lastVerifiedAt,e.lastObservedAt,e.staleThresholdSeconds);if(f!==e.freshness){await db.platformGraphRelationship.update({where:{id:e.id},data:{freshness:f}});updated++}}return{checked:edges.length,updated}}
export async function reconcileGraph(){const[nodes,edges]=await Promise.all([db.platformGraphNode.findMany({take:1000}),db.platformGraphRelationship.findMany({where:{active:true},take:2000})]);const ids=new Set(nodes.map(n=>n.id)),findings:Array<{kind:string;severity:string;scope:string;details:unknown}>=[];for(const e of edges){if(!ids.has(e.fromNodeId)||!ids.has(e.toNodeId))findings.push({kind:"ORPHAN_RELATIONSHIP",severity:"HIGH",scope:e.stableId,details:{from:e.fromNodeId,to:e.toNodeId}});const expected=freshnessFrom(e.lastVerifiedAt,e.lastObservedAt,e.staleThresholdSeconds);if(expected!==e.freshness)findings.push({kind:"STALE_RELATIONSHIP",severity:expected==="STALE"?"HIGH":"MEDIUM",scope:e.stableId,details:{stored:e.freshness,expected}})}for(const f of findings)await db.platformGraphFinding.create({data:{kind:f.kind,severity:f.severity as never,scope:f.scope,details:redact(f.details) as never,methodologyVersion:"15.32-v1",status:"OPEN"}});return{nodes:nodes.length,relationships:edges.length,findings}}
export async function detectDrift(i:{kind:string;scope:string;severity:string;details:unknown}){if(!isClosed(GRAPH_DRIFT_SEVERITIES,i.severity))throw new Error("Unknown drift severity.");return db.platformGraphFinding.create({data:{kind:i.kind,scope:i.scope,severity:i.severity as never,details:redact(i.details) as never,methodologyVersion:"15.32-v1",status:"OPEN"}})}
export async function graphHealth(){const[nodes,edges,findings]=await Promise.all([db.platformGraphNode.count(),db.platformGraphRelationship.count({where:{active:true}}),db.platformGraphFinding.count({where:{status:"OPEN"}})]);return{nodes,edges,openFindings:findings,maxTraversalDepth:MAX_DEPTH,maxTraversalNodes:MAX_NODES,modelVersion:"15.32-v1"}}
export async function graphOverview(){const[health,findings,relationships]=await Promise.all([graphHealth(),db.platformGraphFinding.findMany({where:{status:"OPEN"},orderBy:{createdAt:"desc"},take:25}),db.platformGraphRelationship.findMany({where:{active:true},orderBy:{updatedAt:"desc"},take:25,include:{fromNode:true,toNode:true}})]);return{health,findings,relationships}}
export const GRAPH_RULES={nodeTypes:GRAPH_NODE_TYPES,relationshipTypes:GRAPH_RELATION_TYPES,provenance:GRAPH_PROVENANCE,confidence:GRAPH_CONFIDENCE} as const;
