"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

export function CatalogMediaManager({images,canManage}: {images:any[];canManage:boolean}) {
 const router=useRouter();const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 async function add(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const d=Object.fromEntries(new FormData(e.currentTarget).entries());const res=await fetch("/api/admin/catalog/media",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({productId,url:d.url,altText:d.altText||null,isPrimary:d.isPrimary==="on",sortOrder:Number(d.sortOrder||0)})});const b=await res.json().catch(()=>({}));if(!res.ok)setError(b?.error?.message||"Could not add media.");else{e.currentTarget.reset();router.refresh()}setBusy(false)}
 async function remove(id:string){const reason=window.prompt("Reason for removing this media:");if(!reason||reason.trim().length<3)return;setBusy(true);const res=await fetch("/api/admin/catalog/media/"+id,{method:"DELETE",headers:{"content-type":"application/json"},body:JSON.stringify({reason})});const b=await res.json().catch(()=>({}));if(!res.ok)setError(b?.error?.message||"Could not remove media.");else router.refresh();setBusy(false)}
 async function primary(id:string){setBusy(true);const res=await fetch("/api/admin/catalog/media/"+id+"/primary",{method:"POST",headers:{"content-type":"application/json"},body:"{}"});const b=await res.json().catch(()=>({}));if(!res.ok)setError(b?.error?.message||"Could not set primary media.");else router.refresh();setBusy(false)}
 return <div className="space-y-4">{canManage&&<form onSubmit={add} className="grid gap-2 border-2 border-black p-3"><input name="url" required placeholder="Image URL" className="border-2 border-black p-2"/><input name="altText" placeholder="Alt text" className="border-2 border-black p-2"/><label className="flex items-center gap-2 text-sm font-bold"><input name="isPrimary" type="checkbox"/> Primary</label><button disabled={busy} className="border-2 border-black bg-[#f7d51d] p-2 font-bold uppercase">Add media</button></form>}<div className="grid gap-2">{images.map(i=><div key={i.id} className="flex flex-wrap items-center justify-between gap-2 border-2 border-black p-2"><span className="max-w-[60%] truncate text-sm">{i.url}</span><span className="text-xs font-bold">{i.isPrimary?"PRIMARY":""}</span>{canManage&&<div className="flex gap-2">{!i.isPrimary&&<button type="button" onClick={()=>void primary(i.id)} className="border-2 border-black px-2 py-1 text-xs font-bold uppercase">Primary</button>}<button type="button" onClick={()=>void remove(i.id)} className="border-2 border-black bg-[#ff5a36] px-2 py-1 text-xs font-bold uppercase">Remove</button></div>}</div>)}</div>{error&&<p role="alert" className="border-2 border-black bg-[#ff5a36] p-2 font-bold">{error}</p>}</div>;
}