import { requireAdmin } from "@/lib/admin/authorization";
import { getOperationsDashboard } from "@/lib/operations/service";
export const dynamic="force-dynamic";
export default async function OperationsPage(){const context=await requireAdmin(undefined,"operations.read");const dashboard=await getOperationsDashboard();const counts=dashboard.services.reduce<Record<string,number>>((acc,s)=>{acc[s.operationalStatus]=(acc[s.operationalStatus]??0)+1;return acc;},{});const canManage=context.permissions.has("operations.manage");
return <section className="space-y-8"><header className="border-2 border-black bg-white p-4 shadow-[4px_4px_0_0_#000] sm:border-4 sm:p-6 sm:shadow-[8px_8px_0_0_#000]"><p className="text-sm font-black uppercase tracking-[0.2em]">Production operations</p><h2 className="mt-2 text-4xl font-black uppercase">Control plane</h2><p className="mt-3 max-w-3xl text-sm">Continuous service assurance over existing observability, reliability, synthetic monitoring, reconciliation, governance and cost/capacity systems. UNKNOWN is never presented as healthy.</p></header>
<section className="grid gap-3 grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-7">{["HEALTHY","DEGRADED","FAILING","BLOCKED","MAINTENANCE","UNKNOWN","UNAVAILABLE"].map(state=><div key={state} className="border-2 border-black bg-white p-4"><p className="text-xs font-black uppercase">{state}</p><p className="mt-1 text-2xl font-black">{counts[state]??0}</p></div>)}</section>
<section className="border-2 border-black bg-white sm:border-4"><div className="border-b-2 border-black sm:border-b-4 border-black p-4"><h3 className="text-xl font-black uppercase">Service inventory</h3></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead><tr className="border-b-2 border-black"><th className="p-2 sm:p-3">Service</th><th className="p-3">Owner</th><th className="p-3">Criticality</th><th className="p-3">Status</th><th className="p-3">Dependencies</th><th className="p-3">Failure / recovery</th></tr></thead><tbody>{dashboard.services.map(s=><tr key={s.id} className="border-b-2 border-black last:border-0"><td className="p-3"><div className="font-black">{s.name}</div><div className="text-xs">{s.domain}</div></td><td className="p-3">{s.owner}</td><td className="p-3">{s.criticality}</td><td className="p-3 font-black">{s.operationalStatus}</td><td className="p-3">{s.dependencies.join(", ")||"—"}</td><td className="p-3"><div>{s.failureMode}</div><div className="text-xs">{s.recoveryProcedure}</div></td></tr>)}</tbody></table></div></section>
<section className="grid gap-4 lg:grid-cols-2"><div className="border-4 border-black bg-white p-5"><h3 className="font-black uppercase">Dependencies</h3><div className="mt-3 space-y-2 text-sm">{dashboard.dependencyGraph.map(edge=><div key={edge.component+"-"+edge.dependency} className="border-2 border-black p-2"><span className="font-black">{edge.component}</span> → <span className="font-black">{edge.dependency}</span> · {edge.health} · {edge.impact}</div>)}</div></div><div className="border-4 border-black bg-white p-5"><h3 className="font-black uppercase">Operational evidence</h3><dl className="mt-3 grid gap-2 text-sm">{Object.entries({incidents:dashboard.criticalIncidents.length,syntheticFailures:dashboard.summaries.synthetic.failing,reconciliationCritical:dashboard.summaries.reconciliation.critical,governanceFailed:dashboard.summaries.governance.failed,governanceCritical:dashboard.summaries.governance.critical,costAnomalies:dashboard.summaries.costCapacity.openAnomalies,migrationFailures:dashboard.migrationEvidence.failed}).map(([key,value])=><div key={key} className="flex justify-between border-b py-1"><dt>{key}</dt><dd className="font-black">{String(value)}</dd></div>)}</dl></div></section>
<section className="border-4 border-black bg-white p-5"><h3 className="font-black uppercase">Safe operator actions</h3><p className="mt-2 text-sm">Actions are authenticated, permission-gated and audited. No arbitrary shell, URL fetch, SQL execution, payment transaction, fulfillment creation or uncontrolled production mutation is exposed.</p><p className="mt-2 text-sm font-bold">{canManage?"Operations management permission is available through the protected API.":"Read-only operational access."}</p></section>
<section className="border-4 border-black bg-white p-5"><h3 className="font-black uppercase">Runbook registry</h3><div className="mt-3 grid gap-2 md:grid-cols-2">{dashboard.runbooks.map(book=><div key={book.id} className="border-2 border-black p-3"><div className="font-black">{book.id} · {book.title}</div><div className="text-xs uppercase">{book.trigger} · {book.safety}</div></div>)}</div></section></section>}