import Link from "next/link";
import { requireAdmin } from "@/lib/admin/authorization";
import { listAdminShipments, parseAdminShippingQuery } from "@/lib/admin/shipping";
import { AdminShipmentCreate } from "@/components/admin/shipment-action";

export default async function AdminShippingPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const context=await requireAdmin(undefined,"shipping.read");const raw=await searchParams;const url=new URL("https://admin.local/admin/shipping");
 for(const [k,v] of Object.entries(raw)){if(Array.isArray(v))v.forEach(x=>url.searchParams.append(k,x));else if(v!==undefined)url.searchParams.set(k,v);}
 const query=parseAdminShippingQuery(url),data=await listAdminShipments(query,context);
 return <section className="space-y-6">
  <header className="border-4 border-black bg-[#f7d51d] p-6 shadow-[8px_8px_0_0_#000]"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.2em]">Operations control plane</p><h2 className="mt-2 text-4xl font-black uppercase">Shipping</h2><p className="mt-2 max-w-3xl">Canonical Shipment and Tracking visibility. Shipping remains the authority for shipment lifecycle and provider reconciliation.</p></div>{context.permissions.has("shipping.create")&&<AdminShipmentCreate/>}</div></header>
  <form method="get" className="border-4 border-black bg-white p-4 shadow-[6px_6px_0_0_#000]"><div className="grid gap-3 md:grid-cols-4">
   <label className="md:col-span-2"><span className="text-xs font-black uppercase">Search</span><input name="search" defaultValue={query.search||""} placeholder="Shipment, order, customer" className="mt-1 w-full border-2 border-black p-2"/></label>
   <label><span className="text-xs font-black uppercase">Status</span><select name="status" defaultValue={query.status||""} className="mt-1 w-full border-2 border-black p-2"><option value="">All</option>{["CREATED","IN_TRANSIT","OUT_FOR_DELIVERY","DELIVERED","DELIVERY_FAILED","RETURNED"].map(x=><option key={x}>{x}</option>)}</select></label>
   <label><span className="text-xs font-black uppercase">Provider</span><input name="provider" defaultValue={query.provider||""} className="mt-1 w-full border-2 border-black p-2"/></label>
   <label><span className="text-xs font-black uppercase">Carrier</span><input name="carrier" defaultValue={query.carrier||""} className="mt-1 w-full border-2 border-black p-2"/></label>
   {context.permissions.has("shipping.view_sensitive")&&<label><span className="text-xs font-black uppercase">Tracking number</span><input name="trackingNumber" defaultValue={query.trackingNumber||""} className="mt-1 w-full border-2 border-black p-2"/></label>}
   <label><span className="text-xs font-black uppercase">Reconciliation</span><select name="reconciliationRequired" defaultValue={query.reconciliationRequired===undefined?"":String(query.reconciliationRequired)} className="mt-1 w-full border-2 border-black p-2"><option value="">Any</option><option value="true">Required</option><option value="false">Clear</option></select></label>
   <label><span className="text-xs font-black uppercase">Sort</span><select name="sort" defaultValue={query.sort} className="mt-1 w-full border-2 border-black p-2">{["createdAt","updatedAt","shipmentReference","status","providerId","carrier"].map(x=><option key={x}>{x}</option>)}</select></label>
   <label><span className="text-xs font-black uppercase">Direction</span><select name="direction" defaultValue={query.direction} className="mt-1 w-full border-2 border-black p-2"><option value="desc">Descending</option><option value="asc">Ascending</option></select></label>
   <label><span className="text-xs font-black uppercase">From</span><input type="date" name="from" className="mt-1 w-full border-2 border-black p-2"/></label>
   <label><span className="text-xs font-black uppercase">To</span><input type="date" name="to" className="mt-1 w-full border-2 border-black p-2"/></label>
  </div><div className="mt-3 flex gap-2"><button className="border-2 border-black bg-black px-4 py-2 font-black uppercase text-white">Apply filters</button><Link href="/admin/shipping" className="border-2 border-black px-4 py-2 font-black uppercase">Reset</Link></div></form>
  <div className="overflow-x-auto border-4 border-black bg-white"><table className="w-full min-w-[1200px] border-collapse"><caption className="sr-only">Administrative Shipment list</caption><thead><tr className="border-b-4 border-black bg-black text-left text-xs font-black uppercase text-white">{["Shipment","Order","Customer","Status","Provider","Carrier","Tracking","Reconcile","Events","Updated"].map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{data.items.map(item=><tr key={item.id} className="border-b-2 border-black align-top"><td className="p-3"><Link href={"/admin/shipping/"+item.id} className="font-black underline break-all">{item.shipmentReference}</Link><p className="text-xs break-all">{item.id}</p></td><td className="p-3 font-black">{item.orderNumber}<p className="text-xs font-normal">{item.orderId}</p></td><td className="p-3"><p className="font-bold">{item.customer.displayName||"Unnamed"}</p><p className="text-xs break-all">{item.customer.email}</p></td><td className="p-3 font-black">{item.status}</td><td className="p-3">{item.providerId}{item.providerReference&&<p className="break-all text-xs">{item.providerReference}</p>}</td><td className="p-3">{item.carrier||"—"}</td><td className="p-3">{item.trackingNumber||"Restricted"}</td><td className="p-3">{item.reconciliationRequired?<strong>REQUIRED</strong>:"Clear"}</td><td className="p-3">{item.trackingEventCount}</td><td className="p-3 text-sm">{new Date(item.updatedAt).toLocaleString("en-IN")}</td></tr>)}</tbody></table>{!data.items.length&&<p className="p-6 font-bold">No Shipments matched the current filters.</p>}</div>
  <footer className="flex flex-wrap justify-between gap-3 font-bold"><span>Page {data.pagination.page} / {data.pagination.totalPages} · {data.pagination.total} Shipments</span><span className="flex gap-2">{query.page>1&&<Link className="border-2 border-black px-3 py-2" href={"/admin/shipping?page="+(query.page-1)}>Previous</Link>}{data.pagination.hasNextPage&&<Link className="border-2 border-black bg-[#f7d51d] px-3 py-2" href={"/admin/shipping?page="+(query.page+1)}>Next</Link>}</span></footer>
 </section>;
}
