import {NextResponse} from "next/server";import {requireAdmin} from "@/lib/admin/authorization";import {approveChange,assessImpact,authorizeRelease,certifyChange,certifyRehearsal,createChangeRequest,createPlan,detail,evaluateAndRecordPolicy,invalidateCertifications,listChanges,requestRehearsal,startRelease,transitionChange,validateRelease,rollbackChange} from "@/lib/change-governance/service";
export const dynamic="force-dynamic";const s=(v:unknown)=>typeof v==="string"?v.trim():"";
export async function GET(req:Request){try{const u=new URL(req.url),a=s(u.searchParams.get("action"))||"list";await requireAdmin(req,"change_governance.read");if(a==="list")return NextResponse.json(await listChanges(Number(u.searchParams.get("limit")||50)));if(a==="detail")return NextResponse.json(await detail(s(u.searchParams.get("id"))));return NextResponse.json({error:"Unknown change query"},{status:400});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Change query failed safely"},{status:400});}}
export async function POST(req:Request){try{const b=await req.json() as Record<string,unknown>,a=s(b.action);
if(a==="CREATE"){const c=await requireAdmin(req,"change_governance.create");return NextResponse.json({result:await createChangeRequest({stableId:s(b.stableId),title:s(b.title),purpose:s(b.purpose),rationale:s(b.rationale),scope:b.scope,targets:Array.isArray(b.targets)?b.targets.filter((x):x is string=>typeof x==="string"):[],category:s(b.category),urgency:s(b.urgency),environment:s(b.environment),requestedWindow:s(b.requestedWindow)||undefined,requesterId:c.adminUser.id,ownerId:s(b.ownerId)||c.adminUser.id,businessImpact:b.businessImpact,customerImpact:b.customerImpact,technicalImpact:b.technicalImpact,rollbackStrategy:s(b.rollbackStrategy),validationStrategy:s(b.validationStrategy),requiredApprovals:b.requiredApprovals,correlationId:s(b.correlationId)||undefined})},{status:201});}
if(a==="IMPACT"){const c=await requireAdmin(req,"change_governance.impact");return NextResponse.json({result:await assessImpact(s(b.id),c.adminUser.id)});}
if(a==="POLICY"){const c=await requireAdmin(req,"change_governance.policy");return NextResponse.json({result:await evaluateAndRecordPolicy(s(b.id),c.adminUser.id)});}
if(a==="PLAN"){const c=await requireAdmin(req,"change_governance.plan");return NextResponse.json({result:await createPlan(s(b.id),c.adminUser.id)});}
if(a==="TRANSITION"){const c=await requireAdmin(req,"change_governance.approve");return NextResponse.json({result:await transitionChange(s(b.id),s(b.to),c.adminUser.id)});}
if(a==="APPROVE"){const c=await requireAdmin(req,"change_governance.approve");return NextResponse.json({result:await approveChange(s(b.id),c.adminUser.id,Number(b.expectedRevision))});}
if(a==="REHEARSAL"){const c=await requireAdmin(req,"change_governance.rehearsal");return NextResponse.json({result:await requestRehearsal(s(b.id),c.adminUser.id)});}
if(a==="CERTIFY_REHEARSAL"){const c=await requireAdmin(req,"change_governance.rehearsal");return NextResponse.json({result:await certifyRehearsal(s(b.id),c.adminUser.id)});}
if(a==="AUTHORIZE_RELEASE"){const c=await requireAdmin(req,"change_governance.release");return NextResponse.json({result:await authorizeRelease(s(b.id),c.adminUser.id)});}
if(a==="START_RELEASE"){const c=await requireAdmin(req,"change_governance.release");return NextResponse.json({result:await startRelease(s(b.id),c.adminUser.id)});}
if(a==="VALIDATE"){const c=await requireAdmin(req,"change_governance.validate");return NextResponse.json({result:await validateRelease(s(b.id),c.adminUser.id,b.result==="PASS"?"PASS":"FAIL",b.checks)});}
if(a==="ROLLBACK"){const c=await requireAdmin(req,"change_governance.rollback");return NextResponse.json({result:await rollbackChange(s(b.id),c.adminUser.id,{deterministic:b.deterministic===true,validated:b.validated===true,dataLoss:b.dataLoss===true,financialMutation:b.financialMutation===true,duplicateProviderAction:b.duplicateProviderAction===true,bounded:b.bounded===true,policyAllows:b.policyAllows===true,evidence:b.evidence===true,reason:s(b.reason)})});}
if(a==="CERTIFY"){const c=await requireAdmin(req,"change_governance.certify");return NextResponse.json({result:await certifyChange(s(b.id),c.adminUser.id)});}
if(a==="INVALIDATE"){await requireAdmin(req,"change_governance.certify");return NextResponse.json({result:await invalidateCertifications(s(b.reason)||"Material dependency or environment change.")});}
return NextResponse.json({error:"Unknown change action"},{status:400});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Change operation failed safely"},{status:400});}}