import Link from "next/link";
import { requireAdmin } from "@/lib/admin/authorization";
import { listAdminFulfillments, parseAdminFulfillmentQuery } from "@/lib/admin/fulfillment";
import { AdminFulfillmentCreate } from "@/components/admin/fulfillment-action";

function pageHref(url: URL, page: number) { const params = new URLSearchParams(url.searchParams); params.set("page", String(page)); return "/admin/fulfillments?" + params.toString(); }

export default async function AdminFulfillmentsPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const context=await requireAdmin(undefined,"fulfillment.read");const raw=await searchParams;const url=new URL("https://admin.local/admin/fulfillments");
 for(const [k,v] of Object.entries(raw)){if(Array.isArray(v))v.forEach(x=>url.searchParams.append(k,x));else if(v!==undefined)url.searchParams.set(k,v);}
 const query=parseAdminFulfillmentQuery(url);const data=await listAdminFulfillments(query,context);
 return <section className="space-y-6">
  <header className="border-4 border-black bg-[#f7d51d] p-6 shadow-[8px_8px_0_0_#000]"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.2em]">Operations control plane</p><h2 className="mt-2 text-4xl font-black uppercase">Fulfillment</h2><p className="mt-2 max-w-3xl">Canonical Fulfillment visibility and controlled provider operations. Payment, Order and Shipping domains remain authoritative for their own state.</p></div>{context.permissions.has("fulfillment.create")&&<AdminFulfillmentCreate/>}</div></header>
  <form method="get" className="border-4 border-black bg-white p-4 shadow-[6px_6px_0_0_#000]"><div className="grid gap-3 md:grid-cols-4">
   <label className="md:col-span-2"><span className="text-xs font-black uppercase">Search</span><input name="search" defaultValue={query.search||""} placeholder="Fulfillment, order, customer" className="mt-1 w-full border-2 border-black p-2"/></label>
   <label><span className="text-xs font-black uppercase">Status</span><select name="status" defaultValue={query.status||""} className="mt-1 w-full border-2 border-black p-2"><option value="">All</option>{["PENDING","SUBMITTED","FAILED","COMPLETED"].map(x=><option key={x}>{x}</option>)}</select></label>
   <label><span className="text-xs font-black uppercase">Provider</span><input name="provider" defaultValue={query.provider||""} className="mt-1 w-full border-2 border-black p-2"/></label>
   <label><span className="text-xs font-black uppercase">Shipment</span><select name="shipmentStatus" defaultValue={query.shipmentStatus||""} className="mt-1 w-full border-2 border-black p-2"><option value="">Any</option>{["CREATED","IN_TRANSIT","OUT_FOR_DELIVERY","DELIVERED","DELIVERY_FAILED","RETURNED"].map(x=><option key={x}>{x}</option>)}</select></label>
   <label><span className="text-xs font-black uppercase">Failure only</span><select name="failureOnly" defaultValue={query.failureOnly===undefined?"":String(query.failureOnly)} className="mt-1 w-full border-2 border-black p-2"><option value="">Any</option><option value="true">Failures</option><option value="false">Non-failures</option></select></label>
   <label><span className="text-xs font-black uppercase">Sort</span><select name="sort" defaultValue={query.sort} className="mt-1 w-full border-2 border-black p-2">{["createdAt","updatedAt","requestedAt","status","provider"].map(x=><option key={x}>{x}</option>)}</select></label>
   <label><span className="text-xs font-black uppercase">Direction</span><select name="direction" defaultValue={query.direction} className="mt-1 w-full border-2 border-black p-2"><option value="desc">Descending</option><option value="asc">Ascending</option></select></label>
   <label><span className="text-xs font-black uppercase">From</span><input type="date" name="from" defaultValue={query.from?.toISOString().slice(0,10)||""} className="mt-1 w-full border-2 border-black p-2"/></label><label><span className="text-xs font-black uppercase">To</span><input type="date" name="to" defaultValue={query.to?.toISOString().slice(0,10)||""} className="mt-1 w-full border-2 border-black p-2"/></label>
  </div><div className="mt-3 flex gap-2"><button className="border-2 border-black bg-black px-4 py-2 font-black uppercase text-white">Apply filters</button><Link href="/admin/fulfillments" className="border-2 border-black px-4 py-2 font-black uppercase">Reset</Link></div></form>
  <div className="overflow-x-auto border-4 border-black bg-white"><table className="w-full min-w-[1150px] border-collapse"><caption className="sr-only">Administrative fulfillment list</caption><thead><tr className="border-b-4 border-black bg-black text-left text-xs font-black uppercase text-white">{["Fulfillment","Order","Customer","Status","Provider","Shipment","Failure","Updated"].map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{data.items.map(item=><tr key={item.id} className="border-b-2 border-black align-top"><td className="p-3"><Link href={"/admin/fulfillments/"+item.id} className="font-black underline break-all">{item.id}</Link></td><td className="p-3 font-black">{item.orderNumber}<p className="text-xs font-normal">{item.orderId}</p></td><td className="p-3"><p className="font-bold">{item.customer.displayName||"Unnamed"}</p><p className="text-xs break-all">{item.customer.email}</p></td><td className="p-3 font-black">{item.status}</td><td className="p-3">{item.provider}{item.providerReference&&<p className="break-all text-xs">{item.providerReference}</p>}</td><td className="p-3">{item.shipmentStatus||"—"}</td><td className="p-3">{item.failure.code?<><strong>{item.failure.code}</strong><p className="text-xs">{item.failure.reconciliationRequired?"Reconciliation required":"Failure recorded"}</p></>:"—"}</td><td className="p-3 text-sm">{new Date(item.updatedAt).toLocaleString("en-IN")}</td></tr>)}</tbody></table>{!data.items.length&&<p className="p-6 font-bold">No fulfillments matched the current filters.</p>}</div>
  <footer className="flex flex-wrap items-center justify-between gap-3 font-bold"><span>Page {data.page} / {data.totalPages} · {data.total} fulfillments</span><span className="flex gap-2">{query.page>1&&<Link className="border-2 border-black px-3 py-2" href={pageHref(url,query.page-1)}>Previous</Link>}{data.page<data.totalPages&&<Link className="border-2 border-black bg-[#f7d51d] px-3 py-2" href={pageHref(url,query.page+1)}>Next</Link>}</span></footer>
 </section>;
}
