import { NextResponse } from "next/server";
import { requireAdmin, requireHighRiskReason } from "@/lib/admin/authorization";
import { createOpportunity,addEvidence,propose,moveOpportunity,approve,validateProposal,recordOutcome,certify,overview } from "@/lib/improvement/service";
export const dynamic="force-dynamic";
const body=async(r:Request)=>await r.json() as Record<string,unknown>;const s=(x:unknown)=>typeof x==="string"?x.trim():"";const obj=(x:unknown)=>x&&typeof x==="object"&&!Array.isArray(x)?x as Record<string,unknown>:{};
export async function GET(req:Request){try{await requireAdmin(req,"improvement.read");return NextResponse.json(await overview(),{headers:{"cache-control":"private,no-store"}})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Forbidden"},{status:403})}}
export async function POST(req:Request){try{const b=await body(req);const a=s(b.action);
 if(a==="CREATE_OPPORTUNITY"){const c=await requireAdmin(req,"improvement.create");return NextResponse.json({result:await createOpportunity({stableId:s(b.stableId),title:s(b.title),problem:s(b.problem),sourceType:s(b.sourceType),sourceId:s(b.sourceId),domain:s(b.domain),severity:s(b.severity),confidence:s(b.confidence)||"UNKNOWN",riskClass:s(b.riskClass)||"OBSERVE_ONLY",customerImpact:s(b.customerImpact)||"NO_IMPACT",owner:c.adminUser.id,evidence:b.evidence,hypothesis:b.hypothesis,factors:obj(b.factors)})},{status:201})}
 if(a==="ADD_EVIDENCE"){const c=await requireAdmin(req,"improvement.evidence.write");return NextResponse.json({result:await addEvidence({opportunityId:s(b.opportunityId),sourceType:s(b.sourceType),sourceId:s(b.sourceId),environment:s(b.environment)||"unknown",domain:s(b.domain),severity:s(b.severity),observedBehavior:s(b.observedBehavior),expectedBehavior:s(b.expectedBehavior),impact:b.impact,metrics:b.metrics,references:b.references})},{status:201})}
 if(a==="PROPOSE"){const c=await requireAdmin(req,"improvement.propose");return NextResponse.json({result:await propose({opportunityId:s(b.opportunityId),owner:c.adminUser.id,problem:s(b.problem),hypothesis:s(b.hypothesis),proposedChange:b.proposedChange,affectedComponents:b.affectedComponents,affectedDomains:b.affectedDomains,riskClass:s(b.riskClass)||"OBSERVE_ONLY",expectedBenefit:b.expectedBenefit,expectedFailureModes:b.expectedFailureModes,rollbackStrategy:b.rollbackStrategy,validationPlan:b.validationPlan,monitoringPlan:b.monitoringPlan,acceptanceCriteria:b.acceptanceCriteria,customerImpact:b.customerImpact,dependencyAssessment:b.dependencyAssessment,databaseAssessment:b.databaseAssessment,governanceRefs:b.governanceRefs,featureFlagRefs:b.featureFlagRefs,digitalTwinRefs:b.digitalTwinRefs,resilienceRefs:b.resilienceRefs,releaseRefs:b.releaseRefs,costAssessment:b.costAssessment,reviewers:b.reviewers})},{status:201})}
 if(a==="TRANSITION"){const c=await requireAdmin(req,"improvement.transition");return NextResponse.json({result:await moveOpportunity(s(b.id),s(b.from),s(b.to),c.adminUser.id,requireHighRiskReason(b.reason))})}
 if(a==="APPROVE"){const c=await requireAdmin(req,"improvement.approve");return NextResponse.json({result:await approve({proposalId:s(b.proposalId),approver:c.adminUser.id,role:(c.adminUser.roles[0]??"ADMIN"),decision:s(b.decision),rationale:requireHighRiskReason(b.rationale),policyVersion:s(b.policyVersion)||"15.30-v1",evidenceVersion:s(b.evidenceVersion)||"15.30-v1",separationRequired:b.separationRequired!==false,owner:s(b.owner)})})}
 if(a==="VALIDATE"){await requireAdmin(req,"improvement.validate");return NextResponse.json({result:await validateProposal({proposalId:s(b.proposalId),tests:b.tests,evidence:b.evidence,blockers:Array.isArray(b.blockers)?b.blockers.map(String):[],rollbackVerified:b.rollbackVerified===true,observabilityAvailable:b.observabilityAvailable===true,customerImpact:b.customerImpact,governanceSatisfied:b.governanceSatisfied===true,digitalTwinVerified:b.digitalTwinVerified===true,resilienceVerified:b.resilienceVerified===true})})}
 if(a==="OUTCOME"){await requireAdmin(req,"improvement.outcome");return NextResponse.json({result:await recordOutcome({proposalId:s(b.proposalId),expectedBenefit:b.expectedBenefit,actualBenefit:b.actualBenefit,regression:b.regression,operationalImpact:b.operationalImpact,customerImpact:b.customerImpact,costImpact:b.costImpact,reliabilityImpact:b.reliabilityImpact,sloImpact:b.sloImpact,errorBudgetImpact:b.errorBudgetImpact,numeric:{expectedBenefit:Number(b.expectedBenefitScore??0),actualBenefit:Number(b.actualBenefitScore??0),regression:Number(b.regressionScore??0)},rolledBack:b.rolledBack===true})})}
 if(a==="CERTIFY"){const c=await requireAdmin(req,"improvement.certify");return NextResponse.json({result:await certify({proposalId:s(b.proposalId),owner:c.adminUser.id,ciStatus:s(b.ciStatus)||"GREEN",testsPassed:b.testsPassed===true,securityStatus:s(b.securityStatus)||"PASS",dataIntegrityStatus:s(b.dataIntegrityStatus)||"PASS",operationalStatus:s(b.operationalStatus)||"PASS",governanceStatus:s(b.governanceStatus)||"PASS",documentationStatus:s(b.documentationStatus)||"PASS",rollbackReadiness:b.rollbackReadiness,knownLimitations:b.knownLimitations,unresolvedRisks:b.unresolvedRisks,digitalTwinVerified:b.digitalTwinVerified===true,resilienceVerified:b.resilienceVerified===true,continuousLifecycleOperational:b.continuousLifecycleOperational===true})})}
 return NextResponse.json({error:"Unknown improvement action"},{status:400})
}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Improvement operation failed safely"},{status:400})}}