import Link from "next/link";
import { requireAdmin } from "@/lib/admin/authorization";
import { listReconciliationCases, reconciliationSummary } from "@/lib/reconciliation/service";
import ReconciliationActions from "@/components/admin/reconciliation-actions";

export default async function AdminReconciliationPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const context=await requireAdmin(undefined,"reconciliation.read"); const raw=await searchParams;
 const status=typeof raw.status==="string"?raw.status:undefined, domain=typeof raw.domain==="string"?raw.domain:undefined, severity=typeof raw.severity==="string"?raw.severity:undefined;
 const [summary,cases]=await Promise.all([reconciliationSummary(),listReconciliationCases({status:status as never,domain:domain as never,severity:severity as never,limit:200})]);
 return <section className="space-y-6">
  <header className="border-4 border-black bg-[#f7d51d] p-6 shadow-[8px_8px_0_0_#000]"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[0.2em]">Integrity control plane</p><h2 className="mt-2 text-4xl font-black uppercase">Reconciliation</h2><p className="mt-2 max-w-3xl">Cross-domain discrepancy detection with explicit authority, bounded repairs and audited manual resolution. Financial and customer truth is never guessed.</p></div>{context.permissions.has("reconciliation.export")&&<Link href="/api/admin/reconciliation?export=1" className="border-2 border-black bg-white px-4 py-2 font-black uppercase">Export</Link>}</div></header>
  <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6">{[["Total",summary.total],["Detected",summary.detected],["Review",summary.awaitingReview],["Critical",summary.critical],["High",summary.high],["Resolved",summary.resolved]].map(([label,value])=><article key={String(label)} className="border-4 border-black bg-white p-4"><p className="text-xs font-black uppercase">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></article>)}</div>
  <form method="get" className="border-4 border-black bg-white p-4"><div className="grid gap-3 md:grid-cols-4"><label><span className="text-xs font-black uppercase">Status</span><select name="status" defaultValue={status||""} className="mt-1 w-full border-2 border-black p-2"><option value="">All</option>{["DETECTED","INVESTIGATING","AUTO_RESOLVABLE","AWAITING_REVIEW","RECONCILING","RESOLVED","FAILED","ESCALATED","IGNORED","NOT_REPRODUCIBLE"].map(x=><option key={x}>{x}</option>)}</select></label><label><span className="text-xs font-black uppercase">Domain</span><select name="domain" defaultValue={domain||""} className="mt-1 w-full border-2 border-black p-2"><option value="">All</option>{["CATALOG","PAYMENT","ORDER","FULFILLMENT","SHIPPING","CUSTOMER","ANALYTICS","NOTIFICATIONS","PROVIDERS"].map(x=><option key={x}>{x}</option>)}</select></label><label><span className="text-xs font-black uppercase">Severity</span><select name="severity" defaultValue={severity||""} className="mt-1 w-full border-2 border-black p-2"><option value="">All</option>{["CRITICAL","HIGH","MEDIUM","LOW"].map(x=><option key={x}>{x}</option>)}</select></label><button className="self-end border-2 border-black bg-black px-4 py-2 font-black uppercase text-white">Apply</button></div></form>
  <div className="overflow-x-auto border-4 border-black bg-white"><table className="w-full min-w-[1200px] border-collapse"><thead><tr className="border-b-4 border-black bg-black text-left text-xs font-black uppercase text-white">{["Severity","Domain","Discrepancy","Entity","Authority","Status","Evidence","Actions"].map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{cases.map(item=><tr key={item.id} className="border-b-2 border-black align-top"><td className="p-3 font-black">{item.severity}</td><td className="p-3">{item.domain}</td><td className="p-3"><strong>{item.type}</strong><p className="mt-1 max-w-sm text-xs">{item.description}</p></td><td className="p-3"><p className="font-bold">{item.affectedEntityType}</p><p className="break-all text-xs">{item.affectedEntityId}</p></td><td className="p-3 font-bold">{item.authoritativeDomain}</td><td className="p-3 font-black">{item.status}</td><td className="p-3 text-xs">{item.evidence?JSON.stringify(item.evidence):"—"}</td><td className="p-3"><ReconciliationActions id={item.id} version={item.version} canExecute={context.permissions.has("reconciliation.execute")} canResolve={context.permissions.has("reconciliation.resolve")} highRisk={["CRITICAL","PAYMENT","ORDER","CUSTOMER","FULFILLMENT"].some(x=>x===item.severity||x===item.domain)}/></td></tr>)}</tbody></table>{!cases.length&&<p className="p-6 font-bold">No reconciliation cases matched the filters.</p>}</div>
 </section>;
}