export const OPERATIONAL_HEALTH_STATES = ["HEALTHY","DEGRADED","FAILING","BLOCKED","MAINTENANCE","UNKNOWN","UNAVAILABLE"] as const;
export type OperationalHealthState = typeof OPERATIONAL_HEALTH_STATES[number];
export type ServiceDefinition = Readonly<{id:string;name:string;domain:string;owner:string;criticality:"CRITICAL"|"HIGH"|"MEDIUM"|"LOW";runtime:string;dependencies:string[];upstream:string[];downstream:string[];healthMechanism:string;readinessMechanism:string;failureMode:string;recoveryProcedure:string;escalationPath:string;maintenanceRequirements:string;operationalStatus:OperationalHealthState}>;
export const SERVICE_INVENTORY: readonly ServiceDefinition[]=[
{id:"storefront",name:"Storefront",domain:"commerce",owner:"commerce-operations",criticality:"CRITICAL",runtime:"Next.js",dependencies:["application","database","search"],upstream:[],downstream:["cart","checkout"],healthMechanism:"/api/health",readinessMechanism:"/api/readiness",failureMode:"customer-facing request failure",recoveryProcedure:"storefront/deployment runbook",escalationPath:"commerce operations",maintenanceRequirements:"approved deployment window",operationalStatus:"UNKNOWN"},
{id:"application",name:"Application runtime",domain:"platform",owner:"platform",criticality:"CRITICAL",runtime:"Next.js/Netlify",dependencies:["database"],upstream:["storefront","api"],downstream:["commerce workflows"],healthMechanism:"/api/health",readinessMechanism:"/api/readiness",failureMode:"runtime unavailable",recoveryProcedure:"deployment rollback/recovery",escalationPath:"platform",maintenanceRequirements:"deployment window",operationalStatus:"UNKNOWN"},
{id:"api",name:"API layer",domain:"platform",owner:"platform",criticality:"CRITICAL",runtime:"Next.js Route Handlers",dependencies:["application","database"],upstream:["storefront","admin"],downstream:["commerce workflows"],healthMechanism:"health/readiness plus synthetics",readinessMechanism:"workflow synthetics",failureMode:"API errors/timeouts",recoveryProcedure:"application recovery",escalationPath:"platform",maintenanceRequirements:"approved deployment window",operationalStatus:"UNKNOWN"},
{id:"database",name:"Database",domain:"persistence",owner:"platform",criticality:"CRITICAL",runtime:"PostgreSQL",dependencies:[],upstream:["application"],downstream:["commerce","admin","operations"],healthMechanism:"SELECT 1",readinessMechanism:"database readiness",failureMode:"persistence unavailable",recoveryProcedure:"database/recovery runbook",escalationPath:"platform",maintenanceRequirements:"database maintenance window",operationalStatus:"UNKNOWN"},
{id:"cache",name:"Cache",domain:"platform",owner:"platform",criticality:"MEDIUM",runtime:"application cache where configured",dependencies:[],upstream:["application"],downstream:["storefront","search"],healthMechanism:"existing telemetry",readinessMechanism:"existing runtime checks",failureMode:"cache unavailable/stale",recoveryProcedure:"safe fallback/invalidation",escalationPath:"platform",maintenanceRequirements:"bounded invalidation",operationalStatus:"UNKNOWN"},
{id:"search",name:"Search/discovery",domain:"discovery",owner:"search-operations",criticality:"HIGH",runtime:"provider-neutral search",dependencies:["database"],upstream:["catalog"],downstream:["storefront"],healthMechanism:"search synthetics",readinessMechanism:"synthetic workflow",failureMode:"search failure/stale results",recoveryProcedure:"search runbook",escalationPath:"search operations",maintenanceRequirements:"indexing maintenance",operationalStatus:"UNKNOWN"},
{id:"storage",name:"Storage/media",domain:"platform",owner:"platform",criticality:"MEDIUM",runtime:"application/provider storage",dependencies:[],upstream:["catalog","content"],downstream:["storefront"],healthMechanism:"media/content checks",readinessMechanism:"content checks",failureMode:"media unavailable",recoveryProcedure:"storage runbook",escalationPath:"platform",maintenanceRequirements:"provider maintenance window",operationalStatus:"UNKNOWN"},
{id:"queues",name:"Queues/background jobs",domain:"operations",owner:"platform",criticality:"HIGH",runtime:"Netlify scheduled/background functions",dependencies:["database"],upstream:["commerce","notifications","reconciliation"],downstream:["notifications","search","reconciliation"],healthMechanism:"job/synthetic telemetry",readinessMechanism:"job execution evidence",failureMode:"backlog/stuck jobs",recoveryProcedure:"background-job runbook",escalationPath:"platform operations",maintenanceRequirements:"bounded pause/recovery",operationalStatus:"UNKNOWN"},
{id:"payment-provider",name:"Payment provider",domain:"payments",owner:"payments-operations",criticality:"CRITICAL",runtime:"PayU adapter",dependencies:["application"],upstream:["checkout"],downstream:["payment","order"],healthMechanism:"payment boundary telemetry",readinessMechanism:"non-financial validation",failureMode:"payment processing/callback failure",recoveryProcedure:"payment outage runbook",escalationPath:"payments operations",maintenanceRequirements:"provider window",operationalStatus:"UNKNOWN"},
{id:"notifications",name:"Notification provider",domain:"communications",owner:"communications-operations",criticality:"HIGH",runtime:"notification service/provider",dependencies:["database"],upstream:["orders","customers"],downstream:["customer communications"],healthMechanism:"delivery telemetry",readinessMechanism:"isolated synthetic notifications",failureMode:"delivery/retry backlog",recoveryProcedure:"notification runbook",escalationPath:"communications operations",maintenanceRequirements:"synthetic traffic isolated",operationalStatus:"UNKNOWN"},
{id:"analytics",name:"Analytics pipeline",domain:"analytics",owner:"analytics",criticality:"MEDIUM",runtime:"first-party analytics",dependencies:["database"],upstream:["storefront","commerce"],downstream:[],healthMechanism:"event pipeline telemetry",readinessMechanism:"analytics synthetic exclusion",failureMode:"ingestion/schema/consent failure",recoveryProcedure:"analytics runbook",escalationPath:"analytics",maintenanceRequirements:"synthetic traffic excluded",operationalStatus:"UNKNOWN"},
{id:"fulfillment",name:"Provider-neutral fulfillment",domain:"fulfillment",owner:"fulfillment-operations",criticality:"HIGH",runtime:"fulfillment adapter",dependencies:["database","qikink"],upstream:["order"],downstream:["shipping"],healthMechanism:"reliability checks",readinessMechanism:"synthetic/provider boundary",failureMode:"handoff ambiguity/stuck state",recoveryProcedure:"fulfillment runbook",escalationPath:"fulfillment operations",maintenanceRequirements:"idempotency/reconciliation required",operationalStatus:"UNKNOWN"},
{id:"qikink",name:"Qikink fulfillment adapter",domain:"fulfillment-provider",owner:"fulfillment-operations",criticality:"HIGH",runtime:"server-side provider adapter",dependencies:[],upstream:["fulfillment"],downstream:["fulfillment"],healthMechanism:"adapter capability declaration",readinessMechanism:"provider-safe boundary",failureMode:"provider unavailable/unsupported capability",recoveryProcedure:"Qikink runbook",escalationPath:"fulfillment operations",maintenanceRequirements:"no catalog/shipping bypass",operationalStatus:"UNKNOWN"},
{id:"shipping",name:"Shipping",domain:"shipping",owner:"shipping-operations",criticality:"HIGH",runtime:"provider-neutral shipping",dependencies:["database"],upstream:["fulfillment"],downstream:["tracking"],healthMechanism:"shipping reconciliation",readinessMechanism:"tracking contract evidence",failureMode:"shipment creation/reconciliation failure",recoveryProcedure:"shipping runbook",escalationPath:"shipping operations",maintenanceRequirements:"provider contract required",operationalStatus:"UNKNOWN"},
{id:"tracking",name:"Tracking",domain:"shipping",owner:"shipping-operations",criticality:"HIGH",runtime:"tracking boundary",dependencies:["shipping"],upstream:["shipping"],downstream:["customer"],healthMechanism:"tracking/reconciliation",readinessMechanism:"verified status lookup",failureMode:"tracking unavailable",recoveryProcedure:"tracking runbook",escalationPath:"shipping operations",maintenanceRequirements:"provider status contract",operationalStatus:"UNKNOWN"},
{id:"authentication",name:"Authentication",domain:"identity",owner:"security-operations",criticality:"CRITICAL",runtime:"customer/admin auth",dependencies:["database"],upstream:["storefront","admin"],downstream:["customer","admin"],healthMechanism:"auth synthetics/governance",readinessMechanism:"auth schema checks",failureMode:"login/session failure",recoveryProcedure:"authentication runbook",escalationPath:"security operations",maintenanceRequirements:"security controls remain active",operationalStatus:"UNKNOWN"},
{id:"observability",name:"Observability",domain:"platform",owner:"platform",criticality:"CRITICAL",runtime:"existing telemetry stack",dependencies:[],upstream:["all services"],downstream:["incidents"],healthMechanism:"telemetry self-checks",readinessMechanism:"CI/runtime evidence",failureMode:"operational blind spot",recoveryProcedure:"observability runbook",escalationPath:"platform",maintenanceRequirements:"never disable as workaround",operationalStatus:"UNKNOWN"},
{id:"deployment",name:"Deployment infrastructure",domain:"release-engineering",owner:"release-engineering",criticality:"CRITICAL",runtime:"Netlify + GitHub Actions",dependencies:["application"],upstream:["release"],downstream:["application"],healthMechanism:"deployment evidence",readinessMechanism:"post-deployment verification",failureMode:"failed/partial deployment",recoveryProcedure:"deployment rollback runbook",escalationPath:"release engineering",maintenanceRequirements:"approved release window",operationalStatus:"UNKNOWN"}
];
export const DEPENDENCY_GRAPH=SERVICE_INVENTORY.flatMap(service=>service.dependencies.map(dependency=>({component:service.id,dependency,health:"UNKNOWN" as OperationalHealthState,impact:"A failure in "+dependency+" can affect "+service.name+"."})));
export const RUNBOOKS=[
["RB-DB-001","Database outage","DATABASE","SAFE"],["RB-PAY-001","Payment outage","PAYMENT_PROVIDER","REQUIRES_AUTHORIZATION"],["RB-QIK-001","Qikink outage","QIKINK","REQUIRES_AUTHORIZATION"],["RB-FUL-001","Fulfillment failure","FULFILLMENT","REQUIRES_AUTHORIZATION"],["RB-SHP-001","Shipping failure","SHIPPING","REQUIRES_AUTHORIZATION"],["RB-TRK-001","Tracking failure","TRACKING","SAFE"],["RB-QUEUE-001","Queue failure","QUEUES","SAFE"],["RB-NOT-001","Notification failure","NOTIFICATIONS","SAFE"],["RB-SEA-001","Search failure","SEARCH","SAFE"],["RB-DEP-001","Deployment failure","DEPLOYMENT","REQUIRES_AUTHORIZATION"],["RB-MIG-001","Migration failure","DATABASE","REQUIRES_AUTHORIZATION"],["RB-AUTH-001","Authentication failure","AUTHENTICATION","REQUIRES_AUTHORIZATION"],["RB-ERR-001","Elevated error rate","APPLICATION","SAFE"],["RB-LAT-001","Latency degradation","APPLICATION","SAFE"],["RB-REC-001","Reconciliation discrepancy","RECONCILIATION","REQUIRES_AUTHORIZATION"],["RB-BKP-001","Backup failure","BACKUP","REQUIRES_AUTHORIZATION"]
] as const;
export function combineHealth(states:readonly OperationalHealthState[]):OperationalHealthState{if(states.includes("UNAVAILABLE"))return"UNAVAILABLE";if(states.includes("FAILING"))return"FAILING";if(states.includes("BLOCKED"))return"BLOCKED";if(states.includes("DEGRADED"))return"DEGRADED";if(!states.length||states.includes("UNKNOWN"))return"UNKNOWN";if(states.every(s=>s==="MAINTENANCE"))return"MAINTENANCE";return"HEALTHY";}
export function propagateDependencyHealth(component:string,edges:readonly {component:string;dependency:string;health:OperationalHealthState}[]):OperationalHealthState{const relevant=edges.filter(edge=>edge.component===component);if(!relevant.length)return"HEALTHY";return combineHealth(relevant.map(edge=>edge.health));}