import { NextResponse } from "next/server";
import { requireAdmin,requireHighRiskReason } from "@/lib/admin/authorization";
import { overview,createEvolution,addEvidence,assessEvolution,proposeEvolution,recordDecision,recordMigration,recordValidation,certify,addDrift,transitionEvolution } from "@/lib/architecture/service";
export const dynamic="force-dynamic";
const s=(x:unknown)=>typeof x==="string"?x.trim():"";
export async function GET(req:Request){try{await requireAdmin(req,"architecture.read");return NextResponse.json(await overview(),{headers:{"cache-control":"private,no-store"}})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Forbidden"},{status:403})}}
export async function POST(req:Request){try{const b=await req.json() as Record<string,unknown>;const a=s(b.action);
 if(a==="CREATE"){const c=await requireAdmin(req,"architecture.create");return NextResponse.json({result:await createEvolution({stableId:s(b.stableId),title:s(b.title),description:s(b.description),problem:s(b.problem),category:s(b.category),owner:c.adminUser.id,affectedDomains:b.affectedDomains,affectedComponents:b.affectedComponents,risk:s(b.risk),blastRadius:s(b.blastRadius)||"MINIMAL",expectedBenefit:b.expectedBenefit,expectedCost:b.expectedCost,migrationStrategy:s(b.migrationStrategy)||"IN_PLACE",rollbackStrategy:b.rollbackStrategy,validationPlan:b.validationPlan,successCriteria:b.successCriteria,evidence:b.evidence})},{status:201})}
 if(a==="EVIDENCE"){await requireAdmin(req,"architecture.evidence.write");return NextResponse.json({result:await addEvidence({evolutionId:s(b.evolutionId),sourceType:s(b.sourceType),sourceId:s(b.sourceId),environment:s(b.environment)||"unknown",observedAt:s(b.observedAt)||new Date().toISOString(),summary:s(b.summary),references:b.references,metrics:b.metrics,integrityHash:s(b.integrityHash)||undefined})},{status:201})}
 if(a==="ASSESS"){const c=await requireAdmin(req,"architecture.assess");return NextResponse.json({result:await assessEvolution({evolutionId:s(b.evolutionId),assessment:b.assessment,assessor:c.adminUser.id,result:s(b.result)||"REFINE",successCriteriaCount:Number(b.successCriteriaCount||0),evidenceCount:Number(b.evidenceCount||0)})},{status:201})}
 if(a==="PROPOSE"){const c=await requireAdmin(req,"architecture.propose");return NextResponse.json({result:await proposeEvolution({evolutionId:s(b.evolutionId),version:Number(b.version||1),options:b.options,decisionCriteria:b.decisionCriteria,selectedOption:s(b.selectedOption)||undefined,proposal:b.proposal,owner:c.adminUser.id})},{status:201})}
 if(a==="DECIDE"){const c=await requireAdmin(req,"architecture.approve");return NextResponse.json({result:await recordDecision({evolutionId:s(b.evolutionId),proposalId:s(b.proposalId),decision:s(b.decision),rationale:requireHighRiskReason(b.rationale),approver:c.adminUser.id,version:Number(b.version||1),risks:b.risks,tradeoffs:b.tradeoffs,rejectedAlternatives:b.rejectedAlternatives,approval:b.approval===true})},{status:201})}
 if(a==="MIGRATE"){const c=await requireAdmin(req,"architecture.migrate");return NextResponse.json({result:await recordMigration({evolutionId:s(b.evolutionId),strategy:s(b.strategy),owner:c.adminUser.id,plan:b.plan,rollback:b.rollback,forwardRecovery:b.forwardRecovery,compatibility:b.compatibility,status:s(b.status)||"PLANNED"})},{status:201})}
 if(a==="VALIDATE"){await requireAdmin(req,"architecture.validate");return NextResponse.json({result:await recordValidation({evolutionId:s(b.evolutionId),migrationId:s(b.migrationId)||undefined,status:s(b.status)||"PASSED",tests:b.tests,evidence:b.evidence,rollbackVerified:b.rollbackVerified===true,observabilityVerified:b.observabilityVerified===true,securityVerified:b.securityVerified===true,privacyVerified:b.privacyVerified===true,reconciliationVerified:b.reconciliationVerified===true,digitalTwinVerified:b.digitalTwinVerified===true,resilienceVerified:b.resilienceVerified===true})},{status:201})}
 if(a==="DRIFT"){const c=await requireAdmin(req,"architecture.drift.write");return NextResponse.json({result:await addDrift({evolutionId:s(b.evolutionId)||undefined,kind:s(b.kind),scope:s(b.scope),details:b.details,owner:c.adminUser.id})},{status:201})}
 if(a==="TRANSITION"){const c=await requireAdmin(req,"architecture.transition");return NextResponse.json({result:await transitionEvolution(s(b.evolutionId),s(b.from),s(b.to),c.adminUser.id,requireHighRiskReason(b.reason))})}
 if(a==="CERTIFY"){const c=await requireAdmin(req,"architecture.certify");return NextResponse.json({result:await certify({evolutionId:s(b.evolutionId),owner:c.adminUser.id,ciStatus:s(b.ciStatus)||"GREEN",testsPassed:b.testsPassed===true,securityStatus:s(b.securityStatus)||"PASS",privacyStatus:s(b.privacyStatus)||"PASS",dataIntegrityStatus:s(b.dataIntegrityStatus)||"PASS",observabilityStatus:s(b.observabilityStatus)||"PASS",rollbackReady:b.rollbackReady===true,documentationComplete:b.documentationComplete===true,digitalTwinVerified:b.digitalTwinVerified===true,resilienceVerified:b.resilienceVerified===true,reconciliationVerified:b.reconciliationVerified===true})},{status:201})}
 return NextResponse.json({error:"Unknown architecture action"},{status:400});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Architecture operation failed safely"},{status:400})}}