import { requireAdmin } from "@/lib/admin/authorization";
import { listPipelines } from "@/lib/delivery-orchestration/service";
export const dynamic="force-dynamic";
export default async function DeliveryOrchestrationPage(){
 const auth=await requireAdmin(undefined,"delivery.read");const rows=await listPipelines();
 const active=rows.filter(r=>!["COMPLETED","ABORTED","FAILED","INVALIDATED","EXPIRED","SUPERSEDED"].includes(r.status)).length;
 return <main className="min-h-screen bg-[#f2f0e6] p-6 text-black"><section className="mx-auto max-w-7xl space-y-6">
  <header className="border-4 border-black bg-white p-6"><p className="text-xs font-black uppercase">4HRS+ / Delivery orchestration</p><h1 className="mt-2 text-4xl font-black uppercase">Multi-stage release coordination</h1><p className="mt-2 max-w-4xl text-sm">Authoritative Change → Release → Deployment coordination with deterministic gates, registered operations, incident controls and evidence lineage.</p></header>
  <section className="grid gap-4 md:grid-cols-4"><div className="border-2 border-black bg-white p-4"><b className="text-xs uppercase">Pipelines</b><p className="text-3xl font-black">{rows.length}</p></div><div className="border-2 border-black bg-white p-4"><b className="text-xs uppercase">Active</b><p className="text-3xl font-black">{active}</p></div><div className="border-2 border-black bg-white p-4"><b className="text-xs uppercase">Certified claim</b><p className="text-3xl font-black">0</p></div><div className="border-2 border-black bg-white p-4"><b className="text-xs uppercase">Arbitrary execution</b><p className="text-3xl font-black">0</p></div></section>
  <section className="border-4 border-black bg-white"><div className="border-b-4 border-black p-4"><h2 className="font-black uppercase">Pipeline runs</h2></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead><tr className="border-b-2 border-black"><th className="p-3">Pipeline</th><th className="p-3">Environment</th><th className="p-3">Status</th><th className="p-3">Stage</th><th className="p-3">Gates</th><th className="p-3">Runs</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b-2 border-black"><td className="p-3 font-black">{r.stableId}</td><td className="p-3">{r.environment}</td><td className="p-3">{r.status}</td><td className="p-3">{r.stages.find(s=>s.status==="RUNNING")?.name??r.stages.find(s=>s.status==="PENDING")?.name??"—"}</td><td className="p-3">{r.gates.filter(g=>g.result==="PASS").length}/{r.gates.length}</td><td className="p-3">{r.runs.length}</td></tr>)}</tbody></table></div></section>
  <p className="text-xs">Authorized roles: {auth.adminUser.roles.length}. Browser input is untrusted; orchestration uses only registered typed operations and preserves existing provider/RBAC boundaries.</p>
 </section></main>;
}
