import Link from "next/link";
import { notFound } from "next/navigation";
import { requireAdmin } from "@/lib/admin/authorization";
import { AdminError } from "@/lib/admin/errors";
import { getAdminShipment } from "@/lib/admin/shipping";
import { AdminShipmentAction } from "@/components/admin/shipment-action";

export default async function AdminShipmentDetailPage({params}:{params:Promise<{shipmentId:string}>}){
 const context=await requireAdmin(undefined,"shipping.read");let shipment;
 try{shipment=await getAdminShipment((await params).shipmentId,context);}catch(error){if(error instanceof AdminError&&error.code==="NOT_FOUND")notFound();throw error;}
 const endpoint="/api/admin/shipping/"+shipment.id;
 const canReconcile=context.permissions.has("shipping.reconcile");
 const canRecovery=context.permissions.has("shipping.recovery");
 return <section className="space-y-6">
  <header className="border-4 border-black bg-[#f7d51d] p-6 shadow-[8px_8px_0_0_#000]"><Link href="/admin/shipping" className="font-black underline">← Shipping</Link><p className="mt-4 text-xs font-black uppercase tracking-[0.2em]">{shipment.status}</p><h2 className="mt-1 break-all text-4xl font-black uppercase">{shipment.shipmentReference}</h2><p className="mt-2 text-sm">Order {shipment.orderNumber} · Provider {shipment.provider.id}</p><div className="mt-4 flex flex-wrap gap-2">{canReconcile&&<AdminShipmentAction endpoint={endpoint} action="reconcile">Reconcile Shipment</AdminShipmentAction>}{canRecovery&&shipment.reconciliation.required&&<AdminShipmentAction endpoint={endpoint} action="recovery">Request Recovery</AdminShipmentAction>}</div></header>
  <div className="grid gap-6 xl:grid-cols-2">
   <section className="border-4 border-black bg-white p-5 shadow-[6px_6px_0_0_#000]"><h3 className="text-xl font-black uppercase">Shipment state</h3><dl className="mt-4 grid gap-3 sm:grid-cols-2"><div><dt className="text-xs font-black uppercase">Status</dt><dd className="font-black">{shipment.status}</dd></div><div><dt className="text-xs font-black uppercase">Provider</dt><dd>{shipment.provider.id}</dd></div><div><dt className="text-xs font-black uppercase">Carrier</dt><dd>{shipment.provider.carrier||"—"}</dd></div><div><dt className="text-xs font-black uppercase">Service</dt><dd>{shipment.provider.service||"—"}</dd></div><div><dt className="text-xs font-black uppercase">Tracking number</dt><dd className="break-all">{shipment.provider.trackingNumber||"Restricted / unavailable"}</dd></div><div><dt className="text-xs font-black uppercase">Tracking URL</dt><dd className="break-all">{shipment.provider.trackingUrl||"Restricted / unavailable"}</dd></div><div><dt className="text-xs font-black uppercase">Provider reference</dt><dd className="break-all">{shipment.provider.reference||"Restricted / unavailable"}</dd></div><div><dt className="text-xs font-black uppercase">Created</dt><dd>{new Date(shipment.createdAt).toLocaleString("en-IN")}</dd></div></dl>{shipment.reconciliation.required&&<div role="alert" className="mt-5 border-2 border-black bg-[#ff5c35] p-3"><p className="font-black uppercase">Reconciliation required</p><p className="mt-1 text-sm">{shipment.reconciliation.reason||"Operational review required."}</p></div>}</section>
   <section className="border-4 border-black bg-white p-5 shadow-[6px_6px_0_0_#000]"><h3 className="text-xl font-black uppercase">Order & customer</h3><p className="mt-3 font-black"><Link className="underline" href={"/admin/orders/"+shipment.orderNumber}>{shipment.orderNumber}</Link></p><div className="mt-4 border-2 border-black p-3"><p className="font-black">{shipment.customer.displayName||"Unnamed customer"}</p><p>{shipment.customer.email}</p><p className="mt-1 break-all text-xs">Customer ID: {shipment.customer.id}</p></div><div className="mt-4 border-2 border-black p-3"><p className="text-xs font-black uppercase">Fulfillment</p><p className="mt-1 font-black">{shipment.fulfillment.status}</p><p className="text-sm">{shipment.fulfillment.provider} · {shipment.fulfillment.providerReference||"Provider reference restricted"}</p></div></section>
  </div>
  <section className="border-4 border-black bg-white p-5 shadow-[6px_6px_0_0_#000]"><h3 className="text-xl font-black uppercase">Tracking timeline</h3><p className="mt-1 text-sm">Tracking events are immutable domain records; Admin does not fabricate or edit them.</p><ol className="mt-5 grid gap-3">{shipment.trackingEvents.map((event)=><li key={event.id} className="border-2 border-black p-4"><div className="flex flex-wrap justify-between gap-2"><strong>{event.normalizedStatus}</strong><time dateTime={event.eventTimestamp}>{new Date(event.eventTimestamp).toLocaleString("en-IN")}</time></div><p className="mt-1 text-sm">{event.description||"No description recorded."}</p><p className="mt-1 text-xs uppercase">Provider {event.providerId} · Source {event.source}{event.location?" · "+event.location:""}</p></li>)}{!shipment.trackingEvents.length&&<li className="border-2 border-black p-4 font-bold">No tracking events have been ingested.</li>}</ol></section>
  <div className="grid gap-6 xl:grid-cols-2">
   <section className="border-4 border-black bg-white p-5 shadow-[6px_6px_0_0_#000]"><h3 className="text-xl font-black uppercase">Shipping address</h3>{shipment.address?<dl className="mt-4 grid gap-2 text-sm"><div><dt className="font-black">Recipient</dt><dd>{shipment.address.recipientName}</dd></div><div><dt className="font-black">Address</dt><dd>{shipment.address.addressLine1}{shipment.address.addressLine2?", "+shipment.address.addressLine2:""}<br/>{shipment.address.city}, {shipment.address.stateOrProvince} {shipment.address.postalCode}<br/>{shipment.address.countryCode}</dd></div><div><dt className="font-black">Phone</dt><dd>{shipment.address.phone||"—"}</dd></div></dl>:<p className="mt-4 font-bold">Shipping address unavailable or restricted.</p>}</section>
   <section className="border-4 border-black bg-white p-5 shadow-[6px_6px_0_0_#000]"><h3 className="text-xl font-black uppercase">Return Shipments</h3><p className="mt-1 text-sm">Return Shipments remain owned by the Returns domain and are not treated as outbound Shipment state.</p><div className="mt-4 grid gap-2">{shipment.returnShipments.map(r=><article key={r.reference} className="border-2 border-black p-3"><p className="font-black">{r.reference} · {r.status}</p><p className="text-sm">{r.carrier||"Carrier unavailable"} · {r.trackingNumber||"Tracking restricted"}</p></article>)}{!shipment.returnShipments.length&&<p>No Return Shipment is linked.</p>}</div></section>
  </div>
  {context.permissions.has("shipping.audit.read")&&<section className="border-4 border-black bg-white p-5 shadow-[6px_6px_0_0_#000]"><h3 className="text-xl font-black uppercase">Admin audit</h3><div className="mt-4 grid gap-2">{shipment.audit.map((a,i)=><p key={a.createdAt+"-"+i} className="border-2 border-black p-2 text-sm">{new Date(a.createdAt).toLocaleString("en-IN")} · <strong>{a.action}</strong> · {a.success?"success":"failure"}{a.reason?" · "+a.reason:""}</p>)}</div></section>}
 </section>;
}
