"use client";
import { useState } from "react";
import type { ExceptionSummary } from "@/lib/returns/contracts";
import type { PublicOrderDto } from "@/lib/orders/contracts";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

export function OrderExceptionActions({order,summary}:{order:PublicOrderDto;summary:ExceptionSummary}){
 const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false); const [reason,setReason]=useState("CHANGED_MIND"); const [description,setDescription]=useState(""); const [quantities,setQuantities]=useState<Record<string,number>>(()=>Object.fromEntries(order.items.map(i=>[i.itemReference,0])));
 async function post(path:string,body:unknown){setBusy(true);setMessage("");try{const r=await fetch(path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error?.message??"Request failed.");setMessage("Request submitted successfully.");}catch(e){setMessage(e instanceof Error?e.message:"Request failed.");}finally{setBusy(false);}}
 const returnItems=order.items.map(i=>({orderItemReference:i.itemReference,quantity:quantities[i.itemReference]??0})).filter(i=>i.quantity>0);
 return <section className="grid gap-6" aria-labelledby="order-exceptions-heading">
   <div><h2 id="order-exceptions-heading" className="text-2xl uppercase">Order actions</h2><p className="mt-2 text-sm leading-6">Cancellation and return actions are enabled only when the server says this order is eligible.</p></div>
   {summary.cancellation==="eligible"||summary.cancellation==="requires_review" ? <Card className="p-5"><h3 className="text-xl font-900 uppercase">Cancellation</h3><p className="mt-2 text-sm">The request will be evaluated against the current Order, Fulfillment and Shipment state.</p><label className="mt-4 grid gap-2 text-sm font-700">Reason<input className="border-2 border-border bg-background p-3" value={description} onChange={e=>setDescription(e.target.value)} placeholder="Why do you want to cancel?" maxLength={2000}/></label><Button className="mt-4" variant="outline" disabled={busy} onClick={()=>void post(`/api/order/${order.orderNumber}/cancel`,{reason:"CUSTOMER_REQUEST",description})}>Request cancellation</Button></Card>:null}
   {summary.return==="eligible" ? <Card className="p-5"><h3 className="text-xl font-900 uppercase">Return items</h3><div className="mt-4 grid gap-3">{order.items.map(item=><label key={item.itemReference} className="flex flex-wrap items-center justify-between gap-3 border-2 border-border p-3 text-sm"><span><strong>{item.productTitle}</strong><br/>Purchased quantity: {item.quantity}</span><input className="w-24 border-2 border-border bg-background p-2" type="number" min="0" max={item.quantity} value={quantities[item.itemReference]??0} onChange={e=>setQuantities(q=>({...q,[item.itemReference]:Math.max(0,Math.min(item.quantity,Number(e.target.value)||0))}))} aria-label={`Return quantity for ${item.productTitle}`}/></label>)}</div><label className="mt-4 grid gap-2 text-sm font-700">Reason<select className="border-2 border-border bg-background p-3" value={reason} onChange={e=>setReason(e.target.value)}><option value="WRONG_ITEM">Wrong item</option><option value="DAMAGED">Damaged</option><option value="DEFECTIVE">Defective</option><option value="SIZE_OR_FIT">Size or fit</option><option value="NOT_AS_EXPECTED">Not as expected</option><option value="CHANGED_MIND">Changed mind</option><option value="OTHER">Other</option></select></label><label className="mt-4 grid gap-2 text-sm font-700">Description<textarea className="border-2 border-border bg-background p-3" value={description} onChange={e=>setDescription(e.target.value)} maxLength={2000}/></label><Button className="mt-4" variant="yellow" disabled={busy||returnItems.length===0} onClick={()=>void post(`/api/order/${order.orderNumber}/return`,{items:returnItems,reasonCode:reason,description})}>Request return</Button></Card>:null}
   {message?<p role="status" className="border-2 border-border p-4 text-sm font-700">{message}</p>:null}
 </section>;
}
