import { createHash } from "node:crypto";
import { db } from "@/lib/db/client";

export const ARCH_LIFECYCLE = { IDENTIFIED:"ASSESSED", ASSESSED:"PROPOSED", PROPOSED:"ARCHITECTURE_REVIEW", ARCHITECTURE_REVIEW:"APPROVED", APPROVED:"REHEARSAL", REHEARSAL:"MIGRATING", MIGRATING:"VALIDATING", VALIDATING:"CERTIFIED" } as const;
export const ARCH_TERMINAL = new Set(["REJECTED","DEFERRED","ROLLED_BACK","ABANDONED","CERTIFIED"]);
export const PROBLEM_CATEGORIES = ["DOMAIN_BOUNDARY","API_BOUNDARY","DATA_MODEL","DATABASE","PERFORMANCE","SCALABILITY","RELIABILITY","SECURITY","PRIVACY","OBSERVABILITY","DEPENDENCY","INFRASTRUCTURE","DEPLOYMENT","TESTING","DEVELOPER_EXPERIENCE","OPERATIONAL_TOIL","COST","TECHNICAL_DEBT","DOCUMENTATION"] as const;
export const MIGRATION_STRATEGIES = ["IN_PLACE","EXPAND_CONTRACT","STRANGLER","DUAL_READ","DUAL_WRITE","SHADOW","FEATURE_FLAG","BLUE_GREEN","CANARY","PHASED_ROLLOUT"] as const;
export const BLAST_RADIUS = ["MINIMAL","LOW","MEDIUM","HIGH","CRITICAL"] as const;
type R=Record<string,unknown>;
const redact=(v:unknown):unknown=>{const walk=(x:unknown,d=0):unknown=>{if(d>6)return "[TRUNCATED]";if(x===null||typeof x==="string"||typeof x==="number"||typeof x==="boolean")return x;if(Array.isArray(x))return x.slice(0,100).map(y=>walk(y,d+1));if(typeof x==="object"){const o:R={};for(const[k,y]of Object.entries(x)){if(/password|secret|token|authorization|cookie|apiKey|privateKey|cardNumber|cvv/i.test(k))o[k]="[REDACTED]";else o[k]=walk(y,d+1)}return o}return String(x)};return walk(v)};
const hash=(v:unknown)=>createHash("sha256").update(JSON.stringify(v)).digest("hex");

export function transitionAllowed(from:string,to:string){if(ARCH_TERMINAL.has(from))return false;if(["REJECTED","DEFERRED","ABANDONED","ROLLED_BACK"].includes(to))return true;return ARCH_LIFECYCLE[from as keyof typeof ARCH_LIFECYCLE]===to;}
export function validateProblemCategory(category:string){if(!PROBLEM_CATEGORIES.includes(category as never))throw new Error("Unknown architectural problem category.");}
export function validateMigrationStrategy(strategy:string){if(!MIGRATION_STRATEGIES.includes(strategy as never))throw new Error("Unknown migration strategy.");if(strategy==="DUAL_WRITE")throw new Error("Dual-write requires explicit consistency and reconciliation governance before approval.");}
export function validateBlastRadius(value:string){if(!BLAST_RADIUS.includes(value as never))throw new Error("Unknown blast-radius class.");}
export function assessModernization(input:{evidenceCount:number;successCriteriaCount:number;affectedDomains:number;blastRadius:string;reversible:boolean;securitySensitive:boolean;privacySensitive:boolean;customerImpact:number}){validateBlastRadius(input.blastRadius);if(input.evidenceCount<1)throw new Error("Evidence is required before architectural assessment.");if(input.successCriteriaCount<1)throw new Error("Measurable success criteria are required.");const score=input.evidenceCount*2+input.successCriteriaCount*2+Number(input.reversible)*2-input.affectedDomains-input.customerImpact-(input.blastRadius==="CRITICAL"?6:input.blastRadius==="HIGH"?3:0)-(input.securitySensitive?2:0)-(input.privacySensitive?2:0);return {methodology:"15.31-v1",score,decision:score>=6?"PROCEED_TO_PROPOSAL":"REQUIRES_REFINEMENT"};}
export function validateAutomationPolicy(action:string){const blocked=["DESTRUCTIVE_DATABASE","PAYMENT_MUTATION","ORDER_MUTATION","CUSTOMER_DATA_DELETION","PROVIDER_CREDENTIAL_CHANGE","SECURITY_POLICY_WEAKENING","PRODUCTION_ARCHITECTURE_REWRITE"];if(blocked.includes(action))throw new Error("Architecture automation policy blocks this operation.");return true;}
export function detectDrift(kind:string,details:R){const normalized=redact(details);return {kind,classification:"GOVERNED_FINDING",evidence:normalized,integrityHash:hash(normalized),methodologyVersion:"15.31-v1"};}

export async function createEvolution(input:{stableId:string;title:string;description:string;problem:string;category:string;owner:string;affectedDomains:unknown;affectedComponents:unknown;risk:string;blastRadius:string;expectedBenefit:unknown;expectedCost:unknown;migrationStrategy:string;rollbackStrategy:unknown;validationPlan:unknown;successCriteria:unknown;evidence:unknown}){validateProblemCategory(input.category);validateMigrationStrategy(input.migrationStrategy);validateBlastRadius(input.blastRadius);if(!input.problem.trim())throw new Error("A concrete originating problem is required.");const existing=await db.architectureEvolution.findUnique({where:{stableId:input.stableId}});if(existing)return existing;return db.architectureEvolution.create({data:{stableId:input.stableId,title:input.title,description:input.description,originatingProblem:input.problem,category:input.category,owner:input.owner,affectedDomains:redact(input.affectedDomains) as never,affectedComponents:redact(input.affectedComponents) as never,risk:input.risk,blastRadius:input.blastRadius,expectedBenefit:redact(input.expectedBenefit) as never,expectedCost:redact(input.expectedCost) as never,migrationStrategy:input.migrationStrategy,rollbackStrategy:redact(input.rollbackStrategy) as never,validationPlan:redact(input.validationPlan) as never,successCriteria:redact(input.successCriteria) as never,evidence:redact(input.evidence) as never,lifecycle:"IDENTIFIED"}});}
export async function addEvidence(input:{evolutionId:string;sourceType:string;sourceId:string;environment:string;observedAt:string;summary:string;references:unknown;metrics:unknown;integrityHash?:string}){const payload=redact({sourceType:input.sourceType,sourceId:input.sourceId,environment:input.environment,observedAt:input.observedAt,summary:input.summary,references:input.references,metrics:input.metrics});return db.architectureEvidence.create({data:{evolutionId:input.evolutionId,sourceType:input.sourceType,sourceId:input.sourceId,environment:input.environment,observedAt:new Date(input.observedAt),summary:input.summary,references:redact(input.references) as never,metrics:redact(input.metrics) as never,integrityHash:input.integrityHash||hash(payload),redactionVersion:"15.31-v1"}});}
export async function assessEvolution(input:{evolutionId:string;assessment:unknown;assessor:string;result:string;successCriteriaCount:number;evidenceCount:number}){if(input.evidenceCount<1||input.successCriteriaCount<1)throw new Error("Assessment requires evidence and measurable success criteria.");return db.architectureAssessment.create({data:{evolutionId:input.evolutionId,assessor:input.assessor,result:input.result,assessment:redact(input.assessment) as never,methodologyVersion:"15.31-v1"}});}
export async function proposeEvolution(input:{evolutionId:string;version:number;options:unknown;decisionCriteria:unknown;selectedOption?:string;proposal:unknown;owner:string}){const evolution=await db.architectureEvolution.findUnique({where:{id:input.evolutionId}});if(!evolution)throw new Error("Evolution item not found.");if(evolution.lifecycle!=="PROPOSED"&&evolution.lifecycle!=="ASSESSED")throw new Error("Evolution must be assessed before proposal.");return db.architectureProposal.create({data:{evolutionId:input.evolutionId,version:input.version,options:redact(input.options) as never,decisionCriteria:redact(input.decisionCriteria) as never,selectedOption:input.selectedOption||null,proposal:redact(input.proposal) as never,owner:input.owner,status:"PROPOSED"}});}
export async function recordDecision(input:{evolutionId:string;proposalId:string;decision:string;rationale:string;approver:string;version:number;risks:unknown;tradeoffs:unknown;rejectedAlternatives:unknown;approval:boolean}){if(!["APPROVE","REJECT","SUPERSEDE"].includes(input.decision))throw new Error("Invalid architecture decision.");return db.architectureDecision.create({data:{evolutionId:input.evolutionId,proposalId:input.proposalId,decision:input.decision,rationale:input.rationale,approver:input.approver,decisionVersion:input.version,risks:redact(input.risks) as never,tradeoffs:redact(input.tradeoffs) as never,rejectedAlternatives:redact(input.rejectedAlternatives) as never,approval:input.approval}});}
export async function recordMigration(input:{evolutionId:string;strategy:string;owner:string;plan:unknown;rollback:unknown;forwardRecovery:unknown;compatibility:unknown;status:string}){validateMigrationStrategy(input.strategy);if(!input.plan||!input.rollback||!input.forwardRecovery)throw new Error("Migration, rollback, and forward-recovery plans are required.");return db.architectureMigration.create({data:{evolutionId:input.evolutionId,strategy:input.strategy,owner:input.owner,plan:redact(input.plan) as never,rollback:redact(input.rollback) as never,forwardRecovery:redact(input.forwardRecovery) as never,compatibility:redact(input.compatibility) as never,status:input.status}});}
export async function recordValidation(input:{evolutionId:string;migrationId?:string;status:string;tests:unknown;evidence:unknown;rollbackVerified:boolean;observabilityVerified:boolean;securityVerified:boolean;privacyVerified:boolean;reconciliationVerified:boolean;digitalTwinVerified:boolean;resilienceVerified:boolean}){const blockers=[!input.rollbackVerified?"rollback":"",!input.observabilityVerified?"observability":"",!input.securityVerified?"security":"",!input.privacyVerified?"privacy":"",!input.reconciliationVerified?"reconciliation":"",!input.digitalTwinVerified?"digital-twin":"",!input.resilienceVerified?"resilience":""].filter(Boolean);return db.architectureValidation.create({data:{evolutionId:input.evolutionId,migrationId:input.migrationId||null,status:blockers.length?"PASSED_WITH_LIMITATIONS":input.status,tests:redact(input.tests) as never,evidence:redact({evidence:input.evidence,blockers}) as never,rollbackVerified:input.rollbackVerified,observabilityVerified:input.observabilityVerified,securityVerified:input.securityVerified,privacyVerified:input.privacyVerified,reconciliationVerified:input.reconciliationVerified,digitalTwinVerified:input.digitalTwinVerified,resilienceVerified:input.resilienceVerified}});}
export async function certify(input:{evolutionId:string;owner:string;ciStatus:string;testsPassed:boolean;securityStatus:string;privacyStatus:string;dataIntegrityStatus:string;observabilityStatus:string;rollbackReady:boolean;documentationComplete:boolean;digitalTwinVerified:boolean;resilienceVerified:boolean;reconciliationVerified:boolean}){const blockers=[input.ciStatus!=="GREEN"?"ci":"",!input.testsPassed?"tests":"",input.securityStatus==="CRITICAL"?"security":"",input.privacyStatus==="CRITICAL"?"privacy":"",input.dataIntegrityStatus==="CRITICAL"?"data-integrity":"",input.observabilityStatus==="CRITICAL"?"observability":"",!input.rollbackReady?"rollback":"",!input.documentationComplete?"documentation":"",!input.digitalTwinVerified?"digital-twin":"",!input.resilienceVerified?"resilience":"",!input.reconciliationVerified?"reconciliation":""].filter(Boolean);const status=blockers.length?"NOT_READY":"READY_WITH_DOCUMENTED_LIMITATIONS";return db.architectureCertification.create({data:{evolutionId:input.evolutionId,status,ciStatus:input.ciStatus,testStatus:input.testsPassed?"PASS":"FAIL",securityStatus:input.securityStatus,privacyStatus:input.privacyStatus,dataIntegrityStatus:input.dataIntegrityStatus,observabilityStatus:input.observabilityStatus,rollbackReady:input.rollbackReady,documentationComplete:input.documentationComplete,digitalTwinVerified:input.digitalTwinVerified,resilienceVerified:input.resilienceVerified,reconciliationVerified:input.reconciliationVerified,knownLimitations:redact({blockers}) as never,owner:input.owner}});}
export async function addDrift(input:{evolutionId?:string;kind:string;scope:string;details:unknown;owner:string}){const finding=detectDrift(input.kind,typeof input.details==="object"&&input.details!==null?input.details as R:{value:input.details});return db.architectureDriftFinding.create({data:{evolutionId:input.evolutionId||null,kind:input.kind,scope:input.scope,classification:finding.classification,evidence:finding.evidence as never,integrityHash:finding.integrityHash,methodologyVersion:finding.methodologyVersion,owner:input.owner,status:"OPEN"}});}
export async function transitionEvolution(id:string,from:string,to:string,actor:string,reason:string){if(!transitionAllowed(from,to))throw new Error(`Invalid architecture lifecycle transition: ${from} -> ${to}`);const updated=await db.architectureEvolution.updateMany({where:{id,lifecycle:from as never},data:{lifecycle:to as never}});if(updated.count!==1)throw new Error("Stale architecture lifecycle update rejected.");await db.architectureTransition.create({data:{evolutionId:id,fromState:from,toState:to,actor,reason}});return db.architectureEvolution.findUnique({where:{id}});}
export async function overview(){const [evolutions,assessments,proposals,decisions,migrations,validations,certifications,drift,roadmap]=await Promise.all([db.architectureEvolution.findMany({orderBy:{updatedAt:"desc"},take:100}),db.architectureAssessment.findMany({orderBy:{createdAt:"desc"},take:100}),db.architectureProposal.findMany({orderBy:{createdAt:"desc"},take:100}),db.architectureDecision.findMany({orderBy:{createdAt:"desc"},take:100}),db.architectureMigration.findMany({orderBy:{createdAt:"desc"},take:100}),db.architectureValidation.findMany({orderBy:{createdAt:"desc"},take:100}),db.architectureCertification.findMany({orderBy:{certifiedAt:"desc"},take:100}),db.architectureDriftFinding.findMany({orderBy:{createdAt:"desc"},take:100}),db.architectureRoadmapItem.findMany({orderBy:{updatedAt:"desc"},take:100})]);return {evolutions,assessments,proposals,decisions,migrations,validations,certifications,drift,roadmap};}