import Link from "next/link";
import { notFound } from "next/navigation";
import { requireAdmin } from "@/lib/admin/authorization";
import { AdminError } from "@/lib/admin/errors";
import { getAdminPayment } from "@/lib/admin/payments";
import { AdminPaymentAction } from "@/components/admin/payment-action";
export default async function AdminPaymentDetailPage({params}:{params:Promise<{paymentId:string}>}){
 const context=await requireAdmin(undefined,"payments.read");let payment;try{payment=await getAdminPayment((await params).paymentId,context.permissions.has("payments.view_sensitive"),context.permissions.has("payments.audit.read"));}catch(error){if(error instanceof AdminError&&error.code==="NOT_FOUND")notFound();throw error;}
 const endpoint="/api/admin/payments/"+payment.id+"/actions";const fullRefundable=payment.status==="SUCCEEDED"||payment.status==="PARTIALLY_REFUNDED";
 return <section className="space-y-6">
  <header className="border-4 border-black bg-[#f7d51d] p-6 shadow-[8px_8px_0_0_#000]"><Link href="/admin/payments" className="font-black underline">← Payments</Link><p className="mt-4 text-xs font-black uppercase tracking-[0.2em]">{payment.status}</p><h2 className="mt-1 break-all text-4xl font-black uppercase">{payment.reference}</h2><p className="mt-2 break-all text-sm">Payment ID: {payment.id}</p></header>
  <div className="grid gap-6 xl:grid-cols-2">
   <section className="border-4 border-black bg-white p-5 shadow-[6px_6px_0_0_#000]"><h3 className="text-xl font-black uppercase">Financial state</h3><dl className="mt-4 grid gap-3 sm:grid-cols-2"><div><dt className="text-xs font-black uppercase">Amount</dt><dd className="text-2xl font-black">{payment.currency} {payment.amount}</dd></div><div><dt className="text-xs font-black uppercase">State</dt><dd className="font-black">{payment.status}</dd></div><div><dt className="text-xs font-black uppercase">Provider</dt><dd>{payment.providerId||"—"}</dd></div><div><dt className="text-xs font-black uppercase">Provider reference</dt><dd className="break-all">{payment.providerReference||"Restricted"}</dd></div><div><dt className="text-xs font-black uppercase">Created</dt><dd>{new Date(payment.createdAt).toLocaleString("en-IN")}</dd></div><div><dt className="text-xs font-black uppercase">Completed</dt><dd>{payment.completedAt?new Date(payment.completedAt).toLocaleString("en-IN"):"—"}</dd></div></dl>
    <div className="mt-5 flex flex-wrap gap-2">{context.permissions.has("payments.verify")&&<AdminPaymentAction endpoint={endpoint} action="verify"/>}{context.permissions.has("payments.reconcile")&&<AdminPaymentAction endpoint={endpoint} action="reconcile"/>}{context.permissions.has("payments.retry")&&payment.status==="FAILED"&&<AdminPaymentAction endpoint={endpoint} action="retry"/>}{context.permissions.has("payments.refund")&&fullRefundable&&<AdminPaymentAction endpoint={endpoint} action="refund" currency={payment.currency} defaultAmount={payment.amount} canFullRefund/>}{context.permissions.has("payments.refund_partial")&&fullRefundable&&<AdminPaymentAction endpoint={endpoint} action="refund" currency={payment.currency} canPartialRefund/>}</div>
   </section>
   <section className="border-4 border-black bg-white p-5 shadow-[6px_6px_0_0_#000]"><h3 className="text-xl font-black uppercase">Order & customer</h3>{payment.order?<><p className="mt-3 font-black"><Link className="underline" href={"/admin/orders/"+payment.order.orderNumber}>{payment.order.orderNumber}</Link></p><p>{payment.order.currency} {payment.order.total}</p></>:<p className="mt-3">No order relationship.</p>}<div className="mt-4 border-2 border-black p-3"><p className="font-black">{payment.customer.displayName||"Unnamed customer"}</p><p>{payment.customer.email}</p><p className="mt-1 break-all text-xs">Customer ID: {payment.customer.id}</p></div></section>
  </div>
  <section className="border-4 border-black bg-white p-5 shadow-[6px_6px_0_0_#000]"><h3 className="text-xl font-black uppercase">Attempt history</h3><div className="mt-4 grid gap-2">{payment.attempts.map(a=><article key={a.id} className="border-2 border-black p-3"><p className="font-black">Attempt #{a.attemptNumber} · {a.status}</p><p className="text-sm">{a.amount} {a.currency} · Provider {a.providerId||"—"} · Ref {a.providerReference||"Restricted"}</p>{a.failureCode&&<p className="text-sm">Failure: {a.failureCode} {a.failureCategory?"· "+a.failureCategory:""}</p>}<p className="text-xs">{new Date(a.createdAt).toLocaleString("en-IN")}</p></article>)}</div></section>
  <section className="border-4 border-black bg-white p-5 shadow-[6px_6px_0_0_#000]"><h3 className="text-xl font-black uppercase">Refund history</h3><div className="mt-4 grid gap-2">{payment.refunds.map(r=><article key={r.id} className="border-2 border-black p-3"><p className="font-black">{r.status} · {r.currency} {r.amount} · {r.reason}</p><p className="text-sm">Provider: {r.providerId||"—"} · Ref: {r.providerReference||"Restricted"}</p>{r.note&&<p className="text-sm">Note: {r.note}</p>}{r.failureCode&&<p className="text-sm">Failure: {r.failureCode}</p>}<p className="text-xs">{new Date(r.createdAt).toLocaleString("en-IN")}</p></article>)}{!payment.refunds.length&&<p>No refund records exist.</p>}</div></section>
  <section className="border-4 border-black bg-white p-5 shadow-[6px_6px_0_0_#000]"><h3 className="text-xl font-black uppercase">Provider events</h3><div className="mt-4 grid gap-2">{payment.events.map(e=><article key={e.id} className="border-2 border-black p-3"><p className="font-black">{e.normalizedEventType||e.eventType}</p><p className="text-sm">{e.processingStatus} · Provider {e.providerId} · Event {e.providerEventId||"Restricted"}</p>{e.processingError&&<p className="text-sm">{e.processingError}</p>}</article>)}</div></section>
  {context.permissions.has("payments.audit.read")&&<section className="border-4 border-black bg-white p-5 shadow-[6px_6px_0_0_#000]"><h3 className="text-xl font-black uppercase">Admin audit</h3><div className="mt-4 grid gap-2">{payment.audit.map((e,i)=><p key={e.createdAt+"-"+i} className="border-2 border-black p-2 text-sm">{new Date(e.createdAt).toLocaleString("en-IN")} · <strong>{e.action}</strong> · {e.success?"success":"failure"}{e.reason?" · "+e.reason:""}</p>)}</div></section>}
 </section>;
}