import { requireAdmin } from "@/lib/admin/authorization";
import { getOverview } from "@/lib/rehearsal/service";
export const dynamic="force-dynamic";
export default async function RehearsalPage(){
 const context=await requireAdmin(undefined,"twin.read"); const d=await getOverview();
 const counts=d.executions.reduce<Record<string,number>>((a,e)=>{a[e.outcome]=(a[e.outcome]??0)+1;return a;},{});
 return <section className="space-y-8">
  <header className="border-4 border-black bg-white p-6 shadow-[8px_8px_0_0_#000]"><p className="text-sm font-black uppercase tracking-[0.2em]">Continuous verification</p><h1 className="mt-2 text-4xl font-black uppercase">Digital twin & rehearsal</h1><p className="mt-3 max-w-4xl text-sm">Provider-neutral, synthetic-data operational rehearsals. Production credentials, real payments, live provider mutations, arbitrary SQL/shell and unrestricted network destinations are hard-blocked.</p></header>
  <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-6">{["PASS","PARTIAL","FAIL","UNKNOWN","BLOCKED"].map(k=><div key={k} className="border-2 border-black bg-white p-4"><p className="text-xs font-black uppercase">{k}</p><p className="mt-1 text-2xl font-black">{counts[k]??0}</p></div>)}<div className="border-2 border-black bg-white p-4"><p className="text-xs font-black uppercase">Active</p><p className="mt-1 text-2xl font-black">{d.summary.activeRehearsals}</p></div></section>
  <section className="grid gap-4 lg:grid-cols-2"><div className="border-4 border-black bg-white p-5"><h2 className="font-black uppercase">Twin environments</h2><div className="mt-3 space-y-2 text-sm">{d.environments.map(e=><div key={e.id} className="border-2 border-black p-3"><div className="font-black">{e.name}</div><div>{e.environment} · {e.status} · config {e.configurationVersion}</div><div className="text-xs">Isolation proof: {Object.values(e.isolationProof as Record<string,unknown>).every(Boolean)?"PASS":"BLOCKED"}</div></div>)}</div></div>
  <div className="border-4 border-black bg-white p-5"><h2 className="font-black uppercase">Readiness signal</h2><dl className="mt-3 space-y-2 text-sm"><div className="flex justify-between border-b py-1"><dt>Last success</dt><dd className="font-black">{d.summary.lastSuccessfulRun?new Date(d.summary.lastSuccessfulRun).toISOString():"—"}</dd></div><div className="flex justify-between border-b py-1"><dt>Last failure</dt><dd className="font-black">{d.summary.lastFailedRun?new Date(d.summary.lastFailedRun).toISOString():"—"}</dd></div><div className="flex justify-between border-b py-1"><dt>Unresolved failures</dt><dd className="font-black">{d.summary.unresolvedFailures}</dd></div><div className="flex justify-between border-b py-1"><dt>Permissions</dt><dd className="font-black">{context.permissions.size}</dd></div></dl></div></section>
  <section className="border-4 border-black bg-white"><div className="border-b-4 border-black p-4"><h2 className="text-xl font-black uppercase">Scenario registry</h2></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead><tr className="border-b-2 border-black"><th className="p-3">Scenario</th><th className="p-3">Category</th><th className="p-3">Risk</th><th className="p-3">Limit</th><th className="p-3">Impact</th><th className="p-3">State</th></tr></thead><tbody>{d.scenarios.map(s=><tr key={s.id} className="border-b-2 border-black last:border-0"><td className="p-3 font-black">{s.name}</td><td className="p-3">{s.category}</td><td className="p-3">{s.riskClass}</td><td className="p-3">{s.maxDurationSeconds}s / {s.maxResourceUnits}u</td><td className="p-3">{JSON.stringify(s.customerImpact)}</td><td className="p-3 font-black">{s.lifecycleState}</td></tr>)}</tbody></table></div></section>
  <section className="border-4 border-black bg-white"><div className="border-b-4 border-black p-4"><h2 className="text-xl font-black uppercase">Recent rehearsals</h2></div><div className="divide-y-2 divide-black">{d.executions.slice(0,20).map(e=><div key={e.id} className="grid gap-2 p-4 md:grid-cols-5"><span className="font-black">{e.scenarioId}</span><span>{e.state}</span><span>{e.outcome}</span><span>{e.startedAt.toISOString()}</span><span>{e.recovery?JSON.stringify(e.recovery):"—"}</span></div>)}</div></section>
 </section>
}