"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
export default function CaseDetailActions({caseReference,status,canUpdate,canResolve}:{caseReference:string;status:string;canUpdate:boolean;canResolve:boolean}){
 const router=useRouter();const[note,setNote]=useState("");const[summary,setSummary]=useState("");const[resolution,setResolution]=useState("NO_ACTION_REQUIRED");const[busy,setBusy]=useState(false);const[error,setError]=useState("");
 async function post(path:string,body:unknown){setBusy(true);setError("");try{const r=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json","Idempotency-Key":crypto.randomUUID()+"case"},body:JSON.stringify(body)});const b=await r.json();if(!r.ok)throw new Error(b.error?.message??"Operation failed.");router.refresh();}catch(e){setError(e instanceof Error?e.message:"Operation failed.");}finally{setBusy(false);}}
 return <section className="mt-6 border-t-2 border-black pt-5"><h2 className="text-xl font-black uppercase">Operational actions</h2><div className="mt-4 grid gap-3 max-w-2xl">
  {canUpdate&&<button disabled={busy||status==="CLOSED"} onClick={()=>void post("/api/admin/cases/"+caseReference+"/transition",{to:"IN_PROGRESS",reason:"operator_work_started"})} className="border-2 border-black bg-black px-4 py-2 font-black uppercase text-white disabled:opacity-50">Start work</button>}
  {canUpdate&&<><label><span className="sr-only">Internal note</span><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Internal note" maxLength={4000} className="border-2 border-black bg-white p-2 w-full"/></label><button disabled={busy||!note.trim()} onClick={()=>void post("/api/admin/cases/"+caseReference+"/notes",{body:note})} className="border-2 border-black bg-white px-4 py-2 font-black uppercase disabled:opacity-50">Add internal note</button></>}
  {canResolve&&<><label><span className="sr-only">Resolution</span><select value={resolution} onChange={e=>setResolution(e.target.value)} className="border-2 border-black bg-white p-2 w-full">{["NO_ACTION_REQUIRED","INFORMATION_PROVIDED","RETURN_APPROVED","RETURN_REJECTED","ORDER_CANCELLED","SHIPMENT_RECONCILED","FULFILLMENT_RESOLVED","DUPLICATE","ESCALATED"].map(x=><option key={x}>{x}</option>)}</select></label><label><span className="sr-only">Resolution reason</span><textarea value={summary} onChange={e=>setSummary(e.target.value)} placeholder="Resolution reason" maxLength={1000} className="border-2 border-black bg-white p-2 w-full"/></label><button disabled={busy||!summary.trim()||status==="CLOSED"} onClick={()=>void post("/api/admin/cases/"+caseReference+"/resolve",{resolutionType:resolution,summary})} className="border-2 border-black bg-black px-4 py-2 font-black uppercase text-white disabled:opacity-50">Resolve case</button><button disabled={busy||status!=="RESOLVED"} onClick={()=>void post("/api/admin/cases/"+caseReference+"/close",{reason:"resolution_confirmed"})} className="border-2 border-black bg-white px-4 py-2 font-black uppercase disabled:opacity-50">Close case</button></>}
 </div>{error&&<p role="alert" className="mt-3 font-bold">{error}</p>}</section>;
}