"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
type Props={endpoint:string;action:"refund"|"reconcile"|"verify"|"retry";currency?:string;defaultAmount?:string;canFullRefund?:boolean;canPartialRefund?:boolean};
const reasons=[["CUSTOMER_REQUEST","Customer request"],["ORDER_CANCELLED","Order cancelled"],["RETURN_APPROVED","Return approved"],["DUPLICATE_PAYMENT","Duplicate payment"],["PAYMENT_ERROR","Payment error"],["OPERATIONAL_CORRECTION","Operational correction"],["OTHER","Other"]];
export function AdminPaymentAction({endpoint,action,currency="INR",defaultAmount="",canFullRefund=false,canPartialRefund=false}:Props){
 const router=useRouter();const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [reason,setReason]=useState("");const [refundReason,setRefundReason]=useState("CUSTOMER_REQUEST");const [amount,setAmount]=useState(defaultAmount);const [note,setNote]=useState("");
 async function run(){setBusy(true);setError("");const body:Record<string,string>={action,reason};if(action==="refund"){body.amount=amount;body.currency=currency;body.refundReason=refundReason;body.note=note;body.idempotencyKey=crypto.randomUUID().replaceAll("-","")}if(action==="retry")body.idempotencyKey=crypto.randomUUID().replaceAll("-","");const res=await fetch(endpoint,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await res.json().catch(()=>({}));if(!res.ok){setError(data?.error?.message||"The operation failed.");setBusy(false);return;}setOpen(false);setBusy(false);setReason("");setNote("");router.refresh();}
 const label=action==="refund"?"Refund":action==="reconcile"?"Reconcile":action==="verify"?"Verify":"Retry payment";
 if(action==="refund"&&!canFullRefund&&!canPartialRefund)return null;
 return <div className="space-y-2">{open?<div role="dialog" aria-modal="true" aria-labelledby={"payment-"+action+"-title"} className="border-4 border-black bg-white p-4 shadow-[6px_6px_0_0_#000]">
  <h4 id={"payment-"+action+"-title"} className="text-lg font-black uppercase">{label} confirmation</h4>
  {action==="refund"&&<><p className="mt-2 text-sm font-bold">Financial consequence: the exact amount below will be sent to the canonical Payment provider when a supported provider is configured.</p><label className="mt-3 block text-xs font-black uppercase">Refund amount<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} className="mt-1 w-full border-2 border-black p-2" aria-describedby="refund-amount-help"/></label><p id="refund-amount-help" className="mt-1 text-xs">Server-side validation recalculates the remaining refundable balance.</p><label className="mt-3 block text-xs font-black uppercase">Reason<select value={refundReason} onChange={e=>setRefundReason(e.target.value)} className="mt-1 w-full border-2 border-black p-2">{reasons.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="mt-3 block text-xs font-black uppercase">Operational note (optional)<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={1000} rows={3} className="mt-1 w-full border-2 border-black p-2"/></label></>}
  <label className="mt-3 block text-xs font-black uppercase">Confirmation reason<textarea value={reason} onChange={e=>setReason(e.target.value)} maxLength={1000} rows={3} className="mt-1 w-full border-2 border-black p-2" required/></label>
  <div className="mt-3 flex flex-wrap gap-2"><button type="button" disabled={busy||reason.trim().length<3||(action==="refund"&&!amount.trim())} onClick={run} className="border-2 border-black bg-[#ff5a36] px-3 py-2 font-black uppercase text-black">{busy?"Working…":"Confirm "+label}</button><button type="button" disabled={busy} onClick={()=>setOpen(false)} className="border-2 border-black bg-white px-3 py-2 font-black uppercase">Cancel</button></div>
 </div>:<button type="button" onClick={()=>setOpen(true)} className="border-2 border-black bg-[#f7d51d] px-3 py-2 font-black uppercase focus-visible:outline-4 focus-visible:outline-black">{label}</button>}{error&&<p role="alert" className="font-bold">{error}</p>}</div>;
}