import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join, relative } from "node:path";

type Status = "PASS" | "FAIL" | "BLOCKED" | "NOT APPLICABLE";
type Severity = "CRITICAL" | "HIGH" | "MEDIUM" | "LOW" | "INFORMATIONAL";
type Finding = { id:string; domain:string; status:Status; severity:Severity; evidence:string[]; risk:string; remediation:string };

const root = process.cwd();
const findings: Finding[] = [];
const read = (p:string) => existsSync(join(root,p)) ? readFileSync(join(root,p),"utf8") : "";
const exists = (p:string) => existsSync(join(root,p));

function files(dir:string,out:string[]=[]):string[] {
  const full=join(root,dir);
  if(!existsSync(full)) return out;
  for(const entry of readdirSync(full)){
    if(["node_modules",".next",".git"].includes(entry)) continue;
    const child=join(full,entry), rel=relative(root,child).replaceAll("\\","/");
    if(statSync(child).isDirectory()) files(rel,out); else out.push(rel);
  }
  return out;
}
const all=files(".").filter(f=>/\.(ts|tsx|js|jsx|prisma|json|md|yml|yaml)$/.test(f));
const runtime=all.filter(f=>/^(app|lib|components)\//.test(f)&&!/(^|\.)test\.(ts|tsx)$/.test(f));
const clients=all.filter(f=>/^(app|components)\//.test(f)&&read(f).includes('"use client"'));
const source=runtime.map(read).join("\n");
const schema=read("prisma/schema.prisma");
const ci=read(".github/workflows/ci.yml");

function add(id:string,domain:string,status:Status,severity:Severity,evidence:string[],risk:string,remediation:string){
  findings.push({id,domain,status,severity,evidence,risk,remediation});
}
function check(id:string,domain:string,ok:boolean,evidence:string[],risk:string,remediation:string,severity:Severity="HIGH"){
  add(id,domain,ok?"PASS":"FAIL",ok?"INFORMATIONAL":severity,evidence,risk,remediation);
}

check("16.6.01","Canonical identity",exists("lib/auth/service.ts")&&exists("lib/auth/session.ts")&&exists("lib/auth/context.ts")&&exists("lib/customer/repository.ts"),["auth service/session/context/customer repository"],"Multiple identity sources could diverge.","Keep one canonical customer identity/session path.");
check("16.6.02","Authentication",/hashPassword/.test(read("lib/auth/service.ts"))&&/verifyPassword/.test(read("lib/auth/service.ts"))&&/Authentication failed/.test(read("lib/auth/service.ts"))&&/status !== "ACTIVE"/.test(read("lib/auth/service.ts")),["credential hashing/verification, generic failures, status gate"],"Credential or account-state bypass could permit unauthorized access.","Preserve server-side credential and account-state checks.","CRITICAL");
check("16.6.03","Session security",/randomBytes\(32\)/.test(read("lib/auth/session.ts"))&&/sha256/.test(read("lib/auth/session.ts"))&&/httpOnly:\s*true/.test(read("lib/auth/session.ts"))&&/sameSite:\s*"lax"/.test(read("lib/auth/session.ts"))&&/expiresAt/.test(read("lib/auth/service.ts"))&&/revokedAt/.test(read("lib/auth/service.ts")),["random token, hashed persistence, HttpOnly/SameSite, expiry and revocation"],"Forged, replayed or stale sessions could survive security events.","Keep opaque hashed sessions with expiry and revocation.","CRITICAL");
check("16.6.04","Session invalidation",/revokeAllCustomerSessions/.test(read("lib/auth/service.ts"))&&/revokeAllCustomerSessions\(input\.customerId, input\.currentSessionId/.test(read("lib/auth/service.ts"))&&/customer\.status !== "ACTIVE"/.test(read("lib/auth/service.ts")),["password-change and account-status session boundaries"],"Security changes could leave old sessions usable.","Revoke affected sessions and reject non-active accounts.");
check("16.6.05","Registration abuse",/REGISTRATION_LIMIT/.test(read("lib/auth/service.ts"))&&/assertSameOrigin/.test(read("app/api/auth/register/route.ts"))&&/requireCredentials/.test(read("app/api/auth/register/route.ts")),["registration rate limit, same-origin, credential validation"],"Automated registration abuse could exhaust resources or enumerate accounts.","Retain registration throttling and generic identity errors.");
check("16.6.06","Login abuse",/LOGIN_LIMIT/.test(read("lib/auth/service.ts"))&&/RATE_LIMITED/.test(read("lib/auth/service.ts"))&&/Authentication failed/.test(read("lib/auth/service.ts")),["login throttling and generic authentication failure"],"Brute force or enumeration could compromise accounts.","Retain rate limiting and enumeration-resistant responses.");
check("16.6.07","Customer authorization",/requireCurrentCustomer/.test(source)&&/getOrderByNumberForCustomer\(identifier, customer\.id\)/.test(read("lib/orders/application.ts"))&&/listOrdersByCustomer\(customer\.id/.test(read("lib/orders/application.ts")),["server-derived customer identity and scoped order queries"],"IDOR could expose another customer's resources.","Derive ownership from authenticated identity on every customer resource.");
check("16.6.08","Profile mass assignment",/const keys = Object\.keys\(body\)/.test(read("app/api/customer/profile/route.ts"))&&/keys\.some\(\(key\) => key !== "displayName"\)/.test(read("app/api/customer/profile/route.ts"))&&/validateDisplayName\(body\.displayName\)/.test(read("app/api/customer/profile/route.ts"))&&!/body\.customerId|body\.role|body\.permissions/.test(read("app/api/customer/profile/route.ts")),["profile allow-list and server-owned identity"],"Mass assignment could alter privileged fields.","Keep profile mutations field-allowlisted.");
check("16.6.09","Address ownership",/findCustomerAddress\(customerId, addressId\)/.test(read("lib/customer/address-service.ts"))&&/addresses\.(getAddress|updateAddress|deleteAddress|setDefaultAddress)\(current\.customer\.id/.test(read("app/api/customer/addresses/[addressId]/route.ts")),["repository lookup and route ownership scope"],"Address IDs could be used for cross-customer access.","Require authenticated customer ID in every address operation.","CRITICAL");
check("16.6.10","Order ownership",/getOrderByCustomer\(identifier, customer\.id\)/.test(read("lib/orders/application.ts"))&&/getOrderByNumberForCustomer\(identifier, customer\.id\)/.test(read("lib/orders/application.ts")),["order detail queries are customer-scoped"],"Order IDOR would disclose financial and personal data.","Keep object-level authorization in the server repository boundary.","CRITICAL");
check("16.6.11","Privacy export authorization",/requireCurrentCustomer/.test(read("app/api/customer/privacy/route.ts"))&&/exportCustomerData\(current\.customer\.id/.test(read("app/api/customer/privacy/route.ts"))&&!/body\.customerId|searchParams.*customerId|params.*customerId/i.test(read("app/api/customer/privacy/route.ts")),["export identity is server-derived"],"A client-selected customer ID could expose another customer's data.","Never accept customer ownership from request parameters.","CRITICAL");
check("16.6.12","Privacy export minimization",/MAX_PRIVACY_EXPORT_RECORDS/.test(read("lib/customer/privacy.ts"))&&!/passwordHash|sessionTokenHash|sessionToken|apiKey|accessKey/.test(read("lib/customer/privacy.ts"))&&/private, no-store/.test(read("app/api/customer/privacy/route.ts")),["bounded export, secret exclusion, private no-store response"],"Exports could leak credentials or unbounded data.","Keep export bounded and explicitly selected.");
check("16.6.13","Privacy deletion safety",/PRIVACY_DELETE_CONFIRMATION/.test(read("lib/customer/privacy.ts"))&&/anonymizedAt/.test(read("lib/customer/privacy.ts"))&&/tx\.order\.delete|tx\.payment\.delete|tx\.fulfillment\.delete|tx\.shipment\.delete/.test(read("lib/customer/privacy.ts"))===false&&/Serializable/.test(read("lib/customer/privacy.ts")),["explicit confirmation, anonymization, historical record preservation, serializable transaction"],"Deletion could corrupt commercial history or be replayed unsafely.","Anonymize mutable identity data while retaining required transaction integrity.","CRITICAL");
check("16.6.14","Admin customer-data boundary",/requireAdmin\(request,"customers\.read"/.test(read("app/api/admin/customers/[customerId]/route.ts"))&&/customers\.update/.test(read("app/api/admin/customers/[customerId]/profile/route.ts"))&&/customers\.status\.manage/.test(read("app/api/admin/customers/[customerId]/status/route.ts"))&&/auditAdminAction/.test(read("app/api/admin/customers/[customerId]/route.ts")),["admin RBAC and audit evidence"],"Unauthorized staff could access or modify customer data.","Keep permission-specific admin routes and audit privileged access.","CRITICAL");
check("16.6.15","Privacy controls server enforcement",/requireCurrentCustomer/.test(read("app/api/customer/privacy/route.ts"))&&/consumeCustomerPrivacyRateLimit/.test(read("app/api/customer/privacy/route.ts"))&&/deleteCustomerData/.test(read("app/api/customer/privacy/route.ts")),["server authorization/rate limit/lifecycle service"],"A UI-only privacy control would not provide real protection.","Keep state changes enforced in server services.");
check("16.6.16","Password security",/hashPassword/.test(read("lib/auth/password.ts"))&&/scrypt|argon2|bcrypt/i.test(read("lib/auth/password.ts"))&&!/passwordHash.*console|console.*passwordHash/i.test(source),["password hashing implementation and runtime log scan"],"Plaintext or secret logging could compromise credentials.","Use one-way password hashing and never log credential material.","CRITICAL");
check("16.6.17","Password change abuse protection",/rateLimiter\.consume/.test(read("app/api/customer/security/password/route.ts"))&&/currentPassword/.test(read("app/api/customer/security/password/route.ts"))&&/revokeAllCustomerSessions/.test(read("lib/auth/service.ts")),["password endpoint rate limit, current-password check, session invalidation"],"Password takeover attempts could be automated or leave sessions trusted.","Retain rate limiting and security-event session revocation.","HIGH");
check("16.6.18","Communication privacy",/consumeCommunicationRateLimit/.test(read("app/api/customer/communications/preferences/route.ts"))&&/current\.customer\.id/.test(read("app/api/customer/communications/preferences/route.ts"))&&/assertSameOrigin/.test(read("app/api/customer/communications/preferences/route.ts")),["authenticated, same-origin, rate-limited preference changes"],"Preference manipulation could bypass communication controls.","Keep authenticated server-side preference mutation.");
check("16.6.19","Cache isolation",/dynamic = "force-dynamic"/.test(source)&&/revalidate = 0/.test(read("app/api/customer/privacy/route.ts"))&&/private, no-store/.test(read("app/api/customer/privacy/route.ts")),["dynamic account routes and no-store privacy export"],"Shared caches could leak customer-specific data.","Keep customer-specific APIs dynamic/private and audit any future caching.");
check("16.6.20","Request size validation",/16 \* 1024/.test(read("app/api/customer/addresses/route.ts"))&&/16 \* 1024/.test(read("app/api/customer/addresses/[addressId]/route.ts"))&&/readAuthJson/.test(read("app/api/customer/privacy/route.ts")),["bounded address payloads and shared auth JSON parsing"],"Oversized payloads could create avoidable resource pressure.","Retain bounded request parsing on customer mutation routes.","MEDIUM");
check("16.6.21","Same-origin state changes",runtime.filter(f=>/app\/api\/customer\//.test(f)&&/route\.ts$/.test(f)).every(f=>{const s=read(f);return !/export async function (POST|PUT|PATCH|DELETE)/.test(s)||/assertSameOrigin/.test(s)||/unsubscribe/.test(f)}),["customer mutation route scan"],"Cross-site state-changing requests could mutate account data.","Require same-origin protection on authenticated mutations.");
check("16.6.22","No client credential exposure",!clients.some(f=>/QIKINK_(CLIENT_SECRET|AUTH_TOKEN)|DATABASE_URL|SESSION_SECRET|PAYMENT_SECRET|passwordHash|sessionTokenHash/i.test(read(f))),["client source credential scan"],"Secrets exposed to client bundles are production-critical.","Keep credentials and server session material server-only.","CRITICAL");
check("16.6.23","Database lifecycle integrity",/model Customer \{/.test(schema)&&/model CustomerSession \{/.test(schema)&&/model CustomerCredential \{/.test(schema)&&/anonymizedAt/.test(schema)&&/@@unique/.test(schema),["customer/session/credential schema and uniqueness constraints"],"Weak database identity constraints could create duplicate or orphaned identities.","Keep unique identity and durable lifecycle markers.");
check("16.6.24","Audit/observability",/logAuthenticationEvent/.test(read("lib/auth/service.ts"))&&/CUSTOMER_PRIVACY_\$\{input\.operation\}/.test(read("lib/customer/privacy.ts"))&&/auditAdminAction/.test(read("app/api/admin/customers/[customerId]/route.ts")),["authentication, privacy and admin audit evidence"],"Security-sensitive account actions without audit evidence impair incident response.","Preserve structured audit events without secrets.");
check("16.6.25","No secret logging",!runtime.some(f=>read(f).split("\n").some(line=>/(console\.|logger\.)/.test(line)&&/(password|token|secret|cookie|authorization)/i.test(line))),["runtime log scan for secret-bearing fields"],"Logs can become a credential or privacy exfiltration channel.","Redact secrets and sensitive authentication material.","CRITICAL");
check("16.6.26","CI validation gate",/npm run lint/.test(ci)&&/npm run typecheck/.test(ci)&&/npm test/.test(ci)&&/npm run build/.test(ci)&&/npx prisma validate/.test(ci)&&/npx prisma generate/.test(ci),["existing CI validation suite"],"Certification without complete validation is not production evidence.","Run and require the complete suite.");
check("16.6.27","Migration safety",exists("prisma/migrations")&&!/migrate reset|db push/.test(ci)&&/db:audit-migrations/.test(ci),["forward-only migration CI controls"],"Destructive migration shortcuts can corrupt customer data.","Keep migration history append-only and audited.");
check("16.6.28","Customer support isolation",/requireCurrentCustomer/.test(read("app/api/customer/cases/page.ts")||"")||/customerId/.test(read("lib/customer/service.ts"))||exists("app/api/customer/cases"),["customer support surface exists"],"Support data without ownership isolation can leak personal information.","Keep case access scoped to authenticated customer identity.","MEDIUM");
check("16.6.29","Notification minimization",/SECURITY_PASSWORD_CHANGED/.test(read("app/api/customer/security/password/route.ts"))&&/payload: \{\}/.test(read("app/api/customer/security/password/route.ts"))&&/idempotencyKey:/.test(read("app/api/customer/security/password/route.ts")),["security notification uses empty payload and non-secret idempotency metadata"],"Security notifications could leak secrets.","Emit event metadata only, never credential material.");
check("16.6.30","Failure-injection test coverage",exists("tests/customer-authentication-authorization.test.ts")&&exists("tests/customer-account-security.test.ts")&&exists("tests/phase-15-6-data-privacy.test.ts"),["authorization, session-security and privacy regression suites"],"Missing adversarial tests can allow privacy regressions.","Maintain explicit authorization/privacy/security regression coverage.","MEDIUM");

const limitations=[
  ["16.6-L01","Email verification","Registration creates ACTIVE customers and no separate verification workflow is evidenced by the repository."],
  ["16.6-L02","Account recovery","No customer password-recovery endpoint/token workflow is evidenced by the current repository tree; password recovery is therefore not certified as implemented."],
  ["16.6-L03","Data export delivery","Export is synchronous and bounded to 5000 records per category; asynchronous export/download expiry is not implemented."],
  ["16.6-L04","Distributed rate limiting","Authentication/privacy/customer security rate limiters are in-memory process-local controls; cross-instance distributed enforcement is not evidenced."]
];
for(const [id,domain,evidence] of limitations) add(id,domain,"NOT APPLICABLE","INFORMATIONAL",[evidence],"The repository does not evidence this capability as implemented; inventing it would violate the phase scope.","Document the limitation and implement only under a future approved requirement.");

const failed=findings.filter(f=>f.status==="FAIL");
const critical=failed.filter(f=>f.severity==="CRITICAL").length;
const high=failed.filter(f=>f.severity==="HIGH").length;
const blocked=findings.filter(f=>f.status==="BLOCKED").length;
const decision=critical||blocked?"BLOCKED":high?"NOT READY FOR PHASE 16.7":"READY FOR PHASE 16.7";
console.log(JSON.stringify({phase:"16.6",decision,totals:{findings:findings.length,pass:findings.filter(f=>f.status==="PASS").length,fail:failed.length,critical,high,medium:failed.filter(f=>f.severity==="MEDIUM").length,low:failed.filter(f=>f.severity==="LOW").length,blocked,notApplicable:findings.filter(f=>f.status==="NOT APPLICABLE").length},findings},null,2));
if(critical||high||blocked) process.exitCode=1;
