import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { join, relative } from "node:path";
type Status="PASS"|"FAIL"|"BLOCKED"|"NOT APPLICABLE"; type Severity="CRITICAL"|"HIGH"|"MEDIUM"|"LOW"|"INFORMATIONAL";
type Finding={id:string;domain:string;status:Status;severity:Severity;evidence:string[];risk:string;remediation:string};
const root=process.cwd(), findings:Finding[]=[];
const read=(p:string)=>existsSync(join(root,p))?readFileSync(join(root,p),"utf8"):""; const exists=(p:string)=>existsSync(join(root,p));
function files(dir:string,out:string[]=[]){const full=join(root,dir);if(!existsSync(full))return out;for(const e of readdirSync(full)){if(["node_modules",".next",".git"].includes(e))continue;const child=join(full,e),rel=relative(root,child).replaceAll("\\","/");if(statSync(child).isDirectory())files(rel,out);else out.push(rel)}return out}
const all=files(".").filter(f=>/\.(ts|tsx|js|jsx|prisma|json|md|yml|yaml)$/.test(f)); const runtime=all.filter(f=>/^(app|lib|components)\//.test(f)&&!/\.(test|spec)\.(ts|tsx)$/.test(f)); const clients=all.filter(f=>/^(components|app)\//.test(f)&&/"use client"/.test(read(f)));
const source=runtime.map(read).join("\n"), schema=read("prisma/schema.prisma"), app=read("lib/shipping/application.ts"), domain=read("lib/shipping/domain.ts"), repo=read("lib/shipping/repository.ts"), contracts=read("lib/shipping/contracts.ts"), resolver=read("lib/shipping/resolver.ts"), qikink=read("lib/shipping/providers/qikink.ts"), returns=read("lib/returns/application.ts"), returnDomain=read("lib/returns/domain.ts"), ci=read(".github/workflows/ci.yml");
function add(id:string,d:string,status:Status,severity:Severity,evidence:string[],risk:string,remediation:string){findings.push({id,domain:d,status,severity,evidence,risk,remediation})}
function check(id:string,d:string,ok:boolean,e:string[],risk:string,rem:string,severity:Severity="HIGH"){add(id,d,ok?"PASS":"FAIL",ok?"INFORMATIONAL":severity,e,risk,rem)}
const checks:Array<[string,string,boolean,string[],string,string,Severity?]>=[
["16.5.01","Canonical shipping architecture",exists("lib/shipping/application.ts")&&exists("lib/shipping/domain.ts")&&exists("lib/shipping/repository.ts")&&exists("lib/shipping/resolver.ts"),["shipping application/domain/repository/resolver"],"Missing canonical shipping services could permit bypass implementations.","Restore the canonical shipping architecture."],
["16.5.02","Provider boundary",/ShippingProviderAdapter/.test(contracts)&&/createShippingProviderResolver/.test(resolver)&&!clients.some(f=>/qikink\.com|QIKINK_/i.test(read(f))),["shipping contracts/resolver","client scan"],"Provider calls from browser code could bypass server controls.","Keep provider integration behind server-side adapters.","CRITICAL"],
["16.5.03","Qikink shipping boundary",/createShipment:\s*false/.test(qikink)&&/trackingLookup:\s*false/.test(qikink)&&/webhooks:\s*false/.test(qikink),["Qikink shipping adapter"],"Fabricated provider capability could create false shipment/tracking state.","Keep unsupported Qikink capabilities explicitly unavailable."],
["16.5.04","Shipment eligibility",/assertFulfillmentEligibleForShipment/.test(app)&&/status !== "SUBMITTED"/.test(domain)&&/providerReference/.test(domain)&&/destinationExists/.test(domain),["shipping domain/application"],"Ineligible fulfillment could enter shipping.","Require canonical fulfillment status, provider reference, order relationship and destination."],
["16.5.05","Shipment idempotency",/creationIdempotencyKey/.test(schema)&&/getShipmentByCreationIdempotencyKey/.test(app)&&/Serializable/.test(app)&&/SHIPMENT_IDEMPOTENCY_CONFLICT/.test(app),["schema/application"],"Retries or concurrency could create duplicate shipments.","Preserve unique idempotency keys and serializable creation."],
["16.5.06","Unknown-result handling",/reconciliationRequired/.test(schema)&&/RECONCILIATION_REQUIRED/.test(app)&&/markReconciliationRequired/.test(app),["shipping schema/application"],"Unknown provider state could be treated as success or blindly retried.","Quarantine ambiguous conditions for reconciliation."],
["16.5.07","Shipment state machine",/TRANSITIONS/.test(domain)&&/DELIVERED:\s*\[\]/.test(domain)&&/RETURNED:\s*\[\]/.test(domain),["shipping domain"],"Illegal transitions could corrupt lifecycle state.","Use the canonical transition matrix and terminal-state protection."],
["16.5.08","Tracking integrity",/processNormalizedTrackingEvent/.test(app)&&/shipment\.providerId !== input\.event\.providerId/.test(app)&&/createTrackingEventIfNew/.test(app)&&/assertTrackingEventTransition/.test(app),["shipping application"],"Forged or mismatched provider events could mutate state.","Validate provider identity, deduplicate events and enforce transitions.","CRITICAL"],
["16.5.09","Tracking ordering/replay",/shouldApplyTrackingEvent/.test(app)&&/HISTORY_ONLY/.test(domain)&&/providerEventId/.test(repo),["shipping domain/application/repository"],"Replay or stale events could regress shipment state.","Keep event deduplication and history-only handling."],
["16.5.10","Delivery authority",/DELIVERED/.test(domain)&&/transitionFromTrackingEvent/.test(app)&&!/customer.*DELIVERED.*status.*input/i.test(app),["shipping domain/application"],"Client-controlled delivery state could falsely mark orders delivered.","Accept delivery only through trusted normalized tracking events.","CRITICAL"],
["16.5.11","Customer object authorization",/getShipmentByCustomer\(input\.shipmentId, input\.customerId\)/.test(app)&&/getShipmentByReference\(reference, input\.customerId\)/.test(app),["shipping application/repository"],"IDOR could expose another customer's shipment.","Scope every customer lookup by authenticated customer identity.","CRITICAL"],
["16.5.12","Admin authorization",["shipping.create","shipping.reconcile","shipping.recovery"].every(p=>read("lib/admin/shipping.ts").includes(p))&&/requireAdmin/.test(read("app/api/admin/shipping/route.ts"))&&/requireAdmin/.test(read("app/api/admin/shipping/[shipmentId]/route.ts")),["admin routes + canonical service"],"Unauthorized operational actions could mutate shipping.","Keep admin shipping operations behind RBAC."],
["16.5.13","Admin sensitive-data gating",/shipping\.view_sensitive/.test(read("lib/admin/shipping.ts"))&&/sensitive\?row\.trackingNumber:null/.test(read("lib/admin/shipping.ts")),["admin shipping service"],"Sensitive provider/customer data could be exposed broadly.","Gate sensitive fields by explicit permission."],
["16.5.14","Admin mutation boundary",!/db\.(shipment|trackingEvent)\.(create|update|updateMany|delete|deleteMany)/.test(read("lib/admin/shipping.ts"))&&/createShippingApplication/.test(read("lib/admin/shipping.ts")),["admin shipping service"],"Admin UI could bypass canonical shipping transitions.","Route mutations through the canonical Shipping application."],
["16.5.15","Return state machine",/RETURN_TRANSITIONS/.test(returnDomain)&&/assertReturnTransition/.test(returns)&&/RESOLVED:\s*\[\]/.test(returnDomain),["returns domain/application"],"Invalid return transitions could corrupt post-order state.","Keep return lifecycle transitions server-authoritative."],
["16.5.16","Cancellation boundary",/cancellationEligibility/.test(returnDomain)&&/assertCancellationTransition/.test(returns),["returns domain/application"],"Cancellation after terminal delivery could violate business rules.","Use canonical cancellation eligibility and transitions."],
["16.5.17","Refund financial boundary",/REFUND_UNAVAILABLE/.test(returns)&&/Payment\/refund.*not implemented/.test(returns),["returns application"],"Shipping/returns could become financial authority.","Keep refund execution in the payment domain and classify unsupported execution as a limitation."],
["16.5.18","Reconciliation safety",/reconcileShipment/.test(app)&&/PROVIDER_UNSUPPORTED/.test(app)&&/RECONCILIATION_REQUIRED/.test(app)&&/markReconciliationRequired/.test(app),["shipping application"],"Reconciliation could blindly overwrite authoritative state.","Require verified provider capability and explicit reconciliation outcomes."],
["16.5.19","Operational recovery idempotency",/requestShipmentReconciliation/.test(app)&&/getRecoveryActionByIdempotencyKey/.test(app)&&/SHIPMENT_IDEMPOTENCY_CONFLICT/.test(app),["shipping application/repository"],"Repeated recovery requests could duplicate actions.","Use durable idempotency and authorization."],
["16.5.20","Concurrency protection",/Serializable/.test(app)&&/P2034/.test(app)&&/expectedStatus/.test(repo)&&/updateMany/.test(repo),["shipping application/repository"],"Concurrent operations could produce duplicate or illegal state.","Use serializable transactions and compare-and-set transitions."],
["16.5.21","Audit/observability",/logShippingObservation/.test(app)&&/shipping_operations_total/.test(read("lib/shipping/observability.ts"))&&/correlationId/.test(read("lib/shipping/observability.ts")),["shipping observability/application"],"Operational failures without correlation or metrics impair safe operations.","Preserve structured shipping observations."],
["16.5.22","Secret logging",!["lib/fulfillment/providers/qikink.ts","lib/fulfillment/providers/qikink-auth.ts","lib/shipping/providers/qikink.ts","lib/shipping/observability.ts"].some(f=>read(f).split("\n").some(line=>/logger\.(info|warn|error|debug)|console\.(log|warn|error)/.test(line)&&/secret|token|payment/i.test(line))),["runtime logging scan"],"Secrets in shipping runtime create credential leakage.","Never log credentials or payment secrets.","CRITICAL"],
["16.5.23","Provider endpoint trust",/qikink\.com/.test(read("lib/fulfillment/providers/qikink.ts"))&&!/request\.[A-Za-z]+\(.*url/.test(read("lib/fulfillment/providers/qikink.ts")),["Qikink fulfillment provider"],"Client-controlled provider endpoints could create SSRF.","Keep provider endpoints in trusted server configuration."],
["16.5.24","Provider capability truth",/createShipment:\s*false/.test(qikink)&&/trackingLookup:\s*false/.test(qikink)&&/webhooks:\s*false/.test(qikink),["Qikink shipping adapter"],"UI/database fields must not be treated as provider capability.","Certify only implemented and verified capabilities."],
["16.5.25","Webhook boundary",!/webhooks:\s*true/.test(qikink),["Qikink shipping adapter"],"Unsupported webhook behavior could accept forged events.","Do not invent a Qikink webhook contract."],
["16.5.26","Polling boundary",!/setInterval\(/.test(source)&&!/tracking.*poll/i.test(source),["shipping runtime scan"],"Unbounded polling could create provider request storms.","Do not poll without a verified provider contract."],
["16.5.27","Customer-facing projection",/safeCustomerDto/.test(app)&&/statusLabel/.test(app)&&/latestEvent/.test(app),["shipping application"],"Customer UI could display fabricated state.","Project only canonical shipment/tracking state."],
["16.5.28","Database integrity",/model Shipment \{/.test(schema)&&/creationIdempotencyKey[^\n]*@unique/.test(schema)&&/model TrackingEvent/.test(schema)&&/model ShipmentRecoveryAction/.test(schema),["prisma schema"],"Missing uniqueness/lifecycle constraints permit duplicates.","Keep database constraints authoritative."],
["16.5.29","CI provider safety",/NODE_ENV: test/.test(ci)&&!/QIKINK_(CLIENT_SECRET|AUTH_TOKEN)/.test(ci)&&/npm test/.test(ci),["CI workflow"],"CI must not create uncontrolled real shipments.","Use deterministic provider-neutral tests."],
["16.5.30","Required validation gates",/npm run lint/.test(ci)&&/npm run typecheck/.test(ci)&&/npm test/.test(ci)&&/npm run build/.test(ci)&&/prisma validate/.test(ci)&&/prisma generate/.test(ci),["CI workflow"],"Certification without the full validation suite is incomplete.","Run the complete validation suite."],
["16.5.31","No direct client shipment mutation",!/status\s*:|trackingNumber\s*:|carrier\s*:|trackingUrl\s*:/.test(read("components/admin/shipment-action.tsx"))&&/fetch\(\"\/api\/admin\/shipping/.test(read("components/admin/shipment-action.tsx")),["components/admin/shipment-action.tsx"],"Browser-controlled shipment state could bypass server authorization.","Allow only action metadata from the browser; derive shipment state server-side.","CRITICAL"],
["16.5.32","Provider credentials server-only",!clients.some(f=>/QIKINK_(CLIENT_SECRET|AUTH_TOKEN|SANDBOX_SECRET)|FULFILLMENT_PROVIDER_SECRET|PAYMENT_SECRET/i.test(read(f))),["client credential scan"],"Provider credentials exposed to browsers are critical.","Keep provider credentials server-side.","CRITICAL"],
["16.5.33","Migration safety",exists("prisma/migrations")&&/db:audit-migrations/.test(ci)&&!/migrate reset|db push/i.test(ci),["migrations/CI"],"Destructive migration shortcuts can corrupt production data.","Use forward-only migrations."],
["16.5.34","Failure-injection coverage",all.some(f=>/shipping.*test|phase-13.*shipping/i.test(f)),["shipping test suite scan"],"Missing shipping failure tests can hide retry/concurrency regressions.","Maintain deterministic shipping failure tests.","MEDIUM"],
];
for(const c of checks)check(...c);
for(const [id,d,e] of [["16.5-L01","Qikink shipment creation","Qikink createShipment is false; fulfillment handoff is not equivalent to provider shipment creation."],["16.5-L02","Qikink tracking","Qikink trackingLookup and webhooks are false; no verified machine tracking contract exists."],["16.5-L03","Refund execution","Returns explicitly stops financial resolutions at the payment/refund integration boundary."]])add(id,d,"NOT APPLICABLE","INFORMATIONAL",[e],"The capability is intentionally unsupported in the verified contract.","Document the limitation and do not fabricate capability.");
const failed=findings.filter(f=>f.status==="FAIL"),critical=failed.filter(f=>f.severity==="CRITICAL").length,high=failed.filter(f=>f.severity==="HIGH").length,blocked=findings.filter(f=>f.status==="BLOCKED").length;
const decision=critical||blocked?"BLOCKED":high?"NOT READY FOR PHASE 16.6":"READY FOR PHASE 16.6";
console.log(JSON.stringify({phase:"16.5",certification:decision,totals:{checks:findings.length,passed:findings.filter(f=>f.status==="PASS").length,failed:failed.length,critical,high,medium:failed.filter(f=>f.severity==="MEDIUM").length,low:failed.filter(f=>f.severity==="LOW").length,blocked,notApplicable:findings.filter(f=>f.status==="NOT APPLICABLE").length},qikink:{fulfillmentOnly:true,shipping:{createShipment:false,trackingLookup:false,webhooks:false}},findings},null,2));
if(critical||high||blocked)process.exitCode=1;
