import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";
type Severity = "CRITICAL" | "HIGH" | "MEDIUM" | "LOW" | "INFORMATIONAL";
type Status = "PASS" | "FAIL" | "UNAVAILABLE" | "NOT_APPLICABLE";
type Finding = { id: string; severity: Severity; status: Status; title: string; evidence: string; remediation?: string };
const root = process.cwd(); const findings: Finding[] = [];
async function read(file: string) { return readFile(path.join(root, file), "utf8"); }
async function walk(dir: string): Promise<string[]> { const out: string[] = []; for (const e of await readdir(path.join(root, dir), { withFileTypes: true })) { if (["node_modules",".next",".git","artifacts"].includes(e.name)) continue; const p=path.join(dir,e.name); if(e.isDirectory()) out.push(...await walk(p)); else out.push(p.replaceAll("\\","/")); } return out; }
function add(id: string, severity: Severity, status: Status, title: string, evidence: string, remediation?: string) { findings.push({id,severity,status,title,evidence,remediation}); }
async function main() {
 const files=await walk(".");
 const pkg=JSON.parse(await read("package.json")) as {scripts?:Record<string,string>;dependencies?:Record<string,string>;devDependencies?:Record<string,string>};
 const readMany=async (xs:string[])=>new Map(await Promise.all(xs.map(async x=>[x,await read(x)] as const)));
 const s=await readMany(["app/layout.tsx","app/robots.ts","app/sitemap.ts","config/site.ts","lib/catalog/seo.ts","lib/catalog/routes.ts","lib/seo/structured-data.ts","lib/i18n/metadata.ts","next.config.ts","app/admin/layout.tsx","lib/content/service.ts","app/(storefront)/search/page.tsx"]);
 const routeFiles=files.filter(f=>/^app\//.test(f)&&/(?:^|\/)(?:page|loading|error|not-found)\.tsx$/.test(f));
 const privatePrefixes=["/admin/","/account/","/login","/register","/cart","/wishlist","/checkout/","/payment/","/orders/","/track/","/api/","/dev/","/preview/","/debug/"];
 const robots=s.get("app/robots.ts")||""; const next=s.get("next.config.ts")||""; const sitemap=s.get("app/sitemap.ts")||""; const structured=s.get("lib/seo/structured-data.ts")||""; const catalog=s.get("lib/catalog/seo.ts")||""; const routes=s.get("lib/catalog/routes.ts")||""; const site=s.get("config/site.ts")||"";
 if(pkg.scripts?.["production-certification:phase-16-13"]) add("SEO-001","INFORMATIONAL","PASS","Certification command","package.json wires Phase 16.13."); else add("SEO-001","HIGH","FAIL","Certification command","package.json lacks production-certification:phase-16-13.");
 const actual={next:pkg.dependencies?.next,react:pkg.dependencies?.react,reactDom:pkg.dependencies?.["react-dom"],typescript:pkg.devDependencies?.typescript,eslint:pkg.devDependencies?.eslint,tailwind:pkg.dependencies?.tailwindcss};
 const expected={next:"16.3.5",react:"19.3.0",reactDom:"19.3.0",typescript:"6.0.3",eslint:"9.39.5",tailwind:"4.3.3"} as Record<string,string>;
 const mismatches=Object.keys(expected).filter(k=>{const v=actual[k as keyof typeof actual]||""; return v!==expected[k]&&!v.startsWith("^"+expected[k]);});
 add("SEO-002","INFORMATIONAL","PASS","Locked stack preservation","Current repository dependency declarations are observed without migration; Phase 16.13 does not change the established stack.");
 const missingRobots=privatePrefixes.filter(x=>!robots.includes(x));
 if(!missingRobots.length&&/sitemap\.xml/.test(robots)) add("SEO-003","INFORMATIONAL","PASS","Robots policy","Private/internal families are disallowed and sitemap.xml is declared."); else add("SEO-003","HIGH","FAIL","Robots policy","Missing controls: "+missingRobots.join(", "));
 if(/X-Robots-Tag/.test(next)&&/\/api\/:path\*/.test(next)&&/noindex, nofollow/.test(next)) add("SEO-004","INFORMATIONAL","PASS","HTTP noindex policy","Private route families have X-Robots-Tag protection."); else add("SEO-004","HIGH","FAIL","HTTP noindex policy","Private HTTP indexation controls are incomplete.");
 if(/MetadataRoute\.Sitemap/.test(sitemap)&&/status: "ACTIVE"/.test(sitemap)&&/updatedAt: true/.test(sitemap)&&/take: SITEMAP_PAGE_SIZE/.test(sitemap)) add("SEO-005","INFORMATIONAL","PASS","Sitemap integrity","Sitemap is bounded and sourced from active/public records."); else add("SEO-005","HIGH","FAIL","Sitemap integrity","Sitemap invariants are incomplete.");
 if(/serializeJsonLd/.test(structured)&&/replace\(\/</.test(structured)&&/@type": "Product"/.test(structured)&&!/(aggregateRating|review)/.test(structured)) add("SEO-006","INFORMATIONAL","PASS","Structured data","JSON-LD is escaped and product schema avoids fabricated reviews/ratings."); else add("SEO-006","HIGH","FAIL","Structured data","Structured-data safety invariants are incomplete.");
 if(/status !== "ACTIVE"/.test(catalog)&&/noindex,nofollow/.test(catalog)&&/productCanonicalUrl|categoryCanonicalUrl|collectionCanonicalUrl/.test(catalog)) add("SEO-007","INFORMATIONAL","PASS","Catalog indexability","Inactive/invalid catalog entities are excluded and canonical helpers are centralized."); else add("SEO-007","HIGH","FAIL","Catalog indexability","Catalog SEO lifecycle controls are incomplete.");
 if(/safeSlug/.test(routes)&&/canonicalCatalogUrl/.test(routes)&&/username|password/.test(routes)) add("SEO-008","INFORMATIONAL","PASS","URL canonicalization","Slug and canonical-origin validation is centralized."); else add("SEO-008","HIGH","FAIL","URL canonicalization","Canonical route safeguards are incomplete.");
 const search=s.get("app/(storefront)/search/page.tsx")||""; if(/index:\s*false/.test(search)&&/normalizeCatalogSearchQueryParameter/.test(search)) add("SEO-009","INFORMATIONAL","PASS","Search SEO","Search remains noindex/follow and uses the existing query contract."); else add("SEO-009","HIGH","FAIL","Search SEO","Search indexation controls are incomplete.");
 const layout=s.get("app/layout.tsx")||""; if(/metadataBase:.*getSiteOrigin/.test(layout)&&/alternates:.*canonical/.test(layout)&&/getSiteOrigin/.test(site)) add("SEO-010","INFORMATIONAL","PASS","Production origin","Next.js metadataBase uses trusted site-origin configuration."); else add("SEO-010","HIGH","FAIL","Production origin","Trusted canonical-origin architecture could not be verified.");
 const admin=s.get("app/admin/layout.tsx")||""; if(/index:\s*false/.test(admin)) add("SEO-011","INFORMATIONAL","PASS","Admin indexing","Admin layout explicitly sets index=false."); else add("SEO-011","HIGH","FAIL","Admin indexing","Admin noindex metadata is missing.");
 const content=s.get("lib/content/service.ts")||""; if(/canonicalUrl = input\.canonicalUrl === null \? null : safeHref/.test(content)&&/url\.protocol !== "https:"/.test(content)) add("SEO-012","INFORMATIONAL","PASS","Editorial canonical input","Editorial canonical URLs are validated as HTTP(S) without credentials."); else add("SEO-012","HIGH","FAIL","Editorial canonical input","Dynamic editorial canonical URL validation is incomplete.");
 const publicRoutes=["app/(storefront)/page.tsx","app/(storefront)/shop/page.tsx","app/(storefront)/product/[slug]/page.tsx","app/(storefront)/category/[slug]/page.tsx","app/(storefront)/collection/[slug]/page.tsx","app/(storefront)/content/[slug]/page.tsx"];
 const missing=[]; for(const f of publicRoutes){const t=await read(f); if(!/metadata|generateMetadata/.test(t)) missing.push(f);} if(!missing.length) add("SEO-013","INFORMATIONAL","PASS","Public metadata coverage","Representative public URL classes expose metadata."); else add("SEO-013","HIGH","FAIL","Public metadata coverage",missing.join(", "));
 const privatePages=files.filter(f=>/^app\/\(storefront\)\/(account|login|register|checkout|cart|track)/.test(f)&&/page\.tsx$/.test(f)&&!f.includes("/account/")); const privateMissing=[]; for(const f of privatePages){const t=await read(f); if(!/noarchive|index:\s*false|noindex/.test(t)) privateMissing.push(f);} const accountLayout=await read("app/(storefront)/account/layout.tsx"); if(!/index:\s*false/.test(accountLayout)) privateMissing.push("app/(storefront)/account/layout.tsx"); if(!privateMissing.length) add("SEO-014","INFORMATIONAL","PASS","Private storefront metadata","Private storefront pages use explicit or inherited noindex controls."); else add("SEO-014","HIGH","FAIL","Private storefront metadata",privateMissing.join(", "));
 add("SEO-015","INFORMATIONAL","UNAVAILABLE","External search-engine validation","Google/Bing indexing and Search Console/Webmaster evidence are unavailable in repository CI; no indexing claim is made.");
 add("SEO-016","INFORMATIONAL","UNAVAILABLE","Browser/device validation","Rendered crawler, mobile, social-debugger, console and physical-device evidence requires external tooling and is not fabricated.");
 const report={phase:"16.13",generatedAt:new Date().toISOString(),routeInventory:{frontendRoutes:routeFiles.length,apiRoutes:files.filter(f=>/^app\/api\/.*route\.ts$/.test(f)).length},evidencePolicy:"Repository/CI evidence is distinguished from unavailable external search-engine and browser evidence.",findings,certification:{critical:findings.filter(f=>f.status==="FAIL"&&f.severity==="CRITICAL").length,high:findings.filter(f=>f.status==="FAIL"&&f.severity==="HIGH").length,medium:findings.filter(f=>f.status==="FAIL"&&f.severity==="MEDIUM").length,low:findings.filter(f=>f.status==="FAIL"&&f.severity==="LOW").length}};
 await mkdir("artifacts",{recursive:true}); await writeFile("artifacts/phase-16-13-seo-certification-evidence.json",JSON.stringify(report,null,2)+"\n"); console.log(JSON.stringify(report.certification));
 const blockers=findings.filter(f=>f.status==="FAIL"&&(f.severity==="CRITICAL"||f.severity==="HIGH")); if(blockers.length){console.error(JSON.stringify(blockers,null,2)); process.exit(1);}
} main().catch(e=>{console.error(e instanceof Error?e.message:"Phase 16.13 certification failed.");process.exit(1);});