import Link from "next/link";
import { requireAdmin } from "@/lib/admin/authorization";
import { listAdminPayments, parseAdminPaymentQuery } from "@/lib/admin/payments";
export default async function AdminPaymentsPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const context=await requireAdmin(undefined,"payments.read");const raw=await searchParams;const url=new URL("https://admin.local/admin/payments");for(const [k,v] of Object.entries(raw)){if(Array.isArray(v))v.forEach(x=>url.searchParams.append(k,x));else if(v!==undefined)url.searchParams.set(k,v);}const query=parseAdminPaymentQuery(url);const data=await listAdminPayments(query,context.permissions.has("payments.view_sensitive"));
 return <section className="space-y-6">
  <header className="border-4 border-black bg-white p-6 shadow-[8px_8px_0_0_#000]"><p className="text-xs font-black uppercase tracking-[0.2em]">Financial operations control plane</p><h2 className="mt-2 text-4xl font-black uppercase">Payments</h2><p className="mt-2 max-w-3xl">Canonical payment visibility with permission-gated sensitive references. Financial mutations are available only through the Payment application service.</p></header>
  <form method="get" className="border-4 border-black bg-[#f7d51d] p-4 shadow-[6px_6px_0_0_#000]"><div className="grid gap-3 md:grid-cols-4">
   <label className="md:col-span-2"><span className="text-xs font-black uppercase">Search</span><input name="search" defaultValue={query.search||""} placeholder="Payment ref, order, customer email" className="mt-1 w-full border-2 border-black bg-white p-2"/></label>
   <label><span className="text-xs font-black uppercase">Payment outcome</span><select name="outcome" defaultValue={query.outcome||""} className="mt-1 w-full border-2 border-black bg-white p-2"><option value="">All outcomes</option><option value="successful">Successful payments</option><option value="failed">Failed payments</option></select></label>
   <label><span className="text-xs font-black uppercase">Exact status</span><select name="status" defaultValue={query.status||""} className="mt-1 w-full border-2 border-black bg-white p-2"><option value="">All statuses</option>{["CREATED","REQUIRES_ACTION","PROCESSING","SUCCEEDED","FAILED","CANCELLED","EXPIRED","REFUNDED","PARTIALLY_REFUNDED"].map(x=><option key={x} value={x}>{x}</option>)}</select></label>
   <label><span className="text-xs font-black uppercase">Provider</span><input name="providerId" defaultValue={query.providerId||""} className="mt-1 w-full border-2 border-black bg-white p-2"/></label>
   <label><span className="text-xs font-black uppercase">Currency</span><input name="currency" maxLength={3} defaultValue={query.currency||""} className="mt-1 w-full border-2 border-black bg-white p-2"/></label>
   <label><span className="text-xs font-black uppercase">Min amount</span><input name="minAmount" inputMode="decimal" defaultValue={query.minAmount||""} className="mt-1 w-full border-2 border-black bg-white p-2"/></label>
   <label><span className="text-xs font-black uppercase">Max amount</span><input name="maxAmount" inputMode="decimal" defaultValue={query.maxAmount||""} className="mt-1 w-full border-2 border-black bg-white p-2"/></label>
   <label><span className="text-xs font-black uppercase">Refund</span><select name="refundStatus" defaultValue={query.refundStatus||""} className="mt-1 w-full border-2 border-black bg-white p-2"><option value="">Any</option>{["PENDING","SUCCEEDED","FAILED","AMBIGUOUS"].map(x=><option key={x}>{x}</option>)}</select></label>
   <label><span className="text-xs font-black uppercase">Sort</span><select name="sort" defaultValue={query.sort} className="mt-1 w-full border-2 border-black bg-white p-2"><option value="createdAt_desc">Newest</option><option value="createdAt_asc">Oldest</option><option value="amount_desc">Amount high</option><option value="amount_asc">Amount low</option></select></label>
   <label><span className="text-xs font-black uppercase">From</span><input type="date" name="from" className="mt-1 w-full border-2 border-black bg-white p-2"/></label><label><span className="text-xs font-black uppercase">To</span><input type="date" name="to" className="mt-1 w-full border-2 border-black bg-white p-2"/></label>
  </div><div className="mt-3 flex gap-2"><button className="border-2 border-black bg-black px-4 py-2 font-black uppercase text-white">Apply filters</button><Link href="/admin/payments" className="border-2 border-black bg-white px-4 py-2 font-black uppercase">Reset</Link></div></form>
  <div className="overflow-x-auto border-4 border-black bg-white"><table className="w-full min-w-[1100px] border-collapse"><caption className="sr-only">Administrative payment list</caption><thead><tr className="border-b-4 border-black bg-black text-left text-xs font-black uppercase text-white">{["Payment","Order","Customer","Status","Amount","Provider","Refunds","Created"].map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{data.payments.map(p=><tr key={p.id} className="border-b-2 border-black align-top"><td className="p-3"><Link className="font-black underline" href={"/admin/payments/"+p.id}>{p.reference}</Link><p className="text-xs">{p.id}</p></td><td className="p-3">{p.order?<><Link className="font-black underline" href={"/admin/orders/"+p.order.orderNumber}>{p.order.orderNumber}</Link><p>{p.order.currency} {p.order.total}</p></>: "—"}</td><td className="p-3"><p className="font-bold">{p.customer.displayName||"Unnamed"}</p><p className="text-xs break-all">{p.customer.email}</p></td><td className="p-3 font-black">{p.status}</td><td className="p-3 font-black">{p.currency} {p.amount}</td><td className="p-3">{p.providerId||"—"}{p.providerReference&&<p className="text-xs break-all">{p.providerReference}</p>}</td><td className="p-3">Succeeded {p.refund.succeeded}<br/>Reserved {p.refund.pending}</td><td className="p-3 text-sm">{new Date(p.createdAt).toLocaleString("en-IN")}</td></tr>)}</tbody></table>{!data.payments.length&&<p className="p-6 font-bold">No payments matched the current filters.</p>}</div>
  <footer className="flex justify-between font-bold"><span>Page {data.pagination.page} / {data.pagination.totalPages} · {data.pagination.total} payments</span><span className="flex gap-2">{query.page>1&&<Link className="border-2 border-black px-3 py-2" href={"/admin/payments?page="+(query.page-1)}>Previous</Link>}{data.pagination.hasNextPage&&<Link className="border-2 border-black bg-[#f7d51d] px-3 py-2" href={"/admin/payments?page="+(query.page+1)}>Next</Link>}</span></footer>
 </section>;
}