import Link from "next/link";
import { notFound } from "next/navigation";
import { requireAdmin } from "@/lib/admin/authorization";
import { getCatalogProduct } from "@/lib/admin/catalog";
import { CatalogProductForm } from "@/components/admin/catalog/catalog-product-form";
import { CatalogAction } from "@/components/admin/catalog/catalog-action";
import { CatalogVariantManager } from "@/components/admin/catalog/catalog-variant-manager";
import { CatalogMediaManager } from "@/components/admin/catalog/catalog-media-manager";
export default async function CatalogProductPage({params}:{params:Promise<{id:string}>}){const context=await requireAdmin(undefined,"catalog.read");const id=(await params).id;let data;try{data=await getCatalogProduct(context,id)}catch(e){notFound()}const p:any=data.product;return <section className="space-y-8"><header className="flex flex-wrap items-end justify-between gap-4"><div><Link href="/admin/catalog" className="font-bold underline">← Catalog</Link><p className="mt-5 text-sm font-black uppercase tracking-[0.2em]">{p.status}</p><h2 className="text-4xl font-black uppercase">{p.title}</h2><p className="mt-2">{p.slug}</p></div><div className="flex flex-wrap gap-2">{context.permissions.has("catalog.publish")&&p.status==="DRAFT"&&<CatalogAction endpoint={"/api/admin/catalog/products/"+id+"/publish"} label="Publish" reasonRequired expectedUpdatedAt={p.updatedAt}/>}{context.permissions.has("catalog.publish")&&p.status==="ACTIVE"&&<CatalogAction endpoint={"/api/admin/catalog/products/"+id+"/unpublish"} label="Unpublish" reasonRequired/>}{context.permissions.has("catalog.archive")&&p.status!=="ARCHIVED"&&<CatalogAction endpoint={"/api/admin/catalog/products/"+id+"/archive"} label="Archive" reasonRequired expectedUpdatedAt={p.updatedAt} tone="red"/>}{context.permissions.has("catalog.publish")&&p.status==="ARCHIVED"&&<CatalogAction endpoint={"/api/admin/catalog/products/"+id+"/restore"} label="Restore" reasonRequired/>}</div></header><CatalogProductForm mode="edit" product={p}/><section className="grid gap-5 lg:grid-cols-2"><div className="border-4 border-black bg-white p-5"><h3 className="text-xl font-black uppercase">Variants</h3><div className="mt-4"><CatalogVariantManager productId={p.id} variants={p.variants??[]} canManage={context.permissions.has("catalog.update")}/></div></div><div className="border-4 border-black bg-white p-5"><h3 className="text-xl font-black uppercase">Media</h3><div className="mt-4"><CatalogMediaManager images={p.images??[]} canManage={context.permissions.has("catalog.media.manage")}/></div></div></section><section className="border-4 border-black bg-white p-5"><h3 className="text-xl font-black uppercase">Provider mappings</h3><p className="mt-2 text-sm">These are fulfillment mappings only and are never the canonical storefront SKU.</p><div className="mt-4 grid gap-3">{(data.providerMappings as any[]).map((group:any)=><div key={group.variantId} className="border-2 border-black p-3"><strong>Variant {group.variantId}</strong>{group.mappings.map((m:any)=><div key={m.id} className="mt-2 flex flex-wrap justify-between gap-2 text-sm"><span>{m.providerId}: {m.providerSku}</span><span>{m.active?"ACTIVE":"INACTIVE"}</span></div>)}</div>)}</div></section></section>}
