import Link from "next/link";
import {requireAdmin} from "@/lib/admin/authorization";
import {listAdminCustomers,parseAdminCustomerQuery} from "@/lib/admin/customer-query";

export const dynamic="force-dynamic";export const revalidate=0;

export default async function CustomersPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const context=await requireAdmin(undefined,"customers.read");const raw=await searchParams;const url=new URL("https://admin.local/admin/customers");
 for(const [k,v] of Object.entries(raw)){if(Array.isArray(v))v.forEach(x=>url.searchParams.append(k,x));else if(v!==undefined)url.searchParams.set(k,v);}
 const query=parseAdminCustomerQuery(url,context.permissions);const data=await listAdminCustomers(query);const params=new URLSearchParams(url.searchParams);
 const href=(page:number)=>{const p=new URLSearchParams(params);p.set("page",String(page));return "/admin/customers?"+p.toString();};
 return <section className="space-y-6">
  <header className="border-4 border-black bg-white p-6 shadow-[8px_8px_0_0_#000]"><p className="text-xs font-black uppercase tracking-[0.2em]">Customer operations</p><h2 className="mt-2 text-4xl font-black uppercase">Customers</h2><p className="mt-3 max-w-3xl">Search and operate on canonical customer records. Orders, payments, returns, cancellations and cases remain owned by their domains.</p></header>
  <form method="get" className="border-4 border-black bg-[#f7d51d] p-5 shadow-[6px_6px_0_0_#000]"><div className="grid gap-3 md:grid-cols-4">
   <label className="md:col-span-2"><span className="text-xs font-black uppercase">Search</span><input name="search" defaultValue={query.search} maxLength={80} placeholder="Email, name or exact customer ID" className="mt-1 w-full border-2 border-black bg-white p-2"/></label>
   <label><span className="text-xs font-black uppercase">Status</span><select name="status" defaultValue={query.status??""} className="mt-1 w-full border-2 border-black bg-white p-2"><option value="">All</option><option>ACTIVE</option><option>DISABLED</option><option>SUSPENDED</option><option>PENDING_VERIFICATION</option></select></label>
   <label><span className="text-xs font-black uppercase">Verification</span><select name="verified" defaultValue={query.verified??""} className="mt-1 w-full border-2 border-black bg-white p-2"><option value="">All</option><option value="verified">Verified</option><option value="unverified">Unverified</option></select></label>
   <label><span className="text-xs font-black uppercase">Created from</span><input type="date" name="createdFrom" defaultValue={query.createdFrom??""} className="mt-1 w-full border-2 border-black bg-white p-2"/></label>
   <label><span className="text-xs font-black uppercase">Created to</span><input type="date" name="createdTo" defaultValue={query.createdTo??""} className="mt-1 w-full border-2 border-black bg-white p-2"/></label>
   <label><span className="text-xs font-black uppercase">Sort</span><select name="sort" defaultValue={query.sort} className="mt-1 w-full border-2 border-black bg-white p-2"><option value="createdAt">Created</option><option value="updatedAt">Updated</option><option value="displayName">Name</option><option value="email">Email</option><option value="orderCount">Order count</option>{context.permissions.has("customers.financial.read")&&<option value="grossPurchaseValue">Purchase value</option>}</select></label>
   <label><span className="text-xs font-black uppercase">Direction</span><select name="direction" defaultValue={query.direction} className="mt-1 w-full border-2 border-black bg-white p-2"><option value="desc">Descending</option><option value="asc">Ascending</option></select></label>
  </div><div className="mt-4 flex gap-2"><button className="border-2 border-black bg-black px-4 py-2 font-black uppercase text-white">Apply filters</button><Link href="/admin/customers" className="border-2 border-black bg-white px-4 py-2 font-black uppercase">Reset</Link></div></form>
  <div className="overflow-x-auto border-4 border-black bg-white"><table className="w-full min-w-[900px] border-collapse text-left"><caption className="sr-only">Administrative customer list</caption><thead><tr className="border-b-4 border-black bg-black text-xs uppercase text-white"><th className="p-3">Customer</th><th className="p-3">Status</th><th className="p-3">Verified</th><th className="p-3">Orders</th><th className="p-3">Last activity</th>{context.permissions.has("customers.financial.read")&&<th className="p-3">Paid value</th>}</tr></thead><tbody>{data.customers.map(c=><tr key={c.id} className="border-b-2 border-black"><td className="p-3"><Link href={"/admin/customers/"+c.id} className="font-black underline">{c.displayName||"Unnamed customer"}</Link><p className="break-all text-xs">{c.email}</p></td><td className="p-3 font-bold">{c.status}</td><td className="p-3">{c.emailVerifiedAt?"Yes":"No"}</td><td className="p-3">{c.orderCount} total · {c.paidOrderCount} paid</td><td className="p-3 text-sm">{new Date(c.lastActivity).toLocaleString("en-IN")}</td>{context.permissions.has("customers.financial.read")&&<td className="p-3 font-bold">{c.grossPurchaseValue===null?"N/A":"INR "+c.grossPurchaseValue}</td>}</tr>)}</tbody></table>{data.customers.length===0&&<p className="p-6 font-bold">No customers matched the current filters.</p>}</div>
  <footer className="flex items-center justify-between gap-3 text-sm font-bold"><span>{data.pagination.total} customers · page {data.pagination.page} of {Math.max(1,data.pagination.totalPages)}</span><div className="flex gap-2">{query.page>1&&<Link href={href(query.page-1)} className="border-2 border-black bg-white px-3 py-2 uppercase">Previous</Link>}{data.pagination.hasNextPage&&<Link href={href(query.page+1)} className="border-2 border-black bg-[#f7d51d] px-3 py-2 uppercase">Next</Link>}</div></footer>
 </section>;
}
