import Link from "next/link";
import {notFound} from "next/navigation";
import {requireAdmin} from "@/lib/admin/authorization";
import {getAdminCustomerDetail} from "@/lib/admin/customer-detail";
import CustomerActions from "@/components/admin/customer-actions";
import CustomerCommunicationPreferencesAdmin from "@/components/admin/customer-communication-preferences";
import { db } from "@/lib/db/client";
import { getCustomerCommunicationPreferences } from "@/lib/communications/preferences";

export const dynamic="force-dynamic";export const revalidate=0;

export default async function CustomerDetailPage({params}:{params:Promise<{customerId:string}>}){
 const context=await requireAdmin(undefined,"customers.read");const {customerId}=await params;let detail;
 try{detail=await getAdminCustomerDetail(customerId,context.permissions);}catch(error){if(error instanceof Error&&"code" in error&&error.code==="NOT_FOUND")notFound();throw error;}
 const communicationPreferenceData=context.permissions.has("communication.preference.read")?await getCustomerCommunicationPreferences(detail.customer.id):null;
 const marketingEmailPreference=communicationPreferenceData?.find((item)=>item.category==="MARKETING_PROMOTIONAL"&&item.channel==="EMAIL");
 const communicationAudit=context.permissions.has("communication.preference.audit.read")?await db.customerCommunicationPreferenceAudit.findMany({where:{customerId:detail.customer.id},orderBy:[{createdAt:"desc"},{id:"desc"}],take:100,select:{category:true,channel:true,previousState:true,newState:true,source:true,actorType:true,correlationId:true,reason:true,createdAt:true}}):null;
 return <section className="space-y-7">
  <div><Link href="/admin/customers" className="font-black uppercase underline">← Customers</Link></div>
  <header className="border-4 border-black bg-[#f7d51d] p-6 shadow-[8px_8px_0_0_#000]"><p className="text-xs font-black uppercase tracking-[0.2em]">Customer detail</p><h2 className="mt-2 text-4xl font-black uppercase">{detail.customer.displayName||"Unnamed customer"}</h2><p className="mt-2 break-all font-bold">{detail.customer.email}</p><p className="mt-1 text-sm">{detail.customer.id} · {detail.customer.status} · {detail.customer.emailVerifiedAt?"Verified":"Unverified"}</p></header>
  <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[["Orders",detail.metrics.totalOrders===null?"20+":String(detail.metrics.totalOrders)],["Paid orders",detail.metrics.paidOrders??"Restricted"],["Gross purchase",detail.metrics.grossPurchaseValue??"Restricted"],["Refunds",detail.metrics.refundValue??"Restricted"],["Net purchase",detail.metrics.netPurchaseValue??"Restricted"]].map(([l,v])=><article key={l} className="border-4 border-black bg-white p-4 shadow-[4px_4px_0_0_#000]"><p className="text-xs font-black uppercase">{l}</p><p className="mt-2 text-2xl font-black">{v}</p></article>)}</div>
  <CustomerActions customerId={detail.customer.id} displayName={detail.customer.displayName} status={detail.customer.status} updatedAt={detail.customer.updatedAt} canUpdate={context.permissions.has("customers.update")} canStatus={context.permissions.has("customers.status.manage")}/>
{context.permissions.has("communication.preference.read")&&marketingEmailPreference&&<CustomerCommunicationPreferencesAdmin customerId={detail.customer.id} canManage={context.permissions.has("communication.preference.manage")} canAudit={context.permissions.has("communication.preference.audit.read")} initialPreference={{ category: "MARKETING_PROMOTIONAL", channel: "EMAIL", state: marketingEmailPreference.state, version: marketingEmailPreference.version }} initialAudit={communicationAudit?.map((item) => ({ ...item, createdAt: item.createdAt.toISOString() })) ?? null}/>}
  <section className="border-4 border-black bg-white p-5"><h3 className="text-2xl font-black uppercase">Orders</h3><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead><tr className="border-b-2 border-black"><th className="p-2">Order</th><th className="p-2">Status</th><th className="p-2">Payment</th><th className="p-2">Fulfillment</th><th className="p-2">Shipment</th>{context.permissions.has("customers.financial.read")&&<th className="p-2">Total</th>}</tr></thead><tbody>{detail.orders.map(o=><tr key={o.id} className="border-b border-black"><td className="p-2 font-black">{o.orderNumber}</td><td className="p-2">{o.status}</td><td className="p-2">{o.paymentStatus}</td><td className="p-2">{o.fulfillmentStatus??"—"}</td><td className="p-2">{o.shipmentStatus??"—"}{o.trackingAvailable?" · tracking available":""}</td>{context.permissions.has("customers.financial.read")&&<td className="p-2">{o.currency} {o.total}</td>}</tr>)}</tbody></table>{!detail.orders.length&&<p className="pt-4 font-bold">No orders.</p>}</div></section>
  <section className="grid gap-5 lg:grid-cols-2"><article className="border-4 border-black bg-white p-5"><h3 className="text-2xl font-black uppercase">Payments</h3>{detail.payments===null?<p className="mt-4 border-2 border-black bg-[#e7e0d2] p-3 font-bold">Financial information restricted.</p>:<div className="mt-4 space-y-3">{detail.payments.map(p=><div key={p.id} className="border-2 border-black p-3"><strong>{p.status}</strong> · {p.currency} {p.amount}<p className="text-xs">{p.attemptCount} attempts · {p.refundCount} refunds</p></div>)}{!detail.payments.length&&<p>No payments.</p>}</div>}</article><article className="border-4 border-black bg-white p-5"><h3 className="text-2xl font-black uppercase">Returns & cancellations</h3><div className="mt-4 space-y-3">{detail.returns.map(r=><div key={r.reference} className="border-2 border-black p-3"><strong>Return {r.reference}</strong> · {r.status}<p className="text-xs">Order {r.orderNumber}</p></div>)}{detail.cancellations.map(c=><div key={c.reference} className="border-2 border-black p-3"><strong>Cancellation {c.reference}</strong> · {c.status}<p className="text-xs">Order {c.orderNumber}</p></div>)}{!detail.returns.length&&!detail.cancellations.length&&<p>No return or cancellation records.</p>}</div></article></section>
  {detail.cases&&<section className="border-4 border-black bg-white p-5"><h3 className="text-2xl font-black uppercase">Cases</h3><div className="mt-4 grid gap-3 md:grid-cols-2">{detail.cases.map(c=><Link key={c.reference} href={"/admin/cases/"+c.reference} className="border-2 border-black p-3 hover:bg-[#f7d51d]"><strong>{c.reference}</strong> · {c.status}<p className="text-sm">{c.title}</p><p className="text-xs">{c.priority}</p></Link>)}</div></section>}
  {!detail.cases&&<section className="border-2 border-black bg-[#e7e0d2] p-4"><strong>Case information restricted.</strong></section>}
  {detail.addresses&&<section className="border-4 border-black bg-white p-5"><h3 className="text-2xl font-black uppercase">Addresses</h3><div className="mt-4 grid gap-4 md:grid-cols-2">{detail.addresses.map(a=><article key={a.id} className="border-2 border-black p-4"><strong>{a.label}{a.isDefault?" · Default":""}</strong><p className="mt-2">{a.recipientName}</p><p>{a.addressLine1}{a.addressLine2?", "+a.addressLine2:""}</p><p>{a.city}, {a.stateOrProvince} {a.postalCode}</p><p>{a.countryCode}</p><p className="text-sm">{a.phone??"No phone"}</p></article>)}</div></section>}
  {!detail.addresses&&<section className="border-2 border-black bg-[#e7e0d2] p-4"><strong>Address information restricted.</strong></section>}
  <footer className="border-2 border-black bg-white p-4 text-sm">Created {new Date(detail.customer.createdAt).toLocaleString("en-IN")} · Updated {new Date(detail.customer.updatedAt).toLocaleString("en-IN")} · First order {detail.metrics.firstOrderDate?new Date(detail.metrics.firstOrderDate).toLocaleString("en-IN"):"None"} · Latest order {detail.metrics.mostRecentOrderDate?new Date(detail.metrics.mostRecentOrderDate).toLocaleString("en-IN"):"None"}</footer>
 </section>;
}
