export const CHANGE_LIFECYCLES=["DRAFT","SUBMITTED","IMPACT_ANALYZING","RISK_ASSESSING","PLAN_GENERATED","REVIEW_REQUIRED","APPROVAL_REQUIRED","APPROVED","REHEARSAL_REQUIRED","REHEARSING","REHEARSAL_CERTIFIED","READY_FOR_RELEASE","RELEASE_WINDOW_OPEN","DEPLOYING","POST_DEPLOYMENT_VALIDATING","VERIFIED","CERTIFIED","REJECTED","BLOCKED","ABORTED","ROLLED_BACK","ROLLBACK_FAILED","FAILED","EXPIRED","SUPERSEDED","CANCELLED"] as const;
export const CHANGE_RISKS=["LOW","MEDIUM","HIGH","CRITICAL","PROHIBITED"] as const;
export const POLICY_DECISIONS=["ALLOW","ALLOW_WITH_APPROVAL","ALLOW_WITH_REHEARSAL","BLOCK","PROHIBIT"] as const;
export const CHANGE_CATEGORIES=["CODE","CONFIGURATION","DATABASE_MIGRATION","PAYMENT","ORDER","FULFILLMENT","SHIPPING","SECURITY","PRIVACY","RELIABILITY","CAPACITY","FEATURE_FLAG","INFRASTRUCTURE","DEPENDENCY","ARCHITECTURE","DOCUMENTATION","OTHER"] as const;
export type ChangeLifecycle=typeof CHANGE_LIFECYCLES[number];export type ChangeRisk=typeof CHANGE_RISKS[number];export type PolicyDecision=typeof POLICY_DECISIONS[number];
export const RISK_ORDER:Record<ChangeRisk,number>={LOW:1,MEDIUM:2,HIGH:3,CRITICAL:4,PROHIBITED:5};
export const MAX_IMPACT_DEPTH=5,MAX_PLAN_STEPS=32,MAX_EVIDENCE=1000,MAX_CONCURRENT_RELEASES=3;
export function isClosed<T extends readonly string[]>(v:T,x:unknown):x is T[number]{return typeof x==="string"&&(v as readonly string[]).includes(x);}
export function sanitizeText(v:unknown,max=2000){return typeof v==="string"?v.trim().slice(0,max):"";}